### ISSUE TITLE
Too many entries in "What other URLs redirect to this page?" lead to Fatal Error

### ISSUE THREAD

**Issue by knoedelsalat** [processwire/processwire-issues#941] opened 2019-07-25 15:26 UTC
Something I've noticed in the last 5 or so installs of Processwire 3.0.123 on various servers.

Once a page has more than ~ 5 redirect paths under "Settings" -> "What other URLs redirect to this page?" the section won't open up anymore, therefore also making it impossible to delete redundant paths from the admin.

![2019-07-24-pagepathhistory](https://user-images.githubusercontent.com/47994733/61885583-560b0600-aefe-11e9-8b03-59e9d30affc3.png)

### Steps to reproduce the issue
1. Make sure PagePathHistory is installed
2. Add a couple of redirect paths (for me it's around 4 or 5, seems to depend on server memory limit)
3. Save the page and reopen "What other URLs redirect to this page?"
3. eventually the Ajax call will fail and you can't add or remove redirect paths anymore

PW v3.0.123. Anyone else been seeing this?
Regards, KN

**Comment by ryancramerdesign** [comment] 2019-09-25 10:44
@knoedelsalat Thanks for the report. I can't duplicate this one yet. I'm testing on the dev branch, but I don't think this matters for the PagePathHistory module since I think it is likely the same (haven't made changes to it in awhile). I tried adding 15 different redirect URLs of varying types and languages, but do not see any indication of error or slowdown. I'm wondering if there's something unique about your install or your URLs that isn't present on mine. Can you paste in the list of URLs you are adding that are not working? Also, does the page having the error have a large number of children or sibling pages? It might also be helpful to know what 3rd party modules are installed as well, just in case. Thanks.

**Comment by netcarver** [comment] 2019-10-29 19:12
@knoedelsalat Hello KN. Any further update on this?

**Comment by knoedelsalat** [comment] 2019-10-29 20:01
Hey, sorry for taking so long to respond.. Unfortunately I didn't take notes back when I encountered this issue. But it happened on both local Xampp installs and remote servers hosted at at least 2 different webhosts.

Managed to find only one case for now, but I'll try and dig up some more

page path:
```
/baumpflege
```

page_path_history paths are
```
/ueber-uns/baumpflege
/infos/warum-baumpflege
/faq
/category/infos/warum-baumpflege
```

The page has 5 child pages, no grandchildren.

All the redirects work, but opening the "What other URLs redirect to this page?" section fails.

As for modules, the only one used on all of those sites was rockettpw's markup-sitemap if I remember correctly.

I'll do some more testing on my end and report back. Thanks!

**Comment by knoedelsalat** [comment] 2019-10-29 21:50
Found another one.. Different site, different hosting provider.

Page path is
```
/was-ist-ein-glaukom
```

History paths
```
/behandlung
/diagnostik
/behandlungsschwerpunkt-gruener-star
/behandlungsschwerpunkte
/behandlung/behandlungsschwerpunkte
```

No children, four siblings, one parent page. 

Error message looks exactly the same, except the last line is missing:

![glaukom](https://user-images.githubusercontent.com/47994733/67811730-b54c5980-fa9d-11e9-9134-8c38c8b953d0.png)

**Comment by netcarver** [comment] 2019-10-29 21:54
@knoedelsalat Thank you.

@ryancramerdesign I've removed the "needs more info" label now.

**Comment by knoedelsalat** [comment] 2019-10-29 22:18
@netcarver Thanks. 

Something I just noticed, once I open the page for editing and just hover over "What other URLs redirect to this page?", Firefox Web Console starts throwing out
```
Empty string passed to getElementById().
```
Once I click to expand the section, the repeats on that warning are going up:

![glaukom2](https://user-images.githubusercontent.com/47994733/67813400-ba130c80-faa1-11e9-95b6-1356d1f91343.png)

Edit: Might actually be completely unrelated.. :-)

**Comment by phlppschrr** [comment] 2019-12-09 16:08
I am having a similar problem. I could reduce it to this simple test case:

I only have these 2 redirects on the site, and I get the same fatal errors as @knoedelsalat 
```sql
INSERT INTO `page_path_history` (`path`, `pages_id`, `language_id`, `created`)
VALUES
	('/a/b', 27, 0, '2019-12-09 16:58:30'),
	('/a', 27, 0, '2019-12-09 16:58:33');
````

Strangely, the "What other URLs redirect to this page?" section works when I add these redirects  to the homepage (id=1)

**Comment by chriswthomson** [comment] 2020-07-21 08:18
Hi,

I'm getting this too on some pages on a reasonably large site (15000+ pages). Appears to be a recursion error related to the 'virtual' option. If I set this to `false` in `ProcessPageEdit::buildFormPrevPaths`, I don't get the issue.

Going to investigate further and see what I can figure out.

Cheers,

Chris

**Comment by chriswthomson** [comment] 2020-07-21 10:42
Hello,

So for me the issue is caused when one of the redirect paths is a 'child' of the page itself e.g.

Page Path: /a/b/c
Redirect Path: /a/b/c/d

To resolve this I changed line 393 of /wire/modules/PagePathHistory.module (3.0.162) from

`if($parentPath !== '/' && $parentPath != $page->parent()->path()) {`

to

`if($parentPath !== '/' && $parentPath != trim($page->parent()->path(), '/') && $parentPath != trim($page->path(), '/')) {`

Without the trim here `$parentPath != $page->parent()->path()` always evaluates as `false` due to leading/trailing slashes. I've also added a check that the parent path inferred from the redirect path (`$parentPath`) does not equal the path of the page itself. This is the cause of the recursion error.

I'm not sure if my fix here will introduce further issues though - hopefully this explanation will allow @ryancramerdesign to replicate and fix.

Cheers,

Chris

**Comment by ryancramerdesign** [comment] 2020-07-31 13:35
Thanks @chriswthomson that clarified it for me. I have applied a fix based on the one you suggested. 

@knoedelsalat @phlppschrr Does this seem to be the same error you were observing and does the fix also resolve it for you?

**Comment by netcarver** [comment] 2020-11-14 12:22
@knoedelsalat, @phlppschrr Could you verify this fixes things for you - would like to close the issue if possible. Thank you.

**Comment by netcarver** [comment] 2020-12-02 11:08
Ok, closing now. Please post again if this needs reopening.

**Closed as completed by netcarver** 2020-12-02 11:08 UTC
Labels: status: fixed-please confirm
