### ISSUE TITLE
On a paginated template, if you go to a link that doesnt have any results you get ERR_TOO_MANY_REDIRECTS

### ISSUE THREAD

**Issue by cb2004** [processwire/processwire-issues#1569] opened 2022-05-18 09:32 UTC
Using the latest 3.0.200, I am not sure where this cropped up though. Usually I manage this with:

```
$news = $page->children("limit=12");
if(count($news) === 0) throw new Wire404Exception();
```
Or similar, in case my clients delete a load of items and the search engines are left with a link that returns nothing. I commented out the 404 line just to check but it seems the too many redirects error is thrown.

**Comment by ryancramerdesign** [comment] 2022-05-18 13:33
@cb2004 So far I can't duplicate this one here, I just get my 404 page when I do that on a paginated page. But here's a few things you can check: 

Since the 404 page usually has the same _main.php as the rest of the site, maybe there's some logic that generates the footer, navigation, or something else that is causing the redirect loop. 

A common pattern when reaching an out-of-bounds pagination is to redirect (302) back to the first pagination. This is preferable to 404s when it comes to direct incoming traffic for obvious reasons. Do a grep on all your template files for 'redirect' or 'location' to see if you have anything like that. 

When pagination is involved, check also if there are any other $pages->find() or $page->children(), etc. with a "limit=n" that are also getting paginated that you don't intend to.  Think of a common "latest news" in the footer, for example. Perhaps some related logic is issuing a redirect, and may need  a "start=0"  or "limit=0,n" added to the selector. 

Monitor your browser dev tools Network panel to see if the redirects are to variations of trailing slash for the same URL.

**Comment by cb2004** [comment] 2022-05-18 15:13
@ryancramerdesign I thought you were on the right lines with the search for news in multiple places, but that didnt fix it, it did stop me searching for news in the _main.php template and the news-summary.php template and then hiding the section from main.php so at least you guided me to an optimisation :)

The problem is it is trying to redirect to page17 and not page17/ but I have 'Should page number URLs have a trailing slash?' set to yes. If I change it to 'No', or 'Either / does not matter' then it works. So the bug is with when it is set to 'Yes'.

I like your idea of redirecting to page 1, but I cant do that until this bug is fixed anyway.

**Comment by cb2004** [comment] 2022-05-18 15:28
@ryancramerdesign just to add I could add in the $session->redirect with any of the trailing slash settings and it all worked fine, so its an issue with throw new Wire404Exception()

**Comment by ryancramerdesign** [comment] 2022-05-20 13:58
Thanks @cb2004 I was able to reproduce it after setting the template to require a trailing slash for pagination segments. I have pushed a fix. Can you confirm it also fixes it there?

**Comment by matjazpotocnik** [comment] 2022-08-13 08:51
@cb2004 Closing on the assumption this is fixed. Please comment if that is not the case.

**Closed as completed by matjazpotocnik** 2022-08-13 08:51 UTC
Labels: status: fixed-please confirm
