### ISSUE TITLE
FieldtypePage: Selectability of unpublished pages depends on chosen input field class

### ISSUE THREAD

**Issue by rwetzlmayr** [processwire/processwire-issues#2] opened 2016-09-25 06:08 UTC
Steps to reproduce with a recent devns clone:

1. Add a field of type 'Page' to a template.
1. Configure its input field type to 'Select Multiple'
![screenshot - 11 08 2016 08_53_35](https://cloud.githubusercontent.com/assets/357054/17580741/2b377904-5fa1-11e6-956c-9e5a341ae451.png)

1. Uncheck 'Allow unpublished pages?'
1. Unpublish one of the eligible pages, e.g. 'Child page example 1' from the stock basic site profile.
1. Create a page using this template and find that 'Child page example 1' is *not* an available option
![screenshot - 11 08 2016 08_38_30](https://cloud.githubusercontent.com/assets/357054/17580662/a271aae0-5fa0-11e6-9cd0-6106872509b2.png)

1. Configure the 'Page' field's input field to one of 'PageListSelect', 'PageListSelectMultiple', 'PageAutocomplete'.
1. Create a page using this template and find that 'Child page example 1' is an available option
![screenshot - 11 08 2016 08_43_03](https://cloud.githubusercontent.com/assets/357054/17580666/b08760e8-5fa0-11e6-9c2a-844cc8a71366.png)
![screenshot - 11 08 2016 08_49_58](https://cloud.githubusercontent.com/assets/357054/17580670/b6be264a-5fa0-11e6-85e3-f91f048b9437.png)

I think this confuses users as the unpublished pages, while selectable, are not persisted when 'Allow unpublished pages?' is unchecked.

(This issue is a resurface attempt for https://github.com/ryancramerdesign/ProcessWire/issues/1973, as suggested in #1)

**Comment by isellsoap** [comment] 2016-09-26 07:11
I tried to reproduce your issue with the latest ProcessWire version (3.0.34) from the [new repository](https://github.com/processwire/processwire), and I had to stop at step #5, because the unpublished page appears in the page field:

![bildschirmfoto 2016-09-26 um 09 05 28](https://cloud.githubusercontent.com/assets/477474/18825416/89ead07c-83c8-11e6-9da7-784f475c1282.png)

Please specify your exact ProcessWire version ("recent devns clone" isn’t very specific). Can you try it also with the newest ProcessWire version and confirm my observation? If you can, please upgrade to the latest ProcessWire version. In the meantime, I will label this issue "not reproducible".

**Comment by rwetzlmayr** [comment] 2016-09-26 09:06
I can reproduce this issue's step 5 w/ PW 3.0.34 from the new repo while I cannot confirm your observation.

I believe that the code building the selector which excludes unpublished pages from the `InputfieldSelectMultiple` element is [here](https://github.com/processwire/processwire/blob/bac5b0de5d95b5a10c09f48ba5e63b419ee68799/wire/modules/Inputfield/InputfieldPage/InputfieldPage.module#L315).

I think that this code path is executed when the Page field is configured to **not** `Allow unpublished pages?`  and has a `Template of selectable page(s)` set, and thus the situation in step 5 should be reproducible.

Would you mind re-checking whether your PW instance uses the Page field with these two settings in effect?

**Comment by isellsoap** [comment] 2016-09-26 09:17
Sorry, I didn’t fully comprehend the issue you were having. You are right, I can reproduce the issue.

**Comment by ryancramerdesign** [comment] 2016-09-26 10:43
This feature was added awhile back at Teppo's request (if I recall), and it's something that FieldtypePage supports, but not all page selection Inputfield types. I may be able to have the autocomplete one just omit unpublished pages for this case, but if not then certainly a strikethrough on the label (or something like that) would be worthwhile. We can't omit unpublished from the page tree just because a parent may be unpublished while the children might not be. Because support really depends on the Inputfield type (whether or 3rd party), I'll solve this issue by having it issue a save warning that unpublished pages aren't allowed to be stored in the selection. I'm also thinking in some cases we may be able to automatically append "(unpublished)" label to the selected label for additional clarity.

**Comment by ryancramerdesign** [comment] 2016-10-04 10:17
I've pushed a fix for this issue. For PageListSelect types it provides a warning when the page is saved. For Autocomplete, I was able to have it suppress showing of unpublished pages.

**Closed** 2016-10-04 10:17 UTC
Labels: severity: low, status: work in progress, type: consistency, type: fields, type: page status
