### ISSUE TITLE
Inputfield Dependencies: showIf is breaking saved values

### ISSUE THREAD

**Issue by mikerockett** [processwire/processwire-issues#140] opened 2016-12-29 15:22 UTC
### Short description of the issue

With inputfield dependencies, fields that have the `showIf` dependency property lose their values when saved, but only when hidden. (Tested in `ModuleConfig`.)

### Actual behavior

For example, I have a checkbox field called `default`. I then have other fields that depend on this field, such as `wrapNumbers`, where `showIf` == `default=0` and is value defaults to 1 (true). In my case, `default` is true (1) by default. If I save the module config without changing anything, all the defaults are lost, and these fields save as `null` in the database.

### Expected behavior

Field values should retain their saved state, but should simply not show if they are not meant to. An additional measure could be that the field is not available to the module if it is intended to be hidden. That could perhaps be overkill, but the point of the matter is that the config fields should not be saved as `null`.

### Steps to reproduce the issue (untested outside of `ModuleConfig`)

1. Create a field called `default` and set the default value to `true`.
2. Create another field with any name, set its default value to `true` and set the `showIf` property to `default=0`.
3. Open the configuration and save.
4. When reloading and unchecking `default`, the second field will be `false` because it is `null` in the database.

### Setup/Environment

* ProcessWire version: 3.0.42

**Comment by ryancramerdesign** [comment] 2017-01-02 12:52
If I read it correctly, the behavior you describe sounds like the intended behavior. When a showIf causes a field not to appear in the form, the field that does not appear is simply not processed at the server side. Meaning, it no longer participates in the form data. If it did still process them, then it would be possible for someone to manipulate values in fields they aren't supposed to be able to, via their browser inspector. 

If you see a config property that's null, in PW that usually means that it was never set. So that makes me wonder what module configuration method are you using? For most cases, it's a good idea to establish your default config values in your module's __construct() method, though some of the newer configuration methods (when used) will handle this for you.

**Comment by mikerockett** [comment] 2017-01-02 13:09
I'm using ModuleConfig as I do prefer the automated approach. So is this is a simple case of the fact that ModuleConfig is not showing defaults for properties that are saved as `null` in the DB?

**Comment by mikerockett** [comment] 2017-01-02 13:11
For some insight, this is the config class I noticed this with: https://github.com/rockettpw/textformatter-typographer/blob/master/TextformatterTypographerConfig.php

**Comment by ryancramerdesign** [comment] 2017-01-02 14:29
Your getDefaults() method looks good, though I have concerns about the `showIf` checkbox stack (more below). A few things to try– 

For any fieldsets that have "showIf" conditions, try giving them id/name attributes. Probably won't matter, but worth a try. 

This showIf `defaults=0,enabled=1` appears to be a double-stacked checkbox, since `enabled` is a checkbox, and `defaults` is also a checkbox and also has a showIf condition on it that also references `enabled`. I think this is potentially problematic. By nature checkbox inputs are weird because their non-presence in a POST can either mean they were unchecked, or they were not present at all, unlike all other input types. We've got the autocheck option to help, but this doesn't solve everything. When you run into a combination like this that doesn't work with a checkbox, I suggest switching instead to a Yes/No labeled radio button toggle (with 1 and 0 as values). These are more predictable since they always participate in the POST submission. Also, just in case, change the order of your showIf condition to be consistent with the order of fields in the form`enabled=1,defaults=0`. 

Try adding "implements ConfigurableModule" to the end of your module class definition, and then do a Modules > Refresh. 
~~~~~
class TextformatterTypographer extends Textformatter implements Module, ConfigurableModule {
~~~~~
Next, take a look at your /site/config.php file to see if you might have any settings present for `$config->InputfieldWrapper`? Chances are you don't, but wanted to double check, just in case.

Last thing I was wondering about is the "defaults" name, and a potential name collision since the same name is used when referring to module configuration default values. I doubt this is the problem, but it might be worth trying a different name on the off-chance that you are seeing a name collision of some sort. However, I honestly think the most likely case is just the stacked showIf + checkbox ModuleConfig can't be processed due to the stack. If making the suggested changes doesn't make any difference, then I'd like to experiment with your module's code in testing here if you don't mind.

**Comment by mikerockett** [comment] 2017-01-02 15:28
Thanks - I have tried the following:

- Change `showIf` orders
- Add `name+id` to fieldsets
- Add module class implementations
- Rename `defaults`

Haven't tried the radio-selects, but I don't think I like that particular idea for the config, considering that a checkbox is the desired switch-toggle for these settings. The methodology behind it is understood, however.

For the most part, I see what could be happening. You're more than welcome to play around with it.

I think that it would be nice to have the stacked option - perhaps some kind of detection mechanism for these kinds of dependencies could work (just thinking off the top of my head).

I could well scrap the defaults checkbox, but PHP Typographer sets the defaults, so I don't want to have to set them again from the default config, which matches the libary's defaults.

My other option would be to use AsmSelect to override the defaults on an individual basis. I could also enforce the library to not set it's own defaults, leaving such up to the module itself.

**Comment by netcarver** [comment] 2018-07-31 23:08
@mikerockett Were you ever able to get to the bottom of this?
@ryancramerdesign 

> If making the suggested changes doesn't make any difference, then I'd like to experiment with your module's code in testing here if you don't mind.

Did anything come of this?

**Comment by netcarver** [comment] 2019-02-14 23:11
Bumping this again for reconsideration. 

@mikerockett Is this still an issue for you?
@ryancramerdesign Ryan, did anything come of your testing?

**Comment by mikerockett** [comment] 2019-02-15 09:09
@netcarver Hey, haven't been working with PW for a while now so don't have an update, sorry…

**Comment by netcarver** [comment] 2019-02-15 09:39
@mikerockett Ok, Mike, thank you.

@ryancramerdesign Any action you want to take on this issue? Shall I close?

**Comment by netcarver** [comment] 2019-03-07 16:48
This seems to have gone cold, so closing. Please feel free to post more, if needed, @mikerockett.

**Closed by netcarver** 2019-03-07 16:48 UTC
