### ISSUE TITLE
InputfieldSelector wraps custom selectors with `_custom="<selector>"`

### ISSUE THREAD

**Issue by abdusco** [processwire/processwire-issues#257] opened 2017-05-02 17:54 UTC
### Short description of the issue

I'm building a module and and I've added an `InputfieldSelector` in its configuration page. When I build a write <selector> using custom field, `$selector->value` returns `_custom="<selector>"`. 

For example, I write `id>0`, but it returns `_custom="id>0"`. When I want to match a page against the selector using `$page->match($selector)`, it returns `false`, where it should have returned `true` instead.

### Expected behavior

It should return `"<selector>"`

### Actual behavior

It returns `_custom="<selector>"`

### Steps to reproduce the issue

1. Install `InputfieldSelector`, create a field, add to a template. Pick **custom (field=value)**, write `id>0`, save the page.
2. Check `$page->selector`, it returns `_custom="id>0"`

### Setup/Environment
**ProcessWire**: 3.0.61  
**PHP**: 7.0.15-0ubuntu0.16.04.4  
**Apache**: Caddy/0.9.4  
**MySQL**: 5.7.18-0ubuntu0.16.04.1

**Comment by Toutouwai** [comment] 2017-05-03 07:34
I tested this and InputfieldSelector is working normally for me, both when used as an inputfield alone in a module configuration and when used with FieldtypeSelector in a template.

Not sure what could cause the issue you're seeing.

![2017-05-03_192233](https://cloud.githubusercontent.com/assets/1538852/25651450/40ffb758-3037-11e7-8602-960eb4cf0021.png)

**Comment by abdusco** [comment] 2017-05-03 07:38
It works fine for other fieldsm but not for custom input.  
Here is how it looks on my end:
![chrome_2017-05-03_10-36-10](https://cloud.githubusercontent.com/assets/3243482/25651558/6b097e44-2fec-11e7-9f3e-65605f469dee.png)

And the code I used for the input
```php
        // SELECTOR =================
        /* @var $selector InputfieldSelector */
        $selector = $this->modules->InputfieldSelector;
        $selector->name = 'selector';
        $selector->label = $this->_('Select pages');
        // fill it with any value saved before
        $selector->value = $this->selector;

        $selector->description = $this->_('...');
        $selector->notes = $this->_('...');
        $wrapper->add($selector);
```

**Comment by Toutouwai** [comment] 2017-05-03 07:42
Sorry, I didn't read thoroughly enough. 
I can confirm the issue with a 'custom (field=value)' selector.

**Comment by ryancramerdesign** [comment] 2017-05-05 13:57
InputfieldSelector generates selectors appropriate for `$pages->find()` queries. It supports database-specific features. So it may not be a good pair with `$page->match()`. 

A "_custom" selector requires a handler. ProcessWire's `$pages->find()` method has a handler for it if you enable the `allowCustom` option as part of the `$options` argument to the find() method: https://processwire.com/api/ref/pages/find/

For your module, if you want to support "_custom" with `$page->match()` as you did, I'd suggest using `$pages->count()` instead to get the same result with a method that would support the type of query you are wanting to use. 
~~~~~
$options = [ 'allowCustom' => true, 'include' => 'unpublished' ]; 
if($pages->count($selector, $options) > 0) {
  // page matches
} else {
  // doesn't match
}
~~~~~

**Comment by abdusco** [comment] 2017-05-06 00:16
I may be missing the point here, but I think of `InputfieldSelector` as a superset of the plain text field. So if I can type in arbitrary content into text field, I should be able to specify arbitrary selectors using `custom` field.

What I want to achieve is to determine if **current** page matches the given selector and set up hooks based on that. Based API docs `$pages->count($selector)` wouldn't be able to determine whether current page matches or not, it just counts instances of pages matching the selector.

I think implementing a switch like `allowCustom` for `InputfieldSelector` to allow custom selectors with the freedom of specifying any selector, and the safety of built-in sanitization would be a great.

**Comment by Toutouwai** [comment] 2017-05-06 01:42
@ryancramerdesign, could you please explain why a "_custom" selector in InputfieldSelector needs to return the "_custom=" part of the string in the first place? Wouldn't it be better if it just returned the custom selector itself? Then the preview of matched pages in the inputfield would be correct - currently it doesn't work correctly, see screenshots below.

Correct
![2017-05-06_133631](https://cloud.githubusercontent.com/assets/1538852/25768899/b9fc573e-3261-11e7-9bdf-d5abcaafc0bc.png)

Incorrect
![2017-05-06_133613](https://cloud.githubusercontent.com/assets/1538852/25768898/b9f9ad36-3261-11e7-9788-a51b663cf6d2.png)


I'm sure there's a good reason for the "_custom=" and "allowCustom" option in PageFinder but it's not obvious to me.

**Comment by teppokoivula** [comment] 2017-05-06 05:35
Agreed. While allowCustom might not be something that one comes across too often, it is part of the public API, and the docs don't currently explain what this feature is for. In my opinion "for specific uses" isn't a very good explanation :)

**Comment by LostKobrakai** [comment] 2017-05-08 06:42
The usecase is that InputfieldSelector can differenciate what parts were added as custom selector and what parts via the other dropdowns. Before that feature was added complex custom selectors often where later rendered as their "native" selector dropdowns, which didn't necessarily support the value, which was added in the custom selector. 

> Based on API docs, $pages->count($selector) wouldn't be able to determine whether current page matches or not, it just counts instances of pages matching the selector.

Just add `id=$page->id` to the selector and it either matches the selector or not.

**Comment by ryancramerdesign** [comment] 2019-04-04 16:53
Going to close this one out for now since I don't think there's any more we can do with this, but what LostKobrakai suggested (adding the id=page_id) is a good solution for the page matching need presented in this issue report. Another alternative is that you could convert the _custom part of the selector before performing your match. The resulting selector can't be used by InputfieldSelector anymore, but for a runtime matching usage thing it should be just fine:
~~~~~~
$a = [];
foreach(new Selectors($selectorString) as $s) {
  $a[] = $s->field() == '_custom' ? $s->value() : "$s";
}
$newSelectorString = implode(', ', $a); 
~~~~~~

**Closed by ryancramerdesign** 2019-04-04 16:53 UTC
Labels: status: discussion, status: impacts multiple users
