### ISSUE TITLE
Redirecting to an access restricted template from an access restricted template you can see the page

### ISSUE THREAD

**Issue by postscript-chris** [processwire/processwire-issues#876] opened 2019-05-09 19:16 UTC
I stumbled across this one by accident, so I suppose it could be classed as user error, but I feel a warning or something should come into play here.

I was locking down a template and was redirecting to the login page (I thought), but instead I was putting the ID in of the members area by mistake (also locked down). When I was visiting the page it was allowing me access to the page that should have been access restricted.

Latest version of PW dev.

**Comment by teppokoivula** [comment] 2019-05-18 15:14
I can confirm this issue. Instead of redirecting to the page – which should in turn result in whatever action that the template of the target page is set to perform when user doesn't have access – the target page (with matching ID) is instead rendered in place of the current page.

So technically there are two strange things here: missing access restriction, and missing redirect.

Since the title of the option is "Enter the URL or page ID **you want to redirect to** when a user doesn't have access", a redirect would be the expected behaviour... or, in case that typing in an ID skips redirect intentionally, this should be mentioned in context :)

**Comment by ryancramerdesign** [comment] 2019-06-26 16:14
@postscript-chris Thanks I have pushed an update to clarify and expand upon the wording to better explain how this setting works. Using page ID renders the page rather than redirecting to it and is primarily intended for allowing one to maintain login pages that are in an access protected area (like PW's admin login).

**Comment by netcarver** [comment] 2019-10-12 16:13
@postscript-chris This has been marked as fixed for a while now with no reply, so I'll close it. Please post here again if needed and I can re-open the issue. Thank you.

**Closed as completed by netcarver** 2019-10-12 16:13 UTC
Labels: resolution: fixed-please close, status: multiple
