### ISSUE TITLE
PHP empty() function always returns true on Pageimage properties

### ISSUE THREAD

**Issue by 16th-earl** [processwire/processwire-issues#1036] opened 2019-11-15 04:24 UTC
### Short description of the issue

Applying the PHP empty() function to a property of a Pageimage object always returns TRUE regardless of the value of the property.

### Expected behavior

```
// $img is an object of class Pageimage, which has a valid name.
empty($img->name) === false
empty($img->width) === false
empty($img->propertyThatDoesNotExist) === true
```

### Actual behavior

```
// $img is an object of class Pageimage, which has a valid name.
empty($img->name) === true
empty($img->width) === true
empty($img->propertyThatDoesNotExist) === true
```

### Setup/Environment

* ProcessWire version: 3.0.142
* (Optional) PHP version: 5.4.16

**Comment by matjazpotocnik** [comment] 2019-11-16 16:27
```
var_dump($img->basename); //string "img.jpg"
var_dump($img->name); //string "img.jpg"
var_dump($img->width); //int 1600
var_dump($img->description); //string ""
var_dump($img->foo); //NULL

var_dump(empty($img->basename)); //bool(false)
var_dump(empty($img->name)); //bool(true)
var_dump(empty($img->width)); //bool(true)
var_dump(empty($img->description)); //bool(true)
var_dump(empty($img->foo)); //bool(true)

var_dump(empty($img->get('basename'))); //bool(false)
var_dump(empty($img->get('name'))); //bool(false)
var_dump(empty($img->get('width'))); //bool(false)
var_dump(empty($img->get('description'))); //bool(true)
var_dump(empty($img->get('foo'))); //bool(true)

function is_empty($var) {
	return empty($var);
}

var_dump(is_empty($img->basename)); //bool(false)
var_dump(is_empty($img->name)); //bool(false)
var_dump(is_empty($img->width)); //bool(false)
var_dump(is_empty($img->description)); //bool(true)
var_dump(is_empty($img->foo)); //bool(true)
```
I'm sure there is a logical explanation, but I'm no PHP expert. I think it has something to do with classes and get() method. And there also must be a reason why empty() on $img->name and $img->basename returns different value.

**Comment by ryancramerdesign** [comment] 2019-11-20 15:26
@16th-earl @matjazpotocnik Technically those properties are empty as far as PHP goes, they don't actually exist and are just aliases of other properties or method calls. I don't recommend using isset() or empty() on object properties like that, but if you think it'd be useful I can override the __isset() method to return true for alias properties or method calls (assuming it doesn't cause issues elsewhere). The return value of an __isset() method is what is returned by PHP's isset() and !empty() on object instances. The current behavior for WireData derived objects is to return true only for properties that can be both read from and written to (tangible properties). That's why empty(basename) would return false and empty(name) would return true. This is an expected/intended behavior, but I understand it may not be obvious so if you think there's a good use case for Pageimage let me know and we can revisit for that class.

**Comment by matjazpotocnik** [comment] 2019-11-22 07:42
@ryancramerdesign Thank you for the explanation. If I'm not wrong you already implemented __isset() in this commit: https://github.com/processwire/processwire/commit/8455e497b7dcaf176bd868a651cb1df02989ca81 ? @16th-earl Would you please test and then close the issue?

**Comment by netcarver** [comment] 2019-12-21 14:15
Look good, closing this now. @16th-earl  Please post again here if this needs re-opening.

**Closed as completed by netcarver** 2019-12-21 14:15 UTC
Labels: status: discussion
