### ISSUE TITLE
Getting a PDO exception error after updating to 3.0.185 

### ISSUE THREAD

**Issue by lesaff** [processwire/processwire-issues#1446] opened 2021-10-04 19:54 UTC
### Short description of the issue
Recently updated my local project from 3.0.184 to 3.0.185 dev version. Right after the upgrade, I got the following PDO error:

`SQLSTATE[42S22]: Column not found: 1054 Unknown column 'pages_paths.language_id' in 'field list'`

### Optional: Screenshots/Links that demonstrate the issue

![CleanShot 2021-10-04 at 16 52 46](https://user-images.githubusercontent.com/1151181/135915522-b1debd22-d5ac-46ba-a67b-025db7e5d0eb.png)

### Steps to reproduce the issue

1. Update from 3.0.184 to 30.185 (dev version as of 2021/10/04)
Note: This particular site does not have additional languages.

### Setup/Environment

* ProcessWire version: 3.0.185 dev
* (Optional) PHP version: 7.4.22
* (Optional) MySQL version: 5.7.23

**Comment by adrianbj** [comment] 2021-10-04 19:55
Duplicate of https://github.com/processwire/processwire-issues/issues/1444

**Comment by ryancramerdesign** [comment] 2021-10-05 12:52
@lesaff Thanks, I've attempted a fix for this issue. I am not seeing the issue on any installs so don't have a way to confirm it's actually fixed, are you able to test it?

@adrianbj This issue is similar, but not a duplicate as it's for the PagePaths module rather than the PagePathsHistory module. In the commit to fix this one though I also bumped the version number for PagePathsHistory, hoping that might trigger the necessary schema change for #1444

**Comment by lesaff** [comment] 2021-10-05 13:03
@ryancramerdesign Thanks for the fix. I just tested it on a PW 3.0.184 and it successfully updated the site, and added `language_id` column to both `pages_paths` and `page_path_history` tables.

**Comment by adrianbj** [comment] 2021-10-05 13:37
@ryancramerdesign  - sorry for the incorrect flag as a duplicate. I just updated to the latest version and it didn't initially fix my page_path_history table, but then I installed the Page Paths module and did a rebuild and after that the `language_id` field was added to my page_path_history table. So maybe that is the difference between your setup and mine?

**Comment by adrianbj** [comment] 2021-10-09 02:31
@lesaff - do you have the Page Paths module installed? It would be good to know if you do, because that seemed to be the difference for me and I want to make sure @ryancramerdesign doesn't miss this if that is indeed the reason why it didn't work for me initially.

**Comment by matjazpotocnik** [comment] 2023-06-15 08:22
@lesaff @adrianbj is this still relevant?

**Comment by adrianbj** [comment] 2023-06-15 15:18
@matjazpotocnik - sorry, not really sure - I haven't upgraded a ML site from that version for a long time.

**Comment by matjazpotocnik** [comment] 2023-06-16 08:15
Closing then, please reopen if needed. Thanks!

**Closed as completed by matjazpotocnik** 2023-06-16 08:15 UTC
