### ISSUE TITLE
Continue to git tag releases

### ISSUE THREAD

**Issue by isellsoap** [processwire/processwire-issues#63] opened 2016-10-29 07:50 UTC
You stopped tagging releases since the 3.0.36 release.

3.0.37 --> https://github.com/processwire/processwire/commit/4a26b774bfc587b915b113a53d726257af02ff0d
3.0.38 --> https://github.com/processwire/processwire/commit/57fd7412321e87933609e37dddd33332894ecb92
3.0.39 --> https://github.com/processwire/processwire/commit/f7c613d39d70f426674bd94c9a9e86086d0fbb4f

Please continue to tag releases.

**Comment by adrianbj** [comment] 2016-10-30 04:51
I believe the issue is that none of these versions have been pushed to master yet - they are still only on the dev branch at the moment.

**Comment by ryancramerdesign** [comment] 2016-10-31 14:12
Adrian's right, I've been tagging once I merge to master. Hopefully can merge 3.0.40 to master and then tag that as the next this week. Is there any value in tagging it while still on dev? I just didn't want it to look like a release. The dev version increments are just to connect with the weekly blog posts, but I don't really want it showing up in the Git tag list.

**Comment by ryancramerdesign** [comment] 2016-11-03 14:04
I'm going to close this, but if you think there would be a lot of value in tagging everything even on the dev branch, just let me know. My plan was to focus tags on the master branch, but you know Git better than me so if you think I should do it differently just let me know and I'll follow your suggestion.

**Closed by ryancramerdesign** 2016-11-03 14:04 UTC
