### ISSUE TITLE
Repeater templates shows up in page settings for superusers

### ISSUE THREAD

**Issue by abdusco** [processwire/processwire-issues#388] opened 2017-09-28 06:57 UTC
### Short description of the issue

When changing template for a page in the page editor ProcessPageEdit, repeater templates show up in the template list.

[Here's the relevant forum discussion](https://processwire.com/talk/topic/17304-repeater-fields-appears-in-template-settings-of-any-page/)  
Also:  https://github.com/processwire/processwire-issues/issues/287

### Expected behavior

They shouldn't be on the list.

### Actual behavior

They are on the list when user is superuser

### Optional: Screenshots/Links that demonstrate the issue

Your screenshots/links go here.
![image](https://user-images.githubusercontent.com/3243482/30952958-a074aca6-a432-11e7-9843-0bb0d08385c5.png)

### Optional: Suggestion for a possible fix

Superuser or not repeater templates shouldn't be used anything other than repeater items. Since repeater items are assigned their template using API, and these templates are used for nothing else, they shouldnt show up at all.

Here's a possible fix:  
https://processwire.com/talk/topic/17304-solved-repeater-fields-appears-in-template-settings-of-any-page/?do=findComment&comment=151971

**Comment by beatep** [comment] 2017-09-28 07:35
Duplicate of https://github.com/processwire/processwire-issues/issues/287

**Comment by ryancramerdesign** [comment] 2017-10-12 14:53
Thanks, I've pushed a fix for this issue.

**Closed** 2017-11-03 11:32 UTC
Labels: resolution: fixed (close when ready)
