### ISSUE TITLE
Dragging an image into CKeditor uploads it to several single image fields in the page

### ISSUE THREAD

**Issue by ocorreiododiogo** [processwire/processwire-issues#747] opened 2018-11-14 06:48 UTC
### Short description of the issue

When there is one or more single image fields in the template and the ckeditor field is set to upload to one multiple images field, when a image is dragged or pasted there the  .
single fields are also populated.

### Expected behavior

Dragging an image into a CKeditor field populates only the  images field that is selected in it's settings.

### Actual behavior

Dragging an image into a CKeditor field populates a all the single image fields in the page besides the images field that is selected in it's settings.

### Steps to reproduce the issue

1. Create template with one multiple images and more then one single image fields
2. Create page with that template
3. Drag an image inside the textarea of CKeditor
4. Verify if it appeared on the single images field

### Setup/Environment

* ProcessWire version: 3.0.118
* (Optional) PHP version: php72rc

**Comment by ryancramerdesign** [comment] 2018-12-06 17:35
@ocorreiododiogo I can't seem to duplicate this one. I started with a new installation and regular profile. The page I'm testing on has 1 multi-image field (named "images") and 2 single-image fields (named "image1" and "image2"). I drag an image into CKEditor and it uploads to the multi-image field ("images"). It doesn't matter where I move the locations of the image fields above or below CKEditor, or change the order of the image fields. That's because it's not supposed to upload to single-image fields from CKEditor at all (at least, that's the intention). Next I tried manually specifying that "images" was the field allowed for image uploads in the CKEditor settings (Setup > Fields > body > Input > CKEditor > "Images fields that may be used for dragged-in or pasted-in images". This doesn't seem to change anything. It still uploads to the right place. Can you think of anything I missed or any other factors that might be present (like other modules or the like)? Thanks.

**Comment by netcarver** [comment] 2019-03-06 18:41
@ocorreiododiogo Hi Diogo, are you able to assist Ryan with any more information about how to reproduce this - or perhaps give him access to a site that exhibits the behavior?

If no one else can reproduce this I'm inclined to close it in a few weeks.

**Comment by teppokoivula** [comment] 2019-04-13 15:36
Just tried to reproduce this, but no luck here either – everything seems to work as expected. Could be something specific to the environment @ocorreiododiogo is running the site in, some hook or module causing problems – or perhaps this was fixed already.

**Closed** 2019-04-29 14:45 UTC
Labels: status: can't reproduce
