### ISSUE TITLE
Javascript Issues with expanding/collapsing fieldset within repeater item

### ISSUE THREAD

**Issue by jlahijani** [processwire/processwire-issues#536] opened 2018-03-14 19:18 UTC
Video:
http://www.youtube.com/watch?v=WZ2MZ9tXRCw

**Comment by matjazpotocnik** [comment] 2018-03-14 19:37
I think this is an issue (for a long time, at least for me) on all fieldsets that are initially open. You have to click the arrow on the right to collapse the fieldset, after that you can click anywhere to either expand it or collapse it again.

![fieldset](https://user-images.githubusercontent.com/7663992/37426641-66e523e4-27c7-11e8-844c-74651d211a6d.gif)

**Comment by ryancramerdesign** [comment] 2018-03-15 13:22
This is the intended behavior, and true for all Inputfields (not just Fieldsets). When not setup as a collapsed Inputfield, clicking a field label is supposed to focus the input within it (text, textarea or select). This is basically standard behavior for any HTML form using label elements with "for" attributes that point to the input. 

However, unlike a standard HTML form, any field in our forms can be open or collapsed. So if you've got an Inputfield that is collapsed, then it has to be opened before it can be focused or used. A collapsed Inputfield shows the label, but there is no visible input to focus on. So we must open the Inputfield before it can be focused or interacted with. As a result, clicking on the label opens the Inputfield, so that it can complete the focus. Once the label is used in that manner, there's a good chance you might repeat the action to close it, so the behavior sticks. Either way, the right-side toggle icon is the universal way to open/close any Inputfield. We're trying to be consistent with HTML forms while also supporting open/collapsed fields. Maybe it would be more clear if the label never opened the field, but I would also find that a lot less convenient. 

Since this is true of all Inputfields, it's also true of Fieldsets (since they are also a type of Inputfield). Maybe a different behavior would be an enhancement for Fieldsets, so that they always open/collapse when clicking the label. But since the current behavior is intended, I'll revisit this one a little later, after the master version is out. Thanks.

**Comment by matjazpotocnik** [comment] 2018-03-15 15:50
Thank you for the explanation!

**Closed** 2018-03-15 17:31 UTC
Labels: resolution: not a bug
