### ISSUE TITLE
Page Edit Link – Attribute options forced to multiple lines

### ISSUE THREAD

**Issue by lanceosborne** [processwire/processwire-issues#1725] opened 2023-04-26 19:28 UTC
### Short description of the issue

Adding an attribute value that includes a space to the **Attribute options** > **rel** field of the **Page Edit Link** module results in the value being separated into multiple lines.

### Expected behavior

The original expected behavior from **Page Edit Link** version 1.0.9 allows an entry of "noreferrer noopener" on one line.

### Actual behavior

The new behavior from **Page Edit Link** version 1.1.2 does not retain an entry of "noreferrer noopener" on one line. Once the page is saved, "noreferrer" and "noopener" are forced to two lines.

### Screenshots

[Version 1.0.9 after page save](https://www.dropbox.com/s/x8m3vdp4m2rhr86/Screen%20Shot%202023-04-25%20at%204.42.07%20PM.png?dl=0)

[Version 1.1.2 after page save](https://www.dropbox.com/s/khwq58bsvzfxexo/Screen%20Shot%202023-04-25%20at%204.42.25%20PM.png?dl=0)

### Steps to reproduce the issue

1. Enter "noreferrer noopener" as one line in the **Attribute options** > **rel** field of the **Page Edit Link** module.
2. Save
3. "noreferrer" and "noopener" are forced to two lines

### Setup/Environment

* ProcessWire version: 3.0.214 dev
* Page Edit Link: 1.1.2
* PHP version: 7.4.21
* MySQL version: 5.7.34

**Comment by Toutouwai** [comment] 2023-04-26 21:55
Dupe of fixed #1722 issue?

**Comment by ryancramerdesign** [comment] 2023-05-03 14:35
Closing since this was already fixed recently but please re-open if still experiencing it on the current dev branch version.

**Closed as completed by ryancramerdesign** 2023-05-03 14:35 UTC
