### ISSUE TITLE
Inputfield visibility dependencies not working with page reference field

### ISSUE THREAD

**Issue by mattgs** [processwire/processwire-issues#1010] opened 2019-10-24 13:56 UTC
### Short description of the issue

Trying to show/hide a field based on a page reference:

![screen](https://user-images.githubusercontent.com/563482/67491339-1080e500-f675-11e9-824b-de6e442f7ce6.jpg)

'categories' is a page reference field and needs to be identified by its id, referencing subfields like 'title' does not work (known issue according to docs).

### Expected behavior

Field should be visible if any of the ids are selected.

### Actual behavior

JS throws an error in \wire\templates-admin\scripts\inputfields.js in line 157.

Reason: 'value' is (correctly) identified as an integer, but code expects a string, using the indexOf method on 'value' without checking its type.

### Suggestion for a possible fix

Line 157: case '%=': if(String(value).indexOf(conditionValue) > -1) matched++; break;

Force cast 'value' to string makes the code and field configuration in the example work as expected. But I'm not sure if it introduces any unwanted issues, otherwise I would offer this as a solution.

### Setup/Environment

* ProcessWire version: 3.0.142
* Browser: Firefox 70

**Comment by ryancramerdesign** [comment] 2019-10-24 16:32
@mattgs The "%=" operator is a partial text matching operator and is not something to use with Page fields. You would need to change that to be just a "=" operator.

**Comment by mattgs** [comment] 2019-10-24 17:34
That's what we did at first, but that didn't work either. When using the '=' operator, the field is only shown when JUST any of the given ids are selected, but no other. If, according to the example, id 5189 (true) and, say, 7138 (false) are selected, the field is hidden. Just id 5189 or ids 5189 and 5190 work. Add any other id and the field is hidden.

**Comment by Toutouwai** [comment] 2019-10-24 22:33
> When using the '=' operator, the field is only shown when JUST any of the given ids are selected, but no other. If, according to the example, id 5189 (true) and, say, 7138 (false) are selected, the field is hidden. Just id 5189 or ids 5189 and 5190 work. Add any other id and the field is hidden.

When I tested using an AsmSelect inputfield it worked for me with the = operator. If I have a show-if condition like `my_field=2000|2001|2002` then the field appears if any of those pages are selected in the inputfield and it's not affected by other pages also being in the inputfield.

**Comment by ryancramerdesign** [comment] 2019-10-25 13:39
@mattgs See Toutouwai's response above where it was mentioned using an AsmSelect input with the Page field. If the '=' operator is not working in your case, perhaps it's specific to the input type being used for the Page field — what type of Inputfield are you using?

**Comment by mattgs** [comment] 2019-10-25 20:15
Good news is, I can confirm it works with an AsmSelect inputfield, thank you!

Bad news is, we're using a Page List Select Multiple inputfield, and we can't switch to an AsmSelect because we need to be able to drill down into the page tree.

**Comment by germankirichenko** [comment] 2019-11-03 09:43
I can confirm that the dependencies don't work with the PageReference field. I created a forum [topic](https://processwire.com/talk/topic/22298-field-page-reference-and-condition-required-if/?tab=comments#comment-191361) on this issue.

**Comment by ryancramerdesign** [comment] 2019-11-05 15:50
Thanks @mattgs @germankirichenko I've pushed a fix for this. It looks like InputfieldPageListSelectMultiple and InputfieldPageAutocomplete didn't previously support dependencies of this type, but I have added support in the referenced commit.

**Comment by mattgs** [comment] 2019-11-06 12:56
Can confirm it works as expected now. Thank you, Ryan, fantastic work as always!

**Comment by netcarver** [comment] 2019-11-06 15:38
@mattgs Hi Matthias, I'm closing this now. If you need it re-opening just post here again.

**Closed as completed by netcarver** 2019-11-06 15:38 UTC
Labels: status: fixed-please confirm
