### ISSUE TITLE
Error "Unable to create temp dir" on image upload

### ISSUE THREAD

**Issue by sekru1** [processwire/processwire-issues#342] opened 2017-08-11 15:58 UTC
### Short description of the issue

If I want to upload an image, following error occurs:
Unable to create temp dir: C:/http/my_project/site/assets/cache/WireTempDir/.PFM./L1-L2-L3-L4/

### Optional: Suggestion for a possible fix

If I use an old version of wire/core/PagefilesManager.php (3.0.56), it works!
There are sum slightly changes in this file.

### Setup/Environment

I'm on a windows machine!! (UniForm Server)

* ProcessWire version: 3.0.70
* PHP version: 7.1.0

**Comment by matjazpotocnik** [comment] 2017-08-11 17:39
Duplicate of https://github.com/processwire/processwire-issues/issues/338

**Comment by ryancramerdesign** [comment] 2017-08-16 13:37
@sekru1 assuming it's the same thing as #338 this issue was fixed last week and should be on 3.0.71. Please let me know if you continue to experience it in 3.0.71+.

**Closed** 2019-02-03 20:46 UTC
