### ISSUE TITLE
Required only if with required field action issue

### ISSUE THREAD

**Issue by PWaddict** [processwire/processwire-issues#582] opened 2018-04-30 23:55 UTC
### Short description of the issue

On my template's "Required field action" is set to Unpublish the page. I have a Page Table field inside that template with the condition "Required only if". So when a checkbox is checked the Page Table field is required.

The problem is that if the checkbox is unchecked so the Page Table isn't required when I save the page it gets unpublished with the error: "Session: Page unpublished because field "test_pagetable" is required" then I can publish the page again without issues then if I save the page again it gets unpublished with the above error and so on...

### Setup/Environment

* ProcessWire version: 3.0.98
* (Optional) PHP version: 7.0.18

**Comment by Toutouwai** [comment] 2018-05-01 03:58
This issue affects both the "Restore the previous value" and "Unpublish the page" actions in "Required field action" setting.

It looks like [this part](https://github.com/processwire/processwire/blob/8c18e3bf0d28b607d1790cae93493a3d55284754/wire/modules/Process/ProcessPageEdit/ProcessPageEdit.module#L1584-L1612) of ProcessPageEdit doesn't account for required-if conditions, and performs the actions whenever the "required" setting is applied to a field.

**Comment by PWaddict** [comment] 2018-05-01 04:33
I fixed it by replacing the 1585 line of ProcessPageEdit.module with this:

`&& $inputfield->getSetting('required') && !$inputfield->getSetting('requiredIf') && $inputfield->isEmpty()`

@ryancramerdesign please check the fix and include it on the next dev.

**Comment by Toutouwai** [comment] 2018-05-01 04:35
> I fixed it by replacing the 1585 line of ProcessPageEdit.module with this

That won't fix it because then the action won't trigger when the required-if condition evaluates true. The solution will have to involve the evaluation of required-if conditions.

**Comment by PWaddict** [comment] 2018-05-01 04:40
You're right.

**Comment by ryancramerdesign** [comment] 2018-05-01 09:50
Thanks for the report. I think I know where the issue is here. Can you try editing the /wire/modules/Inputfield/InputfieldForm.module and modifying something? Line 372 is currently this:
~~~~~
if(self::debug) $this->debugNote("$child->name - determined that value is not required");
~~~~~
Modify it by adding another line below it:
~~~~~
if(self::debug) $this->debugNote("$child->name - determined that value is not required");
$child->set('required', false); // add this line
~~~~~
What the above does is just updates the required state of the Inputfield when it's already been determined that it's not required due to evaluation of a requiredIf. That should enable ProcessPageEdit to see it.

**Comment by PWaddict** [comment] 2018-05-01 10:34
@ryancramerdesign Still same issue :(

**Comment by Toutouwai** [comment] 2018-05-01 11:43
@ryancramerdesign, your fix is working for me.

**Comment by PWaddict** [comment] 2018-05-01 12:13
@Toutouwai You can save the already published page without getting it unpublished?

**Comment by PWaddict** [comment] 2018-05-01 21:38
@ryancramerdesign @Toutouwai The above fix indeed it works BUT if I want to also use the show if on the same field with the required only if then it doesn't work.

**Comment by PWaddict** [comment] 2018-05-01 22:33
@ryancramerdesign I fixed the show if issue. After we added the above fix then on /wire/modules/Inputfield/InputfieldForm.module 272 line there is this:

`$child->set('showIfSkipped', true); // flag the field as skipped`

I added below it this:

`$child->set('required', false);`

**Comment by PWaddict** [comment] 2018-05-02 10:40
@ryancramerdesign Both are working properly. Thank you very much. Should I close the issue?

**Comment by ryancramerdesign** [comment] 2018-05-08 09:40
Great, thanks for testing. I will close this.

**Closed by ryancramerdesign** 2018-05-08 09:40 UTC
Labels: status: fixed (please confirm)

**Comment by PWaddict** [comment] 2018-07-07 20:44
@ryancramerdesign Having "Required field action" set to "Unpublish the page" and using a non-required repeater field with at least 1 empty required repeater item field the page is still getting saved instead of getting unpublished. Can you please fix it?

**Comment by PWaddict** [comment] 2018-07-08 11:50
@ryancramerdesign Now that I'm rethinking it, maybe isn't a bug cause the repeater field isn't required but I would like to hear your opinion about it.

**Comment by PWaddict** [comment] 2018-07-10 10:13
@ryancramerdesign The problem happens only when the page is already published. 

If the page is unpublished and having at least 1 empty required repeater item field the page cannot be published until either fill the empty required repeater item field or delete the repeater item which is perfect.

**Comment by PWaddict** [comment] 2018-07-10 13:08
@ryancramerdesign Until you fix it I'm gonna use the following hook as a temp fix:

```
$wire->addHookAfter("Pages::save", function(HookEvent $event) {

  $page = $event->arguments[0];
  if($page->template->name != 'my-template') return;

  $admin_page_name = wire("pages")->get(2)->name;
  $repeater_id = wire("fields")->get('my_repeater_field')->id;

  $empty_items = wire("pages")->find("template=repeater_my_repeater_field, my_text_field='', parent=/{$admin_page_name}/repeaters/for-field-{$repeater_id}/for-page-{$page->id}/, include=all");

  if(count($empty_items)) {

    if ($page->is(Page::statusUnpublished)) return;
    $this->session->error($this->_("Page unpublished because missing required value."));
    $page->of(false);
    $page->addStatus(Page::statusUnpublished);
    $page->save();
  }

});
```

**Comment by PWaddict** [comment] 2018-07-17 06:51
@ryancramerdesign Since this issue is close to make sure that you don't miss it I've created a new one https://github.com/processwire/processwire-issues/issues/639.
