### ISSUE TITLE
Unrecognized operator: !~=

### ISSUE THREAD

**Issue by snobjorn** [processwire/processwire-issues#1207] opened 2020-06-29 08:00 UTC
### Short description of the issue

After updating from ProcessWire 3.0.160 dev to 3.0.161 dev, the operator !~= does not work.

### Expected behavior

I have been using this operator with a pages find selector, to exclude text fields with a specific word (e.g. "word"):
$pages->find("template=blogpost, actiontext!~=word");

### Actual behavior

Should return all pages with template blogpost, except those with the "word" as part of the text field "actiontext".

### Steps to reproduce the issue

1. Update to ProcessWire 3.0.161 dev
2. Setup a page template with text field "actiontext"
3. Setup a template file with $pages->find("template=blogpost, actiontext!~=word");

### Setup/Environment

* ProcessWire version: 3.0.161 dev
* (Optional) PHP version: 7.3.6
* (Optional) MySQL version: 5.7.29-cll-lve (uncertain)

**Comment by noelboss** [comment] 2020-07-05 10:07
I have other issues with the latest version:
find using the array syntax does not work for example with the following query:

### New operators break using array syntax:

```
$results = $searchset->find([
   'title~*=‘ => $searchStr,
   ‘sort’ => '-modified|created’
]);
```

This is a simplified version of my query, the actual query I tried was more like this
```
$results = $searchset->find([
   'title~*=~=~|=~|*=~|%=‘ => $searchStr,
   ‘sort’ => '-modified|created’
]);
```

### New operator ~~= breaks
Also, this did result in an error even without the array syntax… But I couldn’t quite pinn it down, sometimes it worked, sometimes not… using a combination of only `~~=` or `~~=~*=~|=~|*=~|%=` or `~*=` to make it work/break again…

```
$results = $searchset->find('title|header~~=' . $searchStr . ', sort=-modified|created');
```

**Comment by ryancramerdesign** [comment] 2020-07-06 18:50
@snobjorn @noelboss Thanks for the report. The latest commit on the dev branch should fix all of these, except for the last one with `~~=` which I'm not able to duplicate. 

Also I'm not positive what `$searchset` means, but went forward assuming it was the `$pages` API var. If that's not what you meant, and `$searchset` is a PageArray or something, I just want to mention these new operators are mostly exclusive to database fulltext indexes, so they aren't really worthwhile elsewhere, and I don't know if they would even work (some may, some not). 

Also, you had a `sort=-modified|created` in one of the selectors above. There isn't this type of either/or option for sorting as far as I can remember, so I think the behavior may be undefined or the reverse of what you want. Likely that should be changed to AND behavior: `sort=-modified, sort=created`, unless I'm forgetting something. That might be related to the error you were seeing, but not sure, as I couldn't get an error either way.

**Comment by adrianbj** [comment] 2020-07-06 19:03
Sorry for lazily adding to this thread, but it's also no longer possible to do:

```
$pages->find('*');
```

It also returns the unrecognized operator error.

**Comment by ryancramerdesign** [comment] 2020-07-06 20:13
@adrianbj Was that working before as a side effect? I don't seem to remember that syntax being an option... but it also kind of looks like something I'd do, so you got me curious, wondering if I've forgotten.

**Comment by adrianbj** [comment] 2020-07-06 20:20
Yep, it definitely works on older versions - tested on 3.0.159 and it works fine. More importantly, this also used to work and doesn't now:
```
$fields->find('*')
```
I expect it might also be the same for template, roles, etc but haven't tested.

Not that it's a meaningful option, but it also used to work for:
```
$page->children('*');
```

**Comment by ryancramerdesign** [comment] 2020-07-06 20:24
Do you know is it documented anywhere? I can find yet any indication in the
code that it was supposed to work that way. So trying to figure out if it
was an intended behavior or if it was just working as a coincidence/side
effect. I'm assuming it just returned everything, like
foreach($fields->find('*')) would be the same as foreach($fields) or
foreach($page->children('*')) would be the same as foreach($page->children)
?

**Comment by adrianbj** [comment] 2020-07-06 20:35
I don't think it is documented anywhere so I think I picked it up from the forums at some point. Yes, the asterisk returns exactly the same as a normal `children()`

Here are some examples of using the `*` vs `getAll()` on other PW objects.

![image](https://user-images.githubusercontent.com/871211/86638798-c6365e80-bf8c-11ea-8da1-7bf3dcfed185.png)

![image](https://user-images.githubusercontent.com/871211/86639056-2af1b900-bf8d-11ea-9fa1-21920d569a98.png)

![image](https://user-images.githubusercontent.com/871211/86639109-41981000-bf8d-11ea-9398-95d771661154.png)

![image](https://user-images.githubusercontent.com/871211/86639182-5d031b00-bf8d-11ea-9dab-8e1721bc5457.png)

**Comment by raymondgeerts** [comment] 2020-07-06 21:53
I just upgraded PW on my local machine to PW 3.0.161 latest dev branche with commit [5b285eb](https://github.com/processwire/processwire/commit/5b285ebc8c86b3782f5e6100b11db59150104dda)

The following WireException is thrown:
Operator '!~=' is not implemented in FieldtypeCroppableImage3

CroppableImage3 is up to date with version 1.2.0

**Comment by ryancramerdesign** [comment] 2020-07-07 11:31
@adrianbj Thanks for the info. Since I can't find code that seems to suggest this was an intended behavior, it looks to me like it was most likely working as an unintended side effect before, as a result of the way the selectors were parsed. Probably someone noticed it worked in the forums at some point, and since PW supports wire('*')` to refer to 'all API variables', it probably seemed like valid syntax elsewhere, even if it wasn't intended. I guess the question is whether PW should support that, and if so, whether with things like pages it also means "include=all", etc.

**Comment by ryancramerdesign** [comment] 2020-07-07 11:40
@Rayden Thanks, any idea what API call that error originates with? I'd assume the FieldtypeCroppableImage3 doesn't support that particular operator (valid error), but I'm also guessing you weren't seeing the error before, and maybe it's receiving that operator when it's not supposed to. If you can tell me how to duplicate I should be able to determine what the issue is and hopefully fix it.

**Comment by matjazpotocnik** [comment] 2020-07-07 12:25
> I guess the question is whether PW should support that, and if so, whether with things like pages it also means "include=all", etc.

IMHO it would be good if PW keeps supporting this because if it's not, then that would be a breaking change (even if unintentional and undocumented)

**Comment by adrianbj** [comment] 2020-07-07 13:59
> I guess the question is whether PW should support that, and if so, whether with things like pages it also means "include=all", etc.

Well the current implementation doesn't mean "include=all" so I guess it's probably best to stick with that.

Note that this is also the case for `$pages->find('*')` as well as `$page->find('*')`

**Comment by raymondgeerts** [comment] 2020-07-07 15:07
> @Rayden Thanks, any idea what API call that error originates with? I'd assume the FieldtypeCroppableImage3 doesn't support that particular operator (valid error), but I'm also guessing you weren't seeing the error before, and maybe it's receiving that operator when it's not supposed to. If you can tell me how to duplicate I should be able to determine what the issue is and hopefully fix it.

Indeed, the error did not occur before upgrading to PW 3.0.161. The previous version that was running was PW 3.0.148 
As far as I can pinpoint, it came down to the following selector. Hope that helps a bit, else let me know if I have to dig a bit deeper. It is a composition of several other selector results which gathers repeater matrix and repeater pages, of which it checks if a checkbox for the regarding image field is checked. The regarding checkbox is assigned to the image field using the template method, in this case, the field name is `images_video`, so the template containing the checkbox is named `field-images_video`. The name of the checkbox field is `checkbox`

`( template=repeater_repeater_matrix_content, parent.name=for-page-257233|for-page-257225|for-page-256981|for-page-256836|for-page-256564|for-page-256441|for-page-255256|for-page-254767|for-page-254996|for-page-255045|for-page-253587|for-page-251560|for-page-195517|for-page-205985|for-page-208207|for-page-250347|for-page-250156|for-page-249255|for-page-248484|for-page-248310, images_video.count>0, images_video.checkbox!=1 ), ( template=repeater_repeater_matrix_content, parent.name=for-page-251178|for-page-246171|for-page-186424|for-page-37482|for-page-37434, images_video.count>0, images_video.checkbox!=1 ), ( template=repeater_repeater_videos, parent.name=for-page-256988|for-page-256985|for-page-256449|for-page-255392|for-page-255223|for-page-255161|for-page-255049|for-page-251568|for-page-250355|for-page-250158|for-page-249259|for-page-248488|for-page-248314|for-page-208211|for-page-205999|for-page-195529|for-page-195540, images_video.checkbox!=1 ), ( template=repeater_repeater_videos, parent.name=for-page-38630|for-page-38546, images_video.checkbox!=1 ), sort=-published, status!=unpublished, limit=20`

**Comment by ryancramerdesign** [comment] 2020-07-09 15:09
@Rayden I don't currently have a setup and selector to rival yours and duplicate this issue, but since it looks like images_video.checkbox is an encoded subfield of a FieldtypeFile/FieldtypeImage field, I have an idea where the issue could be and have attempted a fix in the latest commit. When you get a chance, can you check to see if that fixes it, and confirm that it's still matching correctly as you expect? Thanks.

**Comment by raymondgeerts** [comment] 2020-07-10 07:34
@ryancramerdesign - I have implemented the commit 'Attempt fix for issue...' (f787912), But now it gives me another error:

![Screen Shot 2020-07-10 at 09 21 27](https://user-images.githubusercontent.com/364556/87128325-b752f300-c28f-11ea-936f-fb8062727124.png)

```
FILE: wire/modules/Fieldtype/FieldtypeFile.module
LINE: 843
$operator // !~=
$originalOperator // !=
```

```
FILE: wire/core/Selectors.php
LINE: 1311
$className // ProcessWire\
```

It looks like the opperator !~= is not in Selectors $selectorTypes

```
FILE: wire/core/Selectors.php
LINE: 1296
$operator // !~=
$typeName // null
```
If it helps, i'm happy to send the regarding database.

**Comment by raymondgeerts** [comment] 2020-07-15 10:41
The 3.0.162 upgrade seems to fix the issue on my side.

Not seeing any "Unrecognized operator: !~= #1207" errors or any related errors anymore. 

Thanks for fixing it.

**Comment by ryancramerdesign** [comment] 2020-07-23 17:04
Thanks for testing @Rayden. Since it sounds like all is working now, I'll go ahead and close this one.

**Closed as completed by ryancramerdesign** 2020-07-23 17:04 UTC
Labels: status: fixed-please confirm
