### ISSUE TITLE
WireArray::not() gives unexpected result with multiple selectors

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#383] opened 2017-09-23 02:21 UTC
### Short description of the issue

WireArray::not() does not behave as expected when multiple selectors are included in the selector string.

The expected behaviour is that for any $wirearray and $selector, $wirearray->find($selector) plus $wirearray->not($selector) will equal $wirearray. In other words, not($selector) matches all items not matched by find($selector).

But this isn't the case, as demonstrated below for a PageArray $vehicles consisting of three pages titled "red car", "blue car", "green truck".

````php
$matches = $vehicles->find("title~=car"); // "red car", "blue car"
$not_matches = $vehicles->not("title~=car"); // "green truck"
// So far, so good

// But for multiple selectors...
$matches = $vehicles->find("title~=car, !title~=red"); // "blue car"
$not_matches = $vehicles->not("title~=car, !title~=red"); // expected "red car", "green truck" but got unexpected empty PageArray
````
Related forum thread: https://processwire.com/talk/topic/17113-wirearray-filterdata-selector/

### Setup/Environment

* ProcessWire version: 3.0.75

**Comment by ryancramerdesign** [comment] 2017-12-08 14:01
I think the logic here is actually correct, but when we get into double NOTs like in your second two examples, that's where it can be more difficult to spot, so we kind of have to logic it out step by step. Here's what I'm getting at least, when I try to logic out the following selector: 

~~~~
$vehicles->not("title~=car, !title~=red");
~~~~
You said that you expected "red car" and "green truck". However, you can't expect "red car" because you are asking for items that do NOT have "car" in the title, so that excludes "red car" (and any items with "car" in the title). 

Now for "green truck", the selector can't match that because you are asking for `not("!title~=red")` which is a double NOT. NOT false is true, so that part of the selector is asking for items that HAVE "red" in the title. There's aren't any, because you ALSO asked for items that do NOT have "car" in the title, so there can be no "red car". Now if there was a "red truck", that would match! :)

- NOT `title~=car` leaves just "green truck" in the PageArray. 
- NOT `!title~=red` is a DOUBLE NOT (!false===true), which which means must now match "red" in the title. Since there is only "green truck" left in the PageArray, there's nothing to match.

Given the above, should it not return a blank PageArray? It seems to me like it should. But again, the logic is a little tricky so let me know if I'm missing something.

**Comment by Toutouwai** [comment] 2017-12-08 22:06
> You said that you expected "red car" and "green truck". However, you can't expect "red car" because you are asking for items that do NOT have "car" in the title, so that excludes "red car" (and any items with "car" in the title).

This comes down to the order of operations. We are coming from two different expectations of what the order should be.

Every comma in the selector represents an AND operator, so the example selector could be expressed as

`title contains the word 'car' AND title does not contain the word 'red'`

I expect the not() method to negate the result of this selector...

`not(title contains the word 'car' AND title does not contain the word 'red')`

...so to match any vehicles where that selector statement is not true. So the whole selector statement is evaluated _first_ and then negated.

But I think you are saying the order of operations is...

`not(title contains the word 'car') AND not(title does not contain the word 'red')`

...which is not unreasonable, but I think is unexpected. Perhaps due the brackets around the selector, which I know is just how a method is called in PHP but in mathematics implies that the contents of the brackets is operated on before operations outside the brackets.

**Comment by dscone** [comment] 2018-02-23 17:56
Just replying to this to see where it will land moving forward.

I would agree with Toutouwai's statement that the current behavior is "not unreasonable, but I think is unexpected".  I would have expected the entire selector (made up of potentially many different fields and operators) to be evaluated and then negated also.

Without the proposed functionality (i.e my expected functionality), there are several search/filter/find scenarios that are difficult (impossible?) to achieve.

thanks for all your work.

**Comment by ryancramerdesign** [comment] 2019-04-05 16:08
@Toutouwai I still don't understand the logic you are suggesting here, but I'm a product of the US education system so there's a good chance it's just beyond me. While I don't understand, I know you well enough to know that you are very likely right about it (plus @dscone seems to agree), so I've gone ahead and implemented a WireArray::notAll() method that attempts to accommodate the logic you are asking for. However, since I don't understand the purpose of this, I've only coded it to mirror the results you've outlined here — it'll need further testing to make sure it's working in other situations. Please let me know what you find. Thanks. Here's how I'm testing it:
~~~~~
echo WireArray([
  WireData(['title' => 'red car']),
  WireData(['title' => 'blue car']),
  WireData(['title' => 'green truck'])
])->notAll('title~=car, !title~=red')->implode(', ', 'title');
~~~~~
The above outputs "red car, green truck". 

Please let me know if the "not all" terminology is incorrect or if this method should have a different name to point to the logic its using? I've tagged it as `#pw-internal` so it's not part of the public API just yet.

**Comment by Toutouwai** [comment] 2019-04-05 23:00
Thanks for the update @ryancramerdesign. Introducing a new method is okay, but I still think that the existing not() method does not do what the documentation says: **Filter this WireArray to only include items that DO NOT match the selector (destructive)**.

So I don't think anyone will be expecting the current behaviour of not(). My preference would be to change the behaviour of not() to match the documentation and then a notAll() method wouldn't be needed. But I might be wrong about what people interpret the documentation statement above to mean, so maybe some of the regular commenters here could weigh in: @adrianbj, @netcarver, @teppokoivula, @szabeszg, @matjazpotocnik, or anyone else reading this.

I'll try and restate my interpretation of the documentation in hopefully clearer terms. Originally I was using find() as the counterpart but actually filter() is more correct... 

WireArray::not($selector) is the opposite of WireArray::filter($selector). Documentation: **Filter this WireArray to only include items that match the given selector (destructive)**.  

So regardless of what $selector is, $wirearray->not($selector) should consist of all items in the WireArray that would not be contained in $wirearray->filter($selector).

**Comment by szabeszg** [comment] 2019-04-06 17:13
I still have the same understanding what Robin has: https://processwire.com/api/ref/wire-array/not/

Mathematically speaking this is the complete set we have: _"red car", "blue car", "green truck"_

So just looking at this: `not("title~=car, !title~=red")`
I would first evaluate _"title~=car, !title~=red"_ which results in a set what `find("title~=car, !title~=red")` delivers. After this, negating this set should result in a set with _"green truck"_ only in it, at least this is how I interpret it.

Merging the two sets should result in getting the whole set back, and the docs suggests the same:

> Filter this WireArray to only include items that DO NOT match the selector

where this is the selector: _"title~=car, !title~=red"_

**Comment by adrianbj** [comment] 2019-04-06 17:16
Even though this NOT stuff can be a little brain twisting at times, I agree with @Toutouwai and @szabeszg 's analysis. I also don't think an additional `notAll()` is a good idea. I think the existing `not()` should perform as they describe. That said, I do worry that this might be a breaking change for some users.

**Comment by ryancramerdesign** [comment] 2019-04-06 18:26
Hey guys, I was politely trying to say in the last message that I'm trying to accommodate what you are looking for but this is just not the way this method is designed to work. See my first reply here for the intended logic of this method. I'm willing to add a method (or argument) to support the usage that Toutouwai is looking for here, but I'm not going to break the intended behavior of the existing method to accommodate it. Nor do I want to break every instance others and myself have used the method in the last [almost] decade. I personally have no use for the notAll() behavior being requested here, but I also want to accommodate your interest and need. I'm not going to break the existing method to do it, but I'm happy to add another method to do it. If you guys don't think another method would be worthwhile then let's close this.

**Comment by matjazpotocnik** [comment] 2019-04-06 19:05
We all know De Morgan's laws: `not (A and B) = not A or not B`. So Robin's (and others) expectations are very reasonable, especially when you read the documentation. But I have to agree with Ryan that modifying not() would be a breaking change. So, I would leave not() as is and change the documentation, maybe even linking ti this thread. I would also leave notAll() since we already have it, and mention this in the documentation, probably along with not().

**Comment by Toutouwai** [comment] 2019-04-06 21:03
> Hey guys, I was politely trying to say in the last message that I'm trying to accommodate what you are looking for but this is just not the way this method is designed to work.

I appreciate politeness of course but in this case what you were trying to say didn't come through to me. It sounded very much like you couldn't understand the description of the issue and that because of this the new method only covers a narrow treatment of $selector based on the original example I gave. Hence I started to question if I was the odd man out in what I thought was a straightforward reading of the documentation. And I tried to restate the issue because what I'm trying to get across is a general point about what "items that do not match the selector" would normally be interpreted to mean, and this has nothing to do with specific cases of whatever is in $wirearray and $selector.

I'm happy to have both methods to avoid a breaking change but there will need to be a clear description of how they differ. The current description for notAll() – "Like the not() method but $selector evaluated as if it had (brackets) around it" – isn't clear IMO. I think notAll() should get the description currently used for not(), and not() should explain that the selector string is broken down into components and each component is individually negated. The fact that PW breaks down selectors strings into component selectors might be known to people who have delved into the core code but I doubt that the average user knows this. And so it should be explained for methods that have non-intuitive results because of it.

**Closed** 2019-04-06 21:19 UTC
Labels: status: discussion, type: filtering

**Comment by ryancramerdesign** [comment] 2019-04-08 19:01
ProcessWire's API is based upon jQuery's API rather than somebody's math laws or math syntax. So I think maybe we've been looking at this through different lenses? The not() function works the same as it does in jQuery and produces the same results. 
~~~~~
// jQuery
$notCars = $cars.not('[title~=car], :not([title~=red])');
// PW
$notCars = $cars->not('title~=car, !title~=red');
~~~~~
I'm still confused what you say about the function description not being accurate. To me it says exactly what it does. But since PW and jQuery work the same here I took a look at their not() description, which is this: 

> Remove elements from the set of matched elements.

That's a bit too ambiguous for me, but is that more in the direction you are looking for with the description? Can you suggest a description for PW's not() and notAll() that you think would clarify the behavior for your understanding of them? Thanks.

**Comment by Toutouwai** [comment] 2019-04-08 22:48
> ProcessWire's API is based upon jQuery's API rather than somebody's math laws or math syntax.

I shouldn't have introduced the maths discussion because it just confused things and isn't really that connected to what I'm getting at. The issue isn't some arcane maths thing but just about how I think a general audience understands selectors and what _not matching_ a selector is understood to mean.

The original example I gave is probably not ideal because one of the "clauses" (if that's the right word) within the string it is negated, so negating the whole selector becomes more complicated than is necessary in order to make the point. The original forum topic that lead to this issue report dealt with a selector containing greater than and less than conditions for a datetime field. In the example below I've simplified that to an integer field in the "colour" template. There are 7 colour pages, with integer values 1 - 7. WireArray::filter works as expected given the documented description "Filter this WireArray to only include items that match the given selector".

![2019-04-09_101045](https://user-images.githubusercontent.com/1538852/55760375-feac6b80-5aaf-11e9-8fc7-bfffb3ced1d8.png)

But when not() is substituted for filter() I think a general audience understands that "Filter this WireArray to only include items that DO NOT match the selector" will consist of all the items in the WireArray that would not be matched (and in given the previous filter example _were not matched_) by the selector. But instead there are no matches:

![2019-04-09_101848](https://user-images.githubusercontent.com/1538852/55760669-e38e2b80-5ab0-11e9-81e3-9a57e8c4fc3c.png)

It's interesting the point you make about jQuery and the original example. But isn't it an important difference that in PW selectors each clause is connected with AND logic whereas in jQuery it is OR logic? So if there is a selector string like "[clause 1], [clause 2], [clause 3]" then in PW all the clauses need to match but in jQuery just one of the clauses needs to match. So wouldn't this have an impact on what it means to negate the whole selector string with a not() method?

It's also interesting that you find the existing behaviour more useful rather than what's been introduced with notAll(). So far I've used not() rarely if ever, but if I imagine a situation where I have some WireArray and I don't know what's in it but I do know what I _don't want to keep_ (namely some items that match $selector) then I would want not($selector) to keep all the items that wouldn't be kept by filter($selector).

I don't really have a better idea for documenting not() and notAll() besides what I suggested before. To my way of thinking the existing description for not() better describes notAll(), and the not() documentation seems like it needs to get into an explanation how individual selector clauses/components within the string are separated out and negated individually. So it does something that might be expected by someone who knows the inner workings of PW selectors but is not immediately intuitive to the average user. Not sure how best to make that clear.

**Comment by Toutouwai** [comment] 2019-04-09 02:32
I tested jQuery not() with a similar setup to my example above and got my expected result. A function needs to be used because jQuery can't evaluate less than and greater than within the selector itself.

filter():
```html
<div class="text">
    <p data-int="1">1</p>
    <p data-int="2">2</p>
    <p data-int="3">3</p>
    <p data-int="4">4</p>
    <p data-int="5">5</p>
    <p data-int="6">6</p>
    <p data-int="7">7</p>
</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script>
    $(function() {
        var $items = $('.text p');
        var $result = $items.filter(function() {
            return $(this).data('int') > 2 && $(this).data('int') < 6;
        });
        $result.each(function() {
            console.log("int: " + $(this).data('int'));
        });
    });
</script>
```
![2019-04-09_142945](https://user-images.githubusercontent.com/1538852/55769188-efd7b000-5ad3-11e9-9172-1c4b624dcb3e.png)

not():
```html
<div class="text">
    <p data-int="1">1</p>
    <p data-int="2">2</p>
    <p data-int="3">3</p>
    <p data-int="4">4</p>
    <p data-int="5">5</p>
    <p data-int="6">6</p>
    <p data-int="7">7</p>
</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script>
    $(function() {
        var $items = $('.text p');
        var $result = $items.not(function() {
            return $(this).data('int') > 2 && $(this).data('int') < 6;
        });
        $result.each(function() {
            console.log("int: " + $(this).data('int'));
        });
    });
</script>
```
![2019-04-09_143113](https://user-images.githubusercontent.com/1538852/55769250-257c9900-5ad4-11e9-9708-23f0336679d5.png)
