### ISSUE TITLE
Page::index() gives unexpected result for hidden and unpublished pages

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#751] opened 2018-11-20 23:21 UTC
### Short description of the issue

Page::index() is supposed to return the position of a page relative to its siblings. But it gives an unexpected result if the page is hidden or unpublished.

Visible/published page:

![2018-11-21_121630](https://user-images.githubusercontent.com/1538852/48808962-9589bd00-ed87-11e8-81b3-a00e74c3ea84.png)

Hidden page (same applies for unpublished page):

![2018-11-21_121732](https://user-images.githubusercontent.com/1538852/48808980-a1757f00-ed87-11e8-8aec-5cbdf91185cc.png)

A hidden or unpublished page retains its position in the page list, so I expected those statuses not to affect its index.

### Setup/Environment

* ProcessWire version: 3.0.119

**Comment by kixe** [comment] 2018-11-29 10:33
Furthermore you will get an empty PageArray instead of expected (int) 0 calling
`$pages->get(1)->index();`

**Possible Fix for PageTraversal::index() including**
```
/**
 * get the current index related to siblings defined by selector
 * return null if the item is excluded (due to specified selector)
 * @param object $page
 * @param string $selector
 * @return int/ null
 *
 */
public function index(Page $page, $selector = '') {
	if (strpos($selector, 'sort=') === false) $selector = "sort=sort," . trim($selector,',');
	if (strpos($selector, 'include=') === false) $selector = trim($selector,',') . ",include=all";
	$siblings = $page->siblings($selector);
	return $siblings->getItemKey($page);
}
```

**Comment by ryancramerdesign** [comment] 2018-12-06 19:08
Thanks, I've pushed a fix for this isssue (and the one kixe mentioned as well). The issue is that by default a hidden or unpublished page has no index number among its siblings, so it's not matching anything and simply counting the total number of siblings. It should instead return some kind of error index number, so I've set it to return -1 for this case. You can also now call $page->index(true); and it'll return the index in a manner that includes hidden and unpublished pages.

**Comment by kixe** [comment] 2018-12-07 08:44
Thanks for the fix. I am getting still unexpected results using the following code (note: there is one page under the siblings with status 'unpublished' AND 'hidden')

```
$siblings = $pages->get(2)->siblings('include=all,sort=sort');
$return = [];
foreach($siblings as $sibling) {
	$return[$sibling->id] = array(
		'status' => $sibling->status,
		'sort' => $sibling->sort,
		'index' => $sibling->index(),
		'index_all' => $sibling->index(true),
		'index_hidden' => $sibling->index('include=hidden,sort=sort'),
	);
}
var_dump($return);exit();
```

result
```
array(8) {
  [11973]=>
  array(5) {
    ["status"]=>int(1)
    ["sort"]=>int(5)
    ["index"]=>int(0)
    ["index_all"]=>int(0)
    ["index_hidden"]=>int(0)
  }
  [12334]=>
  array(5) {
    ["status"]=>int(1)
    ["sort"]=>int(7)
    ["index"]=>int(1)
    ["index_all"]=>int(1)
    ["index_hidden"]=>int(1)
  }
  [1095]=>
  array(5) {
    ["status"]=>int(1033)
    ["sort"]=>int(8)
    ["index"]=>int(-1)
    ["index_all"]=>int(2)
    ["index_hidden"]=>int(2)
  }
  [3357]=>
  array(5) {
    ["status"]=>int(1025)
    ["sort"]=>int(9)
    ["index"]=>int(-1)
    ["index_all"]=>int(3)
    ["index_hidden"]=>int(3)
  }
  [3337]=>
  array(5) {
    ["status"]=>int(3077)
    ["sort"]=>int(10)
    ["index"]=>int(-1)
    ["index_all"]=>int(4)
    ["index_hidden"]=>int(7) // expected -1 since this page is unpublished
  }
  [27]=>
  array(5) {
    ["status"]=>int(1035)
    ["sort"]=>int(11)
    ["index"]=>int(-1)
    ["index_all"]=>int(5)
    ["index_hidden"]=>int(4)
  }
  [2]=>
  array(5) {
    ["status"]=>int(1035)
    ["sort"]=>int(12)
    ["index"]=>int(-1)
    ["index_all"]=>int(6)
    ["index_hidden"]=>int(5)
  }
  [7]=>
  array(5) {
    ["status"]=>int(1039)
    ["sort"]=>int(13)
    ["index"]=>int(-1)
    ["index_all"]=>int(7)
    ["index_hidden"]=>int(6)
  }
}
*/

```

I am not convinced using **PageTraversal::_next()** to get the index. I prefer **PageArray::getItemKey()**

The following function returns what I expect:

```
/**
 * get the current index related to siblings defined by selector
 * return -1 if the item is excluded (due to specified selector)
 * @param object $page
 * @param bool/string $selector or true
 * @return int
 *
 */
public function index(Page $page, $selector = '') {
	if (!$selector && $page->status >=1024) return -1;
	if ($selector === true) $selector = 'sort=sort,include=all';
	if (strpos($selector, 'sort=') === false) $selector = "sort=sort," . trim($selector,',');
	if (strpos($selector, 'include=') === false) $selector = trim($selector,',') . ",include=all";
	$siblings = $page->siblings($selector);
	$return = $siblings->getItemKey($page);
	return $return === null? -1 : $return;
}
```

**Comment by ryancramerdesign** [comment] 2018-12-07 15:11
Thanks @kixe I've pushed an update that should fix that, though also changed my mind about the "-1" return values, deciding they weren't that useful, because all they do is reveal the page is hidden/unpublished, which is something one can already tell. Instead I changed it so that it returns the index as it would be if the individual page being checked were not hidden/unpublished, so that the return value at least still provides some point of reference.

In working with index() I also noticed that $page->next(), $page->prev() and related calls were also not useful when called on hidden or unpublished pages. So they've been updated in a similar manner, via some enhancements to the PageFinder class.

Regarding use of PageArray::getItemKey(), that wouldn't be scalable here. The primary benefit of the current Page::index() (and all the Page::traversal methods) is that they can function at any scale. If there are a million siblings, they can still do their job. Whereas a PageArray could not, because it represents pages in memory, and there's a limit to how many pages can be loaded in memory, and a limit to how much time one is willing to wait for them to load. :)

**Comment by kixe** [comment] 2018-12-07 18:17
Using no argument or bool true is working fine. Regarding to any other selector I get really strange results. I tried the following with my loop test function, mentioned above.

- 'status<1025'
- 'sort=sort'
- 'include=unpublished'

I would vote for removing the option to use a string selector argument as filter and only provide the bool true for now.
Apart from this its fine now.

**Comment by netcarver** [comment] 2019-03-22 12:46
@ryancramerdesign Bumping this for your further consideration.

**Comment by ryancramerdesign** [comment] 2019-03-22 16:18
@netcarver @kixe as far as I can tell it is working correctly with selectors. I tried the 3 mentioned selectors above in several different scenarios and received the correct index results with all of them.

**Comment by netcarver** [comment] 2019-03-22 16:51
Ok, @kixe Christoph, I'm closing this one now. Feel free to post more if ever needed.

**Closed by netcarver** 2019-03-22 16:51 UTC
Labels: status: work in progress
