### ISSUE TITLE
Custom fields for files/images – does not save in repeater context

### ISSUE THREAD

**Issue by gerritvanaaken** [processwire/processwire-issues#1070] opened 2020-01-23 10:26 UTC
### Short description of the issue

"Custom fields for files/images" (introduced to the core in 3.0.142) does not work properly in Repeater/RepeaterMatrix context. Saving image metadata failes when repeater item was freshly created.

### Expected behavior

- The image custom field data should be saved correctly in the database and be availiable in backend and frontend.

### Actual behavior

- The image custom data does not get saved, when the repeater item was freshly created. 
- If I perform a page save first, then fill in the image custom data, do page save again, then all gets saved.

### Steps to reproduce the issue

1. create a new repeater item (which has an image field with custom fields).
2. upload an image, click on that image, fill in some custom fields with data
3. Save the page

Image custom data is not being saved.

### Setup/Environment

* ProcessWire version: 3.0.149
* (Optional) PHP version: 7.3
* (Optional) Any 3rd party modules that are installed and could be related to the issue: none, using "default" blog install profile.

**Comment by gerritvanaaken** [comment] 2020-01-23 11:07
Maybe this little investigation helps. In the page save POST request, there is this key/value on the first page save:

image_caption_image_7ed6d74910ce4d58c4339975f55a1002: testcaption
(Which has no effect on the database "field_image" table)

On the second page save its:

image_caption_image_repeater10736_7ed6d74910ce4d58c4339975f55a1002: testcaption
(database "filedata" is being filled with the correct data)

**Comment by gerritvanaaken** [comment] 2020-02-08 22:15
This is a rough solution: https://github.com/processwire/processwire/pull/159

**Comment by alexcapes** [comment] 2020-05-21 20:43
I've also experienced this same issue with data not being saved when custom image fields are used in a PageTable field context.

**Comment by vieregg-jfc** [comment] 2020-06-05 10:07
Same Problem here... Would be nice to see a fix for this bug!

**Comment by mpsn** [comment] 2021-06-08 16:43
Reproduced the Bug in 3.0.165 and 3.0.172. Would also love to see a fix!

**Comment by ryancramerdesign** [comment] 2022-04-28 11:56
Closing this issue because it was previously fixed. I did just double check to make sure. Though please let me know if still experiencing any issues related to this.

**Closed as completed by ryancramerdesign** 2022-04-28 11:56 UTC
Labels: status: multiple
