### ISSUE TITLE
Open parent tree for last item in admin breadcrumb

### ISSUE THREAD

**Issue by sekru1** [processwire/processwire-issues#212] opened 2017-03-13 14:47 UTC
### Short description of the issue

If I edit a page and want to go to the nearest parent with the help of the breadcrumb in the admin view, the page tree is not opened at this position.

### Links that demonstrate the issue

You can test it in the ProcessWire Demo:
http://demo.processwire.com/regular/processwire/page/edit/?id=1018
(User: bloguser, Password: processwire3)
If you click on "Categories" in the breadcrumb, they are not opened.

The link must be "page/?open=1016", but there is not "?open".

### Suggestion for a possible fix
The problem is in this file: ProcessPageEdit.module
I marked the line. If you delete the line, the problem is solved.
```
	/**
	 * Setup the breadcrumbs used in the UI
	 *
	 */
	public function setupBreadcrumbs() {
		if($this->wire('input')->urlSegment1) return;
		if($this->wire('page')->process != $this->className()) return;
		$this->wire('breadcrumbs')->shift(); // shift off the 'Admin' breadcrumb
		if($this->page && $this->page->id != 1) $this->wire('breadcrumbs')->shift(); // shift off the 'Pages' breadcrumb
		$page = $this->page ? $this->page : $this->parent;
		if($this->masterPage) $page = $this->masterPage;

		$numParents = $page->parents->count();
		foreach($page->parents() as $cnt => $p) {
			$url = "../?open=$p->id";
			// if($cnt == $numParents-1) $url = "../"; ################################
			$this->breadcrumb($url, $p->get("title|name"));
		}

		if($this->page && $this->field) $this->breadcrumb("./?id={$this->page->id}", $page->get("title|name"));
	}


```
### Setup/Environment
3.0.55

**Comment by ryancramerdesign** [comment] 2017-03-14 18:55
Hi @sekru1 this is a duplicate of #22 . The behavior is intended so that the nav item goes to the last position in the tree (which is usually where you left it before clicking edit). Since that tree is already cached, it can load it very quickly relative to links using the "?open=...". However the compromise is that if you go to edit the page via direct link, that info won't be cached in the tree used by that particular breadcrumb link.

**Closed by ryancramerdesign** 2017-03-14 18:55 UTC
