### ISSUE TITLE
Finding users - possible access inconsistencies

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-issues#1552] opened 2022-03-30 14:06 UTC
### Short description of the issue

I am not sure if the behavior I am seeing is a bug or expected, but the screenshots will clarify.

### Expected behavior

I am not actually certain, but I think my main surprise is how `$pages->findOne('id=2261')` (as NON superuser) doesn't return the user, but `$pages->findOne(2261)` does return it. I assumed the `check_access` would be required whenever using `$pages` instead of `$users`. 

I am also a little surprised about the difference where `$users->get(13160)` returns the trashed user, but `$users->get('id=13160')` doesn't.

Note that I often end up using `$pages` with `check_access` for a couple of reasons. The main one is to avoid returning trashed users (but maybe that's not necessary if I remember to always add the `id=` to the `$users->get`. The other reasons is to use `findMany()`, although that's not really relevant to this discussion.

### Actual behavior

See the screenshots below. Note that there are 4 runs in total, two as a superuser and 2 as a non-superuser. And within those, one is a published user and the other is a trashed user.

### Optional: Screenshots/Links that demonstrate the issue

**RUN AS A SUPERUSER**

**Trashed User**

![image](https://user-images.githubusercontent.com/871211/160850317-616faa37-d4d5-4e33-ac7a-09a5bc519fab.png)

**Published User**

![image](https://user-images.githubusercontent.com/871211/160850797-af45adb8-b726-44d0-90fe-4cc8ea71d956.png)

**RUN AS A NON SUPERUSER**

**Trashed User**

![image](https://user-images.githubusercontent.com/871211/160851273-15d987b4-eace-4c5e-a61d-480ed33746ec.png)

**Published User**

![image](https://user-images.githubusercontent.com/871211/160851127-c954cc17-811d-42a8-b0ad-f874e951ba18.png)

**Comment by adrianbj** [comment] 2022-04-12 14:59
Also, finding this very confusing - why is this returning a user at all:

![image](https://user-images.githubusercontent.com/871211/162992182-84aef6e9-54bc-4ea4-a46a-4e3783fd891f.png)

**Comment by adrianbj** [comment] 2022-04-12 17:41
And what about this returning an empty string:

![image](https://user-images.githubusercontent.com/871211/163021767-654421c8-f454-4571-8afc-6e13d342a26e.png)

At least this version returns a `NullPage`:

![image](https://user-images.githubusercontent.com/871211/163021986-08a068c8-fbc5-42bc-b6c0-3f111bddd9a0.png)

**Comment by ryancramerdesign** [comment] 2022-04-15 12:05
@adrianbj Thanks for the testing and reports. I'm thinking your pages.findOne() is working in a couple of the cases where you don't expect because maybe you have view access enabled for the corresponding user template to non-superusers? I mention that because I can't duplicate that one here. Can you confirm this is the case, that this is how you've confirmed your permissions?

Regarding trashed users: users aren't supposed to be in the trash. In your case, I'm thinking you've got alternate parents/templates for users and your trashed users must come from that set. You may want to edit your alternate user template in advanced mode and on the System tab check the box to disable trash for that. Though sounds like this is something the core could ideally apply automatically, without you having to manually configure it. Or, if you find it useful to have users in the trash, we could update the users.get() method to not support loading them when you give it an integer id. 

> Also, finding this very confusing - why is this returning a user at all:

Null is an invalid argument for users.get(). It's being cast to a valid argument, in this case a blank Selector object. A blank selector object can match everything, so you are just getting the first match from an "everything" match. It would be preferable for this invalid argument to return a NullPage instead, I will add a check for that null argument so that it returns null or NullPage rather than blank.

> And what about this returning an empty string:

Looks like this is a bug, in cases where there can be multiple parents/templates for users. The blank string is an empty placeholder for a user that is never found, and it should be returned null or NullPage instead. I will push a fix for this.

**Comment by matjazpotocnik** [comment] 2022-05-07 16:57
@adrianbj, could you verify Ryan's fix please and close this issue?

**Comment by adrianbj** [comment] 2022-05-07 17:37
Thanks for taking a look @ryancramerdesign 

> I'm thinking your pages.findOne() is working in a couple of the cases where you don't expect because maybe you have view access enabled for the corresponding user template to non-superusers?

I don't think I have any special permissions in this case - when I look at the Access tab for the user template, I see this, but in the table of checkboxes below, nothing is checked.
![image](https://user-images.githubusercontent.com/871211/167265286-c9fb7e3c-87c3-48b6-bd17-a4825292e93d.png)

> Regarding trashed users: users aren't supposed to be in the trash. In your case, I'm thinking you've got alternate parents/templates for users and your trashed users must come from that set.

I am not talking about alternate parents/templates for users - this is just the normal user template, but I have enabled trashing users. This is important in this use case, so it would be great to make sure that users->get handles this correctly please.

> I will add a check for that null argument so that it returns null or NullPage rather than blank.

Thank you - that is more what I expected to see.

> The blank string is an empty placeholder for a user that is never found, and it should be returned null or NullPage instead. I will push a fix for this.

Great - also looks good, thanks!

@matjazpotocnik - I think the first two things above still need some clarification and / or fixes.

**Comment by ryancramerdesign** [comment] 2023-08-03 14:47
@adrian I can't figure out how to get these to behave differently:
~~~~~
$id = 2261; 
$pages->findOne($id);
$pages->findOne("id=$id");
~~~~~
I'm using a different user ID of course. In my case, if I'm logged in (superuser) then both work return a User. If I'm not logged in, then neither work and both return a NullPage.  Am I missing some part of how I should test?

Regarding trashed users, the user template comes with the `noTrash` flag. While you can unset that in advanced mode, it would be YMMV at that point. I thought that supporting trashed users opened more questions than I knew how to safely answer. I don't necessarily think it's a problem, especially for someone with our experience and skill. But since it's not technically supported by the core I think it's best not to make core changes around it at this time, but maybe later.

**Comment by adrianbj** [comment] 2023-08-03 16:04
@ryancramerdesign - I can't replicate that anymore either so I think you must have fixed that in your round of fixes for this issue.

I am still wondering about the `$pages->get($id)` though. Should that work without `check_access=0` for a non-superuser?

<img width="473" alt="image" src="https://github.com/processwire/processwire-issues/assets/871211/dbcfbc19-e985-4f3d-a846-5ac91e17987b">

Regarding users in the trash - it seems like some of that is behaving closer to expected now, except for the differences between `$pages` and `$users`, but I understand you don't want to tackle that for now.

PS - not sure if you make use of Tracy's User Switcher, but the "Logout to Guest" option is great for checking this stuff while still having access to the Console panel.

**Comment by matjazpotocnik** [comment] 2023-08-03 16:34
@ryancramerdesign @adrianbj I can replicate:

![image](https://github.com/processwire/processwire-issues/assets/7663992/23bec145-a7bd-4683-a458-6bbbf3a5c74c)

if I'm logged in (superuser) then both calls return a User object. If I'm not logged in, then neither work and both return a NullPage. If I'm logged as a user, but not superuser, then I get different results (Adrian, thanks for Tracy and user switcher). As Adrian "discovered", adding `check_access=0` to the selector gives the result:

![image](https://github.com/processwire/processwire-issues/assets/7663992/7d620c54-1458-4f86-8578-6827d2d1fdd2)

**Comment by ryancramerdesign** [comment] 2023-08-03 18:31
@adrianbj your get() result looks correct 

@matjazpotocnik Thanks I'll try it with a logged in user that isn't superuser. get() should behave that way, but I don't think findOne() is supposed to, I'll double check.

**Comment by ryancramerdesign** [comment] 2023-08-04 12:11
@matjazpotocnik I still can't duplicate that here, trying with a logged-in user that isn't superuser. I tried various permissions on that user such as page-edit and user-admin, but still not getting it. Is it possible that the user you are testing with (1070) is the same user that is logged in? If so, then it would also be expected to work. If not, can you tell me more about the roles/permissions setup that the user has? Also double check that your user template doesn't have some custom access control applied to it, since user template permissions are managed by the user-*  permissions instead.

**Comment by matjazpotocnik** [comment] 2023-08-04 13:53
Aha! My test user has a role that have user-admin permission:

![image](https://github.com/processwire/processwire-issues/assets/7663992/6c96ec9f-f656-4bd3-aed9-b7c3a0c5ebea)

If I revoke user-admin permission from the role, then `$pages->findOne('id=1070');` and `$pages->findOne(1070);` returns NullPage while `$pages->findOne('id=1070, check_access=0');` returns User object.

**Comment by ryancramerdesign** [comment] 2023-08-04 14:39
@matjazpotocnik Okay great, thanks for testing. Unless I'm missing anything, it sounds like we can close this one?

**Comment by adrianbj** [comment] 2023-08-04 15:23
I still don't understand why there is a difference in result between lines 41 and 42 in @matjazpotocnik's examples above.

**Comment by matjazpotocnik** [comment] 2023-08-05 07:32
@adrianbj I think a difference is in the selector. If a selector is an integer or a string that can be interpreted as an integer, e.g., string "1070", then findOne() method calls getById() method (or maybe get() method?), which in turn returns a result without any checking. Like the difference between get() and find() method: get() returns the first page matching the given selector with no exclusions, while findOne() filters for access control. Unlike the find() method, this method also performs a secondary runtime access check by calling $page->viewable() with the found $page and returns a NullPage if the page is not viewable with that call.

**Comment by adrianbj** [comment] 2023-08-05 16:03
Thanks @matjazpotocnik but I am not really asking about technically why it's different, but more why it's actually different. It's effectively asking the same thing and I think PW should handle them the same way.

**Comment by matjazpotocnik** [comment] 2023-08-08 07:00
And what would be the correct return value in that specific case, User or NullPage?

**Comment by ryancramerdesign** [comment] 2023-08-09 14:17
@adrianbj @matjazpotocnik The difference is that `id=123` is a selector that uses the PageFinder, whereas `123` is an ID, not a selector, and doesn't even need PageFinder. PageFinder just finds IDs after all. 

The PageFinder filters for access while it's finding pages (unless you use check_access=0 or include=all), so it joins the pages_access table to only load rows the user is known to have access to via predefined template settings. 

The user-admin permission is a runtime permission, where access is determined after the page is loaded with hooks. Since the access check for `123` runs after the page is loaded, it works (per user-admin permission). And since the access check for `id=123` runs before the page is loaded, it doesn't match. Though if you edited the user template and manually added view access to a particular role, then it would match.

**Comment by adrianbj** [comment] 2023-08-09 15:07
Sorry, but I really don't think `123` vs `id=123` should return different results. I understand the mechanics are different, but surely the result for both should be the same.

**Comment by ryancramerdesign** [comment] 2023-08-10 19:28
> surely the result for both should be the same.

No it shouldn't, not in this case. I'm happy to describe further. Using just the id has always been a way to shortcut around the PageFinder, and the system depends on it. Whereas using a selector means that you want to use the PageFinder.

When the PageFinder is involved, it uses a joined table to prevent it from returning page IDs that the user won't have access to, as dictated by access control settings defined with your template. The key here is that user access control is NOT managed by template, even if it is with all other pages.

If using a selector with a non-superuser to find users from a $pages.find* method, it's not going to find any, since user-admin is not a permission defined by template, and is a runtime permission (via hooks). It's one reason why there is a $users API variable, and why it should be used. User access control requires more granularity and consideration than regular page access control.

When you do a $pages.findOne(123) where 123 is a user ID then you are asking it to: 1) skip using the PageFinder; 2) load the page; 3) verify access. Since the PageFinder has been skipped, it will verify access after loading the page, not before. Since user-admin is a runtime permission, it works, so long as the user has that permission.

When you do a $pages.findOne($selector) you are asking it to 1): find the page using a selector (implies PageFinder); 2) verify access while finding page; 3) if page found then verify runtime access after loading page. Even if the querying user has user-admin permission, it won't find the user 123 because there are no template access control settings for this. Like I said, user access control requires more consideration than that.

The distinction doesn't matter at all except when it comes to runtime-only permissions managed by hooks, like user-admin, and only with a user that has that permission. A hook allowed the page when the database didn't, and that's exactly how it's supposed to and should work. In any case, you should be using $users for this anyway.  

I'm going to close this but if there are more questions please feel free to keep the conversation going.

**Closed as completed by ryancramerdesign** 2023-08-10 19:28 UTC
Labels: status: fixed-please confirm
