### ISSUE TITLE
Module refresh via api does not trigger upgrade/downgrade

### ISSUE THREAD

**Issue by saschanos** [processwire/processwire-issues#1304] opened 2021-01-12 18:28 UTC
### Short description of the issue

When performing a module refresh via the API, the upgrade/downgrade operation is not triggered.

### Expected behavior

When running the module refresh via the API, the upgrade/downgrade process should be triggered.

### Actual behavior

When running the module refresh via the API, the upgrade/downgrade process is not executed. It is necessary to trigger a GET request to the web page URL so that this happens.

### Steps to reproduce the issue

1. Creating a new migration via RockMigrations in git (module is included in whole website git)
2. Updating the module version in git
3. Pushing the changes
4. CI/CD is automatically building and creating a new docker container (with start of the container, refreshing via api is executed)
5. check database (changes done via migration are not executed)
6. opening website in browser (changes get executed)

### Setup/Environment

Discussion: https://processwire.com/talk/topic/24847-upgrading-via-command/?tab=comments#comment-209872

**Comment by ryancramerdesign** [comment] 2021-03-19 18:51
@saschanos In order to run an upgrade/download process, the module must be loaded and its upgrade() method called. With the exception of "autoload" modules, ProcessWire loads modules on demand, as requested from the API. This is an intended behavior. When you do a "Modules > Refresh", it should tell you about version changes it found and also indicate that it will apply those when the module is next loaded.

**Comment by saschanos** [comment] 2021-03-20 08:47
@ryancramerdesign, the problem is that after a module refresh, the changes are not executed until you access ProcessWire via HTTP. If you do the module refresh via the API, the changes are not executed until the next time you call ProcessWire from the browser. Is it possible to trigger the execution completely via the API?

**Comment by ryancramerdesign** [comment] 2021-08-04 17:04
@saschanos Module changes are applied when the module is next loaded, so it's not a matter of scheme (http, etc.) but rather just whether the module is needed and thus loaded for the request. Many modules are only used for rendering http requests (such as Process) modules, so it may have that appearance that http is required for some. It's best that updates are only applied when a module is actually going to be used, since it is the module's own upgrade() method that is called to perform the upgrade. And loading a module in a context where it wouldn't typically be used might be problematic or cause errors. But if you have a need for to do this, you could try doing a foreach `$modules` and load each module individually `$modules->getModule($name)`... updates will be applied as each is loaded. Again though I think it may be potentially problematic to do that since this is not the way it's designed to apply upgrades. I'll close this issue since it is applying updates how it's supposed to, but feel free to ask any more questions if I can be of any help.

**Closed as completed by ryancramerdesign** 2021-08-04 17:04 UTC
Labels: status: discussion
