### ISSUE TITLE
$page->fieldsetPage->getUnformatted('datefield') not working anymore in PW 3.0.210

### ISSUE THREAD

**Issue by WebWorkingMan** [processwire/processwire-issues#1713] opened 2023-03-30 16:54 UTC
### Short description of the issue

$page->fieldsetPage->getUnformatted('datefield') not working anymore in PW 3.0.210

I've updated one of my sites form 3.0.165 to 3.0.210 an noticed following problem - **which was working correctly before.**

I've a date field in a _FieldsetPage_ field, ~~which behaves technical like a repeater field, if I'm guessing right~~. Using the following code does not work like exacted.

### Expected behaviour

`$page->fieldsetPage->getUnformatted('datefield') ` should return unformatted date as php timestamp.

### Actual behaviour

Returns formatted date - see screenshot

### Optional: Screenshots/Links that demonstrate the issue

![2023-03-30 18_37_02-Bearbeite Seite_ Hero Göttler • gasthaus-goettler de – Mozilla Firefox](https://user-images.githubusercontent.com/3637410/228908382-c0b36b46-dbb6-4d39-8c90-c8474cd0269b.png)

### Steps to reproduce the issue

See above.

**EDIT**

I did some more tests: It's only a problem in the fieldsetPage and not in repeaters

![2023-03-30 19_01_03-Edit Page_ Test • pw-devtest vieregg design – Mozilla Firefox](https://user-images.githubusercontent.com/3637410/228911592-0979dba7-d5ce-4cc3-b67f-0842bdc6444a.png)

### Setup/Environment

* ProcessWire version: 3.0.210
* PHP version: 8.1.17

![2023-03-30 18_51_07-Felder • ProcessWire • gasthaus-goettler de – Mozilla Firefox](https://user-images.githubusercontent.com/3637410/228908843-e5d105ad-7b33-4962-9289-f4d0df5523c3.png)

**Comment by matjazpotocnik** [comment] 2023-03-30 19:11
Does it help if you do $page->of(false); before?

**Comment by WebWorkingMan** [comment] 2023-03-31 07:50
> Does it help if you do $page->of(false); before?

This is the output if doing so:

![2023-03-31 09_46_59-Edit Page_ Test • pw-devtest vieregg design – Mozilla Firefox](https://user-images.githubusercontent.com/3637410/229057862-1a69f78b-871a-41ba-9224-b5bff4dadd9d.png)

It seems strange to me, that the datefield behaves different on a "normal" page vs. in a fieldset.

**Comment by matjazpotocnik** [comment] 2023-03-31 12:27
How about $page->getUnformatted('fieldset.date_test');

**Comment by WebWorkingMan** [comment] 2023-03-31 12:59
> How about $page->getUnformatted('fieldset.date_test');

This seems to work properly:

![2023-03-31 14_58_53-Edit Page_ Test • pw-devtest vieregg design – Mozilla Firefox](https://user-images.githubusercontent.com/3637410/229126738-f686c36f-2162-45ba-a904-b8b1742f7820.png)

**Comment by ryancramerdesign** [comment] 2023-03-31 13:07
Thanks @WebWorkingMan @matjazpotocnik I've pushed a fix for this issue.

This issue occurs because the output formatting state of the FieldsetPage matches that of the page that it lives on. But this makes the getUnformatted/getFormatted methods of FieldsetPage useless, so I have corrected that so that they should now work as intended. Thanks.

**Comment by matjazpotocnik** [comment] 2023-04-14 18:07
@WebWorkingMan Ryan's fix works for me. Could you verify and close?

**Comment by matjazpotocnik** [comment] 2023-05-06 07:15
@WebWorkingMan I'm closing this, please reopen if the fix isn't working for you.

**Closed as completed by matjazpotocnik** 2023-05-06 07:15 UTC
Labels: status: fixed-please confirm
