### ISSUE TITLE
PageLabelField with Template » Wrong Dropdown Display

### ISSUE THREAD

**Issue by noelboss** [processwire/processwire-issues#726] opened 2018-10-15 13:48 UTC
### Short description of the issue

When defining a special PageLabelField in a Template, and using an Icon, the font-awesome icon code is displayed additionaly to the page-label in menu dropdowns

### Expected behavior

The font-awesom icon code should not appear.

Page Label in Template:

![screenshot 2018-10-15 at 15 45 53](https://user-images.githubusercontent.com/114080/46954675-7c5b6580-d091-11e8-9470-89fac45055d6.png)

Wrong Dropdown:

![screenshot 2018-10-15 at 15 46 55](https://user-images.githubusercontent.com/114080/46954704-8f6e3580-d091-11e8-9998-4b80d51e514d.png)

Correct Dropdown (no PageLabelField defined)

![screenshot 2018-10-15 at 15 45 30](https://user-images.githubusercontent.com/114080/46954730-a2810580-d091-11e8-81cc-57f2e9a3692b.png)

### Setup/Environment

<strong>Server Details</strong>

|Software|Version|
|------:|:-------|
|ProcessWire|3.0.116|
|PHP|7.2.11|
|Webserver|Apache|
|MySQL|5.5.60-MariaDB|
<details><summary><strong>Server Settings</strong></summary>

|Parameter|Value|
|------:|:-------|
|allow_url_fopen|1|
|max_execution_time|120 (changeable)|
|max_input_nesting_level|64|
|max_input_time|120|
|max_input_vars|20000|
|memory_limit|-1|
|post_max_size|16G|
|upload_max_filesize|10G|
|xdebug||
|xdebug.max_nesting_level||
|mod_rewrite|1|
|mod_security||
|GD|bundled (2.1.0 compatible)|
|GIF|1|
|JPG|1|
|PNG|1|
|EXIF Support|1|
|FreeType|1|
|Imagick Extension|1|
</details><details><summary><strong>Module Details</strong></summary>

|Module ClassName|Version|
|------:|:-------|
|AdminHelp|1.0.9|
|AdminHelpTab|1.0.8|
|AdminOnSteroids|2.0.4|
|AdminPageFieldEditLinks|3.1.2|
|AdminThemeBoss|0.4.0|
|BatchChildEditor|1.8.13|
|BreadcrumbDropdowns|0.1.10|
|ConnectPageFields|0.2.1|
|CronjobDatabaseBackup|1.1.5|
|FieldtypeAssistedURL|1.0.0|
|FieldtypeFieldsetGroup|0.0.2|
|FieldtypeFunctional|0.0.1|
|FieldtypeMultiplier|0.1.1|
|FieldtypeRepeaterMatrix|0.0.4|
|FieldtypeRuntimeMarkup|0.0.2|
|FieldtypeTable|0.1.5|
|FieldtypeTemplates|1.0.0|
|FieldtypeTextareas|0.0.7|
|FormBuilder|0.3.4|
|FrontEndEditLightbox|1.4.0|
|IcfAttachments|0.0.1|
|IcfAuthor|0.0.1|
|IcfDownloads|0.0.1|
|IcfFeaturedImage|0.0.2|
|IcfFormFeedback|0.0.1|
|IcfFormSec|0.0.1|
|IcfOauth2Login|0.1.0|
|IcfProcessInvite|0.0.1|
|IcfProcessInviteRequest|0.0.1|
|IcfRangeDownload|0.0.1|
|IcfResource|0.0.1|
|IcfTemplate|0.0.1|
|IcfUtil|0.0.1|
|InputfieldAssistedURL|1.0.1|
|InputfieldChosenSelect|1.2.3|
|InputfieldChosenSelectMultiple|1.1.9|
|InputfieldFormBuilderFile|0.0.2|
|InputfieldFunctional|0.0.1|
|InputfieldMultiplier|0.1.1|
|InputfieldRepeaterMatrix|0.0.4|
|InputfieldRuntimeMarkup|0.0.2|
|InputfieldTable|0.1.5|
|InputfieldTextareas|0.0.7|
|LoginRegister|0.0.2|
|LoginWithEmail|0.0.3|
|ModuleSettingsImportExport|0.2.9|
|PageimageRemoveVariations|0.0.4|
|ProcessAdminHelp|1.0.8|
|ProcessChildrenCsvExport|1.8.13|
|ProcessForgotPassword|1.0.2|
|ProcessFormBuilder|0.3.4|
|ProcessSetupPageName|2.1.0|
|ProcessWireUpgrade|0.0.7|
|ProcessWireUpgradeCheck|0.0.7|
|TextformatterMakeLinks|1.0.0|
|TextformatterTagParser|2.2.0|
|TracyDebugger|4.12.4|
|WireMailMandrill|0.0.1|
|TextformatterOEmbed|2.0.2|
|IcfAuth|0.0.2|
|TextformatterVideoEmbedOptions|0.3.6|
</details>

**Comment by rolandtoth** [comment] 2018-10-15 14:59
Just in case, could try it with AdminOnSteroids switched off?

**Comment by philippdaun** [comment] 2018-10-15 15:55
I can confirm this on 3.0.116 and have noticed it on earlier releases as well.

This is what I could gather so far:

When defining the label fields without curly braces, the icons work as intended: `title date`

Once you add curly braces, the font-awesome code is displayed as text: `{title} ({date})`

Another, related issue I stumbled upon:

When I define the labels without braces (`title date`), the page dropdown doesn't apply output formatting and shows dates as UNIX timestamps (see first screenshot below). Once I define them with braces (`{title} ({date})`), the dates are formatted correctly according to the datetime field settings.

<img width="801" alt="screen shot 2018-10-15 at 17 46 44" src="https://user-images.githubusercontent.com/22225348/46962341-2f808a80-d0a3-11e8-8b29-65c5fe50dc95.png">

<img width="774" alt="screen shot 2018-10-15 at 17 48 04" src="https://user-images.githubusercontent.com/22225348/46962331-27c0e600-d0a3-11e8-8703-c420853a1bb4.png">

**Comment by ryancramerdesign** [comment] 2018-11-29 19:00
Thanks, I've pushed a fix for this issue.

**Comment by netcarver** [comment] 2019-02-06 11:04
@noelboss Can this be closed now?

**Comment by philippdaun** [comment] 2019-02-06 11:26
Just tried it out on 3.0.125, the icons work fine but it seems any spaces between label fields are collapsed.

E.g., defining the label fields as `title abbreviation` will remove the space between them — both in the page list as well as in the page dropdown. I would expect a space between fields as the default behaviour here.

<img width="460" alt="screenshot 2019-02-06 at 12 18 40" src="https://user-images.githubusercontent.com/22225348/52338197-0006dc80-2a0a-11e9-9fc5-870ad9b14b3b.png">
<img width="478" alt="screenshot 2019-02-06 at 12 18 52" src="https://user-images.githubusercontent.com/22225348/52338209-09904480-2a0a-11e9-8768-3f1d50878e91.png">

Should I go ahead and open another issue since this doesn't concern the original issue about fontawesome icon display?

**Comment by netcarver** [comment] 2019-02-06 11:31
@philippdaun Thank you, re-labelling as "work in progress".

**Comment by netcarver** [comment] 2019-03-29 17:29
@ryancramerdesign Bumping this for your further consideration.

**Comment by ryancramerdesign** [comment] 2019-04-02 14:15
> Just tried it out on 3.0.125, the icons work fine but it seems any spaces between label fields are collapsed.

@philippdaun @netcarver I can't duplicate this one. I'm testing on the current dev branch (3.0.128) though am not aware of any related changes between 3.0.125 and 3.0.128. When you use just field names (without the curly brackets) it separates each field with a comma followed by a space. It sounds like something is overriding that behavior. Can you think of anything installed that might be overriding it? (module or hook)

**Comment by daun** [comment] 2019-04-02 14:27
@ryancramerdesign The issue seems to be in the page tree dropdown in the main nav bar. The page list itself looks fine on 3.0.125.

<img width="383" alt="Screenshot 2019-04-02 at 16 18 16" src="https://user-images.githubusercontent.com/22225348/55410120-9ca9ae80-5563-11e9-8f6b-129f7e1b91d1.png">

The markup looks like this, so I'd suspect the spaces are being swallowed somewhere along the line. (It should be between `Schottenfeldgasse` and `SFG`)

```html
<a href="/admin/page/edit/?id=1135" class="">
    <i class="ui-priority-secondary fa fa-fw fa-cube"></i> Dachgeschossausbau SchottenfeldgasseSFG &nbsp; 
</a>
```

**Comment by ryancramerdesign** [comment] 2019-04-02 14:44
Thanks @philippdaun I was just looking in the wrong place (PageList rather than Tree). I see what you are talking about now and have just pushed a fix.

**Closed** 2019-04-29 14:22 UTC
Labels: resolution: fixed (close when ready)
