### ISSUE TITLE
Questions about Page::statusCorrupted

### ISSUE THREAD

**Issue by thetuningspoon** [processwire/processwire-issues#909] opened 2019-06-19 21:17 UTC
When a page has output formatting turned on and a field on the page is set with a **new** value, the page is given a corrupted status and that field is added to a _statusCorruptedFields array. When save() is called on the page, PW checks for the corrupted status and throws an error.

I am seeing 2 issues with this:

1. The corrupted status is only set if the value was already loaded before trying to set it. e.g:

```
$page = $pages->get(123);
$page->title = 'foo';
$page->of(false);
$page->save();
```

Throws no exception. While:

```
$page = $pages->get(123);
echo $page->title; // current field value is accessed
$page->title = 'foo'; // new value is set
$page->of(false);
$page->save();
```

Throws an exception because $page->title has already been accessed. Is this intentional behavior or is it a bug? If intentional, why is it okay to set the field before accessing it but not after?

Of course, setting the output formatting state to false _before_ setting and/or getting (as is recommended) resolves this:

```
$page = $pages->get(123);
$page->of(false);
echo $page->title; // current field value is accessed
$page->title = 'foo'; // new value is set
$page->save();
```

2. The second issue I see is with the purpose that the corrupt status is (or perhaps is not) serving. For purposes of demonstration (the title fields in this example have the htmlspecialcharacters formatter applied):

```
$page = $pages->get(123);
echo $page->title; // current field value is accessed
$page->title = '<script>Setting a string with some tags</script>'; // Setting a new value - could be anything, but we'll use something that would be affected by the output formatter

$page->of(false);
$page->set('_statusCorruptedFields', null); // Clearing the corrupt status that would have been set above
$page->removeStatus(Page::statusCorrupted); // Clearing the corrupt status that would have been set above
$page->save();
```

The string saved to the database is, as I would expect, `<script>Setting a string with some tags</script>`. When output later on with formatting turned on, it is properly encoded as `&lt;script&gt;Setting a string with some tags&lt;/script&gt;`. So, despite the fact that this save operation normally would have resulted in a corrupt page status and an exception being thrown, there is actually nothing wrong with the result.

Now, I believe the concern here is actually more about unintentionally using the formatted value from one page and saving it as a value on another page. So let's try that:

```
$page = $pages->get(123);
$page2 = $pages->get(456);

$page2->title = '<script>Setting a string with some tags</script>';
$page ->title = $page2->title;

$page->of(false);
$page->set('_statusCorruptedFields', null); // Clearing the corrupt status that would have been set above
$page->removeStatus(Page::statusCorrupted); // Clearing the corrupt status that would have been set above
$page->save();
```

The result of this is that `&lt;script&gt;Setting a string with some tags&lt;/script&gt;` is saved in the database. When output, it will be double encoded by the formatter. So, that's not what we wanted, but no harm is done. In fact, there may even be some unusual scenario under which that is what I intended to do. Regardless, normally the corrupt status would have prevented the save from happening.

**Now**, let's move the output formatting switch and see what happens:

```
$page = $pages->get(123);
$page->of(false); // Turning off of on the first page right away
$page2 = $pages->get(456); // Page2 is still formatted

$page2->title = '<script>Setting a string with some tags</script>';
$page ->title = $page2->title;

$page->save();
```

The result in the database is the exact same encoded string `&lt;script&gt;Setting a string with some tags&lt;/script&gt;`, but this time the save goes through no problem (without manually clearing the corrupted status). The reason is because the field's set operation only knows about its **own** output formatting status, and **not** the output formatting status of `$page2`--which is the only output formatting status that actually matters in determining whether or not `$page` is corrupt. 

### Optional: Suggestion for a possible fix

Unless I am overlooking some other purpose, it appears to me that the corrupt status is often getting set when it does not need to be, and often not getting set when it could be helpful. I believe the benefits of removing it entirely would outweigh the rare cases where it would have prevented someone from saving a formatted value when they meant to do otherwise. And those cases are rare, because there is no way for the page being saved to actually know about the output formatting state of the values being set to it. 

We could then have the save() method automatically disable and restore output formatting, in the same manner that setAndSave() does.

Here is a hook I wrote to add a `forceSave()` method that bypasses the corrupted flags and disables output formatting:

```
$this->addHook('Page::forceSave', function($e) {
	$field = $e->arguments(0);
	$options = $e->arguments(1) ?: [];
	$page = $e->object;

	$of = $page->of(false); // Turn off output formatting
	// Reset any corrupted status flags so they will not prevent the save
	if($page->hasStatus(Page::statusCorrupted)) {
		$page->set('_statusCorruptedFields', null);
		$page->removeStatus(Page::statusCorrupted);
	}
	$return = $page->save($field, $options);
	$page->of($of); // Restore output formatting to previous state

	$e->return = $return;
});
```

* ProcessWire version: 3.0.123

**Comment by ryancramerdesign** [comment] 2019-06-21 13:58
The purpose of the corrupted status is to be a basic help to get you following best practices with regard to output formatting. While not completely necessary and there are always ways around it, it's just looking for cases consistent with the potential for existing values on a page getting saved in a formatted state. 

What "formatted" means depends on the Fieldtype. But if you are observing corrupted status at all, then it means you might be treading into territory where corruption *can* occur (not necessarily *will*), like when you are using pages for both front-end output and manipulation at the same. I recommend using a page either for front-end output or for manipulation, but not both at the same time. If you must use it for both at the same time, then keep it in an unformatted state and use getFormatted() method when you need a formatted value, and of course don't set that formatted value back to the page. Following these best practices is preferable to adding hooks to bypass things. 

I don't recommend it, but yes you can get around corrupted status by manipulating internal Page properties yourself. When a page property begins with an underscore, it means it's intended for internal use and it could be problematic to manipulate it yourself. Also, if you are populating field values before accessing them in the same request, then that's allowed since your own logic is the source of the value rather than the page.

**Comment by netcarver** [comment] 2019-10-31 21:05
Hello @thetuningspoon Does Ryan's reply above answer your questions? Can this issue now be closed?

**Comment by thetuningspoon** [comment] 2019-10-31 23:58
I think this is still an important issue that should get further attention. The corrupt status doesn't seem to tell the user anything meaningful and trips up a lot of new PW users. If PW's goal is to avoid unnecessary complexity, then I feel that the corrupt status works against that goal in its current implementation.

I agree that it's important for developers to be aware of output formatting, but there is nothing inherently corrupt about saving a formatted value to the database. The developer can make that decision on their own.

If the goal is truly to prevent developers from performing a save when output formatting is on, then PW should simply not ever allow a page with output formatting turned on to be saved, rather than trying to determine whether it might be corrupt or not, leading to intermittent exceptions that are difficult to track down. 

Having said that, I feel the need to reiterate that the output formatting state of the page being saved is not very relevant to whether or not the values being saved to it are formatted or not. In fact, the page has no way of knowing whether those values are formatted. That being the case, I do not feel that the corrupt status is helpful.

We already have setAndSave(), which is a useful workaround for this issue. My suggestion would be to add a forceSave() method that does the same thing as save() without the corrupt status check. Or presumably the save() method could be changed, since removing the check would be fully backwards compatible.

**Comment by ryancramerdesign** [comment] 2021-08-13 18:18
I'll close this because I don't think there's a bug here to fix, but if you have more ideas about this feel free to re-open in the requests repo. 

> ...there is nothing inherently corrupt about saving a formatted value to the database. 

There is because the next time it is loaded, then formatted, it is double formatted. Every time a formatted value is saved, the process repeats. So you save formatted value with `&nbsp;` in it. Then on next load, is is formatted to `&amp;nbsp;`, you save again (whether API or page editor) and now it loads to `&amp;amp;nbsp;`.  Or maybe output formatting is rounding a number, and you save it, the rounded number is saved, losing data that may not matter for output but does for some financial calculation. These are just two examples. Best bet is to flag values as corrupted when the case is detected to ensure they don't get saved. 

> If the goal is truly to prevent developers from performing a save when output formatting is on, then PW should simply not ever allow a page with output formatting turned on to be saved, rather than trying to determine whether it might be corrupt or not

I don't think this helps because then someone just turns off output formatting to complete the save, and corrupted values are still present and saved to the DB. So the source of the problem is still there. 

The point of this corrupted status is prevent people from corrupting their data. Someone should never see it if they are following best practices, turning off output formatting before getting, modifying and setting values to the page. If one is seeing this error, then it's better that they listen to it rather than try to bypass it. It means they are turning off output formatting too late in the process and there's potential for data corruption.

**Closed as completed by ryancramerdesign** 2021-08-13 18:18 UTC
Labels: status: discussion, status: has suggested fix

**Comment by thetuningspoon** [comment] 2021-08-22 18:50
@ryancramerdesign Thanks for getting back to this. Sorry for reopening. If someone knows how to move this to the requests, please do.

> There is because the next time it is loaded, then formatted, it is double formatted.

This assumes that you are saving the data from a formatted field back to itself or to another field that is also formatted in the same way. But you don't really know that.

> I don't think this helps because then someone just turns off output formatting to complete the save, and corrupted values are still present and saved to the DB. So the source of the problem is still there.

How is this different from what happens now, though? The output formatting state of the page that I'm saving the data **TO** is irrelevant for determining whether or not it is corrupt. The only thing that is relevant is the output formatting state of the page that I got the data **FROM**, and PW has no way of knowing that, which results in confusing behavior.

For example, it should be possible to turn off output formatting on one page, get some data from it, and save it to a different page that has output formatting turned on. There's no chance of corruption of data there, yet PW will balk because it guesses that I might have done something wrong.

It should also be possible to turn off output formatting on a page, get the data I want to use, turn output formatting back on, and then save the unformatted data I got earlier back to the same page. Again, PW guesses I might have done something wrong, but the data would not be corrupt.

And if I use getUnformatted() to get some value that I want to save again somewhere, I shouldn't have to worry about disabling output formatting for either the page I got it from or the page that I'm setting it to.

On the other hand, it should NOT be possible (according to your stated intent of the corrupt status) to get data from a formatted page and then save it to a different page (even if the second page has output formatting disabled). Yet this won't trigger an exception (see my OP for an example of this scenario).

I hope this helps clarify what I'm trying to say. I feel like we're talking past each other, but I do want to better understand where you're coming from and whether or not there's something key that I'm missing here. I'm not just trying to be difficult ;-)
