### ISSUE TITLE
"Add new" doesn't work with templates allowed to be it's own parent

### ISSUE THREAD

**Issue by LostKobrakai** [processwire/processwire-issues#699] opened 2018-09-13 15:03 UTC
### Short description of the issue

When using the family settings on a template and creating a new page using the "Add new" functionality it doesn't detect places where the template is allowed to be the child of the same template.

### Expected behavior

Detect all possible location of where a new page might be added.

### Actual behavior

The nested template locations are missing.

### Setup/Environment

* ProcessWire version: 3.0.98
* (Optional) PHP version: 7
* (Optional) MySQL version: 
* (Optional) Any 3rd party modules that are installed and could be related to the issue:

**Comment by Toutouwai** [comment] 2018-09-13 23:12
Do you mean the new page template has more than one allowed parent template?

Because PW ignores all but the first allowed parent template in the "Add New" feature. There is an open request for it to account for multiple parent templates: https://github.com/processwire/processwire-requests/issues/209

**Comment by LostKobrakai** [comment] 2018-09-14 17:32
that sounds even less desirable

**Comment by ryancramerdesign** [comment] 2019-04-01 15:54
@LostKobrakai I think this one is fixed in the commit [here](https://github.com/processwire/processwire/commit/2e7db9c40f2148b57dca4a7332ea7261c132290b) I just pushed for #778 as that issue report seems to be a duplicate of this one. Can you confirm it also fixes it for you? Thanks.

**Closed** 2019-04-29 14:43 UTC
Labels: status: fixed-please confirm
