### ISSUE TITLE
Page vs Page Reference consistency of labeling

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-issues#507] opened 2018-03-02 03:26 UTC
### Short description of the issue

Sometimes the legacy label "Page" is used, rather than the new "Page Reference"

One key place is in the type column on the /setup/field page, but there are likely others.

**Comment by teppokoivula** [comment] 2018-03-02 09:28
As a testament to said inconsistency, I had no idea that "Page Reference" was in any way an official term. I thought it was just something folks thought up at the support forum to explain _what_ a Page field does :)

**Comment by szabeszg** [comment] 2018-03-02 09:39
Some time ago the term was changed in the config of the inputfield's dropdown. I do not know where else but consistency is always welcome ;)
I think the term "Page Reference" field is technically more exact, so it seems to be a change in the good direction.

**Comment by ryancramerdesign** [comment] 2018-03-06 14:30
Page Reference is not any kind of official term. It's the title used by FieldtypePage, because there are other modules with Page in the title. So if you see Page Reference it's usually referring to the Fieldtype module. A Page field is just a "Page" field (it's not a legacy label), but if there's an instance where it's not obvious what we're referring to, then Page Reference seems to clarify it, kind of like stating someone's first and last name. But I mostly just refer to them as Page fields.

**Comment by Toutouwai** [comment] 2018-03-06 21:55
> Page Reference is not any kind of official term.

I'm surprised to hear that, because it seemed like there was a deliberate decision to switch the terminology to Page Reference some time ago.

I think the fact that nobody commented much about the change indicates that pretty much everyone agrees that "Page Reference" is a clearer name and it made sense to switch to it. I think the term "Page Reference" should be used consistently across PW rather than "Page".

Naming the field "Page" is less clear, and I think it can potentially add confusion for new users who are still adjusting to the fact that "pages" are treated more broadly in PW than in other systems they might be familiar with. I know when answering questions in the forum, using "Page Reference" adds some much needed clarity to sentences that might use the term "page" half a dozen times or more with different meanings. Consider sentences where there is some sloppiness in capitalisation:

"The value of a page field is a page or a pagearray of pages, and you can determine the pages that appear in a page field when a page is opened in page edit via the selectable pages settings in the page field config."

**Comment by adrianbj** [comment] 2018-03-06 21:59
> Naming the field "Page" is less clear, and I think it can potentially add confusion for new users who are still adjusting to the fact that "pages" are treated more broadly in PW than in other systems

I completely agree - "Page" gets thrown around in PW so much that it can be a little confusing. "Page Reference" clears this up and explains what this fieldtype does - it **references a page**, but it **is not actually a page**

**Comment by teppokoivula** [comment] 2018-03-07 06:17
I honestly don't mind which term is used, but I've found it difficult to explain things properly when terminology is inconsistent. While I get the point that @ryancramerdesign makes, I would still prefer consistent naming/labeling through and through :)

> A: You can use a Page field to implement a simple tagging system.
> 
> B: Wait, don't you mean Page Reference field? By the way, what's the difference between Page fields and Page Reference fields? Which one should I use in my perpetual motion machine?

That right there was a completely imaginary discussion (those are kind of my specialty), but that's the type of confusion that inconsistent naming often leads to. And so is this whole issue, for that matter.

**Comment by netcarver** [comment] 2019-02-14 23:19
@ryancramerdesign As this is marked as not a bug, I'd like to move it to the processwire-requests repo provided it's likely to be considered for action again over there. If not, it might as well be closed now.

**Comment by ryancramerdesign** [comment] 2019-02-15 15:57
@netcarver I think it's okay to close, I've already made note of the request and will keep it in mind when writing about these fields in the future.

**Closed** 2019-02-15 16:14 UTC
Labels: resolution: not a bug, status: discussion, status: impacts multiple users, type: consistency
