### ISSUE TITLE
 problem with page parent change in admin tree

### ISSUE THREAD

**Issue by valieand** [processwire/processwire-issues#209] opened 2017-03-10 08:04 UTC
### Problem with page parent change in admin tree
When I change page parent and new parent is user page (with enabled 'may have children' in user template) then it changes parent, but "freezes" so I have to close session and re-login. After re-login, page has new parent (e.g. moved OK).

The same happens in API. Code below "freezes" and does not return from $page->save(). Looks like it falls to endless loop somewhere inside save(). It also does not generate any errors.
```
$page->of(false);
$page->parent = $some_user_page;
$page->save();
echo 'Success'; // PHP does not reach this line
```

Everywhere else except admin tree (I've tested under user pages and under admin menus), parent change works OK.

Problem has been described at forum first (https://processwire.com/talk/topic/15740-problem-with-page-parent-change-in-admin-tree), no resolution so far.

### Expected behavior
Either generate error or return from save().

### Steps to reproduce the issue
![pwbug](https://cloud.githubusercontent.com/assets/4989626/23786799/058b2b4e-0580-11e7-8382-6de941869fb2.gif)

### Setup/Environment
PW 2.8.35
PHP 7.0.14
MySQL 5.7.14, InnoDB

**Comment by ryancramerdesign** [comment] 2017-03-14 19:09
I'm not observing that behavior here. I can move subpages of User template pages around like any others. But something that you may want to check, because User pages can be locked down a bit by default. Edit your user template, and click to the Advanced tab, and uncheck the box that disallows pages from being moved. Do the same for the template used by children of your User pages.

**Comment by valieand** [comment] 2017-03-15 06:00
@ryancramerdesign thanks. That was my initial thought also. But both User and children have unchecked "Don't allow pages to be moved".

**Comment by ryancramerdesign** [comment] 2017-03-15 13:23
Since there's a couple of issue reports from you here where I can duplicate the issue, it might be good to look at what modules are installed (Site tab)? Also, do you have any hooks in place, like in your /site/ready.php file?

**Comment by Zarik** [comment] 2017-03-23 13:06
Seems that we have found the reason of the problem.
#220

**Comment by netcarver** [comment] 2019-02-06 13:59
@valieand Andrey, is this issue still alive given changes to the codebase since first report?

**Comment by netcarver** [comment] 2019-02-16 20:14
Seems to be a duplicate of #220. Closing.

**Closed by netcarver** 2019-02-16 20:14 UTC
Labels: status: not reproducible
