### ISSUE TITLE
Inputfield Selector giving wrong result regarding "Created by User" and "Modified by User" system fields

### ISSUE THREAD

**Issue by karltdev** [processwire/processwire-issues#364] opened 2017-08-31 16:37 UTC
### Short description of the issue

Issue exists when the amount of users exceed the $maxUsers(default 20). When choosing operator "Not Equals" for this given situation, the filter is not working if you are typing the user's name(only, id is fine). If you keep the state and refresh, all the users except the one you typed will appear as filter criteria and listed one by one with "AND" checkbox checked.

### Steps to reproduce the issue

1. set $maxUsers to the amount smaller than your existing user amount, for clean install set 1 inside 
2. open lister or listerpro, add a new filter with field "Modified by User"
3. the value filed would become a text input field instead of a drop down because the $maxUsers is lower than the amount of user and the operators become equals, contain text and not equals from equals and not equals for the same reason
4. set operator to "NOT EQUALS" and enter a user name(not id) into the text field i.e. admin
5. admin still shows up from the result even though "NOT EQUALS" admin is set
6. reload the browser, a new filter appears with "NOT EQUALS" and value 40(id of guest, if there are more users, all of them will be listed with with "AND" checkbox checked)

### Setup/Environment

* ProcessWire version: 3.0.73

**Comment by Toutouwai** [comment] 2019-02-10 03:30
I'm thinking that this is probably not a bug. Any "page" field in InputfieldSelector (e.g. "parent") only works with the page ID as an input. The "users" field is a page field. When $maxUsers is not exceeded and a select input is used the value written to the field is still an ID and the user name is just the option label for convenience:

![2019-02-10_162714](https://user-images.githubusercontent.com/1538852/52529102-c9ee9300-2d50-11e9-9aee-f53d4835e90c.png)

Also there is a [comment in InputfieldSelector](https://github.com/processwire/processwire/blob/649d2569abc10bac43e98ca98db474dd3d6603ca/wire/modules/Inputfield/InputfieldSelector/InputfieldSelector.module#L406-L407):

> // make users selectable if there are under $maxUsers of them
> // otherwise utilize the user ID property

This indicates that an ID is expected as input when $maxUsers is exceeded.

**Comment by karltdev** [comment] 2019-02-10 03:52
Thanks Toutouwai for clarifying. So, steps 3-5 are the expected behavior. 

Step 6 is still a bug. Users may not know that the field can only be entered in User ID, like me. Once they entered the field wrongly with name, like "admin", after reloading the browser, there will be a list (could be a very large list depending on how much users have been registered) of filters appear.

**Comment by Toutouwai** [comment] 2019-02-10 04:32
Taking a closer look at InputfieldSelector it looks like there actually is support for entering a user name instead of a user ID, specifically for modified_users_id and created_users_id. It's in this [section here](https://github.com/processwire/processwire/blob/649d2569abc10bac43e98ca98db474dd3d6603ca/wire/modules/Inputfield/InputfieldSelector/InputfieldSelector.module#L1922-L1937).

But the code for translating the user name into a user ID is not correct when the operator is "not equals".  
If my row in InputfieldSelector is "modified_users_id not equals robin" then this should get translated into "modified_users_id!=41". But instead, in attempting to get the user by name the selector string "name!=robin" is constructed, which of course returns all the IDs _apart from_ the desired ID. This leads to a wrong selector used in the InputfieldSelector/Lister results: "modified_users_id!=40|1316|1317|1380|1387|1390" (for as many user IDs exist in the site)

There is some mixup going on where the operator that belongs to the filter line (the "not equals") is being used in an attempt to match the user name to the user ID. Instead an "equals" should be used there.

**Comment by Toutouwai** [comment] 2019-02-10 10:08
A possible fix, replacing the lines [here](https://github.com/processwire/processwire/blob/649d2569abc10bac43e98ca98db474dd3d6603ca/wire/modules/Inputfield/InputfieldSelector/InputfieldSelector.module#L1926-L1927)...

```php
$operator = $s->operator === '!=' ? '=' : $s->operator;
$users = $this->wire('users')->find("$property$operator" .
	$this->wire('sanitizer')->selectorValue($this->wire('sanitizer')->pageNameUTF8($name)));
```

**Comment by netcarver** [comment] 2019-03-14 20:36
@ryancramerdesign Bumping this for your consideration.

**Comment by ryancramerdesign** [comment] 2019-03-19 14:30
Thanks @Toutouwai @karltdev @netcarver I've pushed a fix for this issue based on the one suggested by @Toutouwai

**Comment by netcarver** [comment] 2019-03-29 17:32
Closing this one now. Please post more if needed.

**Closed by netcarver** 2019-03-29 17:32 UTC
Labels: resolution: fixed (close when ready), status: impacts multiple users, status: includes suggested fix, type: fields
