### ISSUE TITLE
LanguageSupport.module setlocale(LC_ALL, $locale)

### ISSUE THREAD

**Issue by trk** [processwire/processwire-issues#215] opened 2017-03-14 15:35 UTC
# Question
is `wire/modules/LanguageSupport/LanguageSupport.module` line `185` and `186`
```php
$locale = $this->_('C'); // Value to pass to PHP's setlocale(LC_ALL, 'value') function when initializing this language // Default is 'C'. Specify '0' to skip the setlocale() call (and carry on system default).
if($locale != '0') setlocale(LC_ALL, $locale);
```
only working for admin side, for selected profile language ? or is this a bug ?

# Explanation and Test
Website have 2 languages, `English (default)` and `Turkish (second)`. My default profile language is `English`.

Viewing website in`English` setlocale test :
```php
$setlocale = setlocale(LC_ALL, 0);
echo "<br /><br /><br />setlocale : ", $setlocale, "<br />gmstrftime : ", gmstrftime('%A %e %B %Y, %H:%M');
```
Viewing website in`English` setlocale test result :
```
setlocale : en_GB.UTF-8
gmstrftime : Tuesday 14 March 2017, 15:13
```
Viewing website in`Turkish` (my C translation for `Turkish` language is `tr_TR.UTF-8`) setlocale test :
```php
$setlocale = setlocale(LC_ALL, 0);
echo "<br /><br /><br />setlocale : ", $setlocale, "<br />gmstrftime : ", gmstrftime('%A %e %B %Y, %H:%M');
```
Viewing website in`Turkish` (my C translation for `Turkish` language is `tr_TR.UTF-8`)  setlocale test result :
```
setlocale : en_GB.UTF-8
gmstrftime : Tuesday 14 March 2017, 15:13
```
If i change my profile language to `Turkish` result for both (`English` and `Turkish`) test are :
```
setlocale : tr_TR.UTF-8
gmstrftime : Salı 14 Mart 2017, 15:33
```
Changing language on fron-end not effecting to setlocale setting. System taking setlocale setting from selected profile language. It's not matter which language you using for view website. If your profile language is `English` setlocale setting for whole website will come from `English` language.

# Request
Can you add language setlocale option to language api, like : `$language->getLocale();`

* ProcessWire version: 3.0.55
* PHP version: 7.1.1 
* MySQL version: 5.6.35

**Comment by ryancramerdesign** [comment] 2017-03-15 13:35
I may not be understanding correctly, but if I am, that sounds consistent with how it works. For a logged in user, the locale setting is connected with the user language setting. If you need it to come from somewhere else for the front-end, you can always override with your own setlocale() call in your /site/templates/_init.php or whatever file you are using for initialization:
~~~~
// one option
setlocale(LC_ALL, $this->_('en_GB.UTF-8')); // translatable

// another option
switch($user->language->name) {
  case 'en': setlocale(LC_ALL, 'en_GB.UTF-8'); break;
  case 'tr': setlocale(LC_ALL, 'tr_TR.UTF-8'); break;
} 
~~~~~

**Comment by matjazpotocnik** [comment] 2017-03-15 13:52
Locale is coming from currently logged user, for anonymous users this is from guest profile. If you change url to /tr/ PW switches the language, but not the locale, at least that's my tests say so. @ryancramerdesign , what @trk is trying to say (at least how I understand it) that it would be nice, if we could also have an option, maybe checkbox on the Settings tab on Home page, that would execute setlocale() based on translation of "C" string in LanguageSupport.module. That way locale aware functions would also work on the frontend, not just on the backend and we wouldn't have to do it manually.

**Comment by trk** [comment] 2017-03-15 13:54
@matjazpotocnik 👍

**Comment by ryancramerdesign** [comment] 2017-03-16 13:52
Thanks guys, I understand now. Plus, it looks like it wasn't working quite as intended too. I have pushed an update that makes it use the locale setting on the front-end when using LanguageSupportPageNames module. Also added setLocale() and getLocale() methods to the `$languages` API var.

**Comment by matjazpotocnik** [comment] 2017-03-16 15:14
I tested and it's working for me. @trk could you verify and then close this issue?

**Comment by trk** [comment] 2017-03-16 16:00
I tested also and it's working on my side.

There is misspelling : https://github.com/processwire/processwire/commit/9c92ce530577531214f940ec4cab7fa57e2c23ec#diff-3480931e97012ef934bb9b725061b1edR391
```php
// wrong
$langauges->setLocale(LC_CTYPE, 'en_US.UTF-8'); 
// true
$languages->setLocale(LC_CTYPE, 'en_US.UTF-8');
```

**Comment by matjazpotocnik** [comment] 2017-03-16 19:13
> How can i get getLocale() result for specific language

$languages->getLocale() method returns current locale and does not support what you want. Your foreach example will not work, as getLocale is method of $languages, not $language. What you could do is this:

```
foreach($languages as $l) {
	$locale = $l->translator()->getTranslation('wire--modules--languagesupport--languagesupport-module', 'C');
	echo "Language: {$l->name}, Locale: $locale\n";
}
```

@ryancramerdesign could fulfill one's wish.

**Comment by trk** [comment] 2017-03-16 19:42
**I am thinking to use it for** `hreflang, multilanguage sitemap creation, og:locale, link:alternate, languages menu flags` etc..

I am using `$homepage->getLanguageValue($user->language, 'name')` method, for get language name, but `$language->getLocale()` api call is much effective.

If @ryancramerdesign won't add `$language->getLocale()` api call, I will use your `$languages` loop.

**Comment by ryancramerdesign** [comment] 2017-03-20 12:30
I've gone ahead and added `$language->getLocale()` and `$language->setLocale()` methods to accompany some other updates to the equivalent versions in `$languages` API variable. I think this will provide what you are looking for?

Something to note is that changing the `$user` language manually does not automatically change the PHP locale setting. PW just sets the locale consistent with what the user's language is before Page::render. So if you are changing the user language at runtime and also wanting to change the locale at the same time, do this:
~~~~
$user->language = $languages->get('name');
$user->language->setLocale();
~~~~

**Closed** 2017-03-20 13:37 UTC
Labels: resolution: fixed (close when ready)
