### ISSUE TITLE
ProcessPageList: number of children does not account for listable

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#649] opened 2018-07-29 00:12 UTC
### Short description of the issue

In ProcessPageList the number of children under each parent page is indicated by a number next to the page title. However, this number does not take account of the `$page->listable` boolean which determines which child pages will in fact be listed under that parent.

So for example, the core `Page::listable` method says that a page is not listable if it isn't editable by the current user and the page is unpublished: 
https://github.com/processwire/processwire/blob/c01289edb7ad650bb635e412b490e8db8fe91989/wire/modules/PagePermissions.module#L626

But because this isn't taken into account by ProcessPageList the wrong number of children can be indicated, which is confusing for the user.

Superuser:
![2018-07-29_120323](https://user-images.githubusercontent.com/1538852/43361623-a08f6994-9327-11e8-981f-06825f187437.png)

Non-superuser:
![2018-07-29_120414](https://user-images.githubusercontent.com/1538852/43361625-aa14ce28-9327-11e8-8f72-74cd0de2cd86.png)

Interestingly it is not just the two unpublished pages that result in the incorrect child count, meaning the 404 page, Admin page or Trash page must also be incorrectly included in the child count of Home, so that count will be wrong for non-superusers even on a brand new PW installation with the Blank profile.

This issue also creates a problem for anyone hooking `Page::listable` to set a custom listable value, which is something I do regularly. I previously raised this as part of a [feature request](https://github.com/processwire/processwire-requests/issues/194), but now I see that an issue occurs even without custom listable values I'd consider this a bug.

### Setup/Environment

* ProcessWire version: 3.0.108

**Comment by netcarver** [comment] 2018-07-29 09:12
@Toutouwai Hi Robin. I can verify that this is reproducible in an older install as well (3.0.68)

**Comment by ryancramerdesign** [comment] 2018-08-06 14:57
The numbers are determined before the pages are loaded via database count() calls, and are the closest it can get without actually loading all the pages and checking them individually. ProcessWire can support pretty much an infinite amount of children on any given page, and it's not practical for it to call a listable() hook on all children of a page. For non-superuser with unpublished pages, they have to examined individually before it would be known if the user has edit permission to them (and thus would be able to see them in a list). On the front-end, it's a non-issue since unpublished pages never appear in lists. The numbers indicate the the highest possible that *could* be listable in order to ensure that the item is at least openable.

**Comment by netcarver** [comment] 2019-02-06 12:07
@ryancramerdesign Just bumping this for your consideration of Robin's request. If this is still a "won't fix", should it be closed?

**Comment by netcarver** [comment] 2019-02-16 20:26
/remind me to review this issue in 2 weeks

**Comment by ryancramerdesign** [comment] 2019-02-26 13:41
@Toutouwai @netcarver 

I've added a method here that you can hook to modify the children count in PageList. 

~~~~~
$wire->addHookAfter('ProcessPageListRender::getNumChildren', function($event) {
  $page = $event->arguments(0);
  $selector = $event->arguments(1);
  $event->return = $page->numChildren($selector); // your implementation here
 }); 
~~~~~

**Comment by Toutouwai** [comment] 2019-03-03 01:42
Much appreciated, thanks Ryan.

**Comment by ryancramerdesign** [comment] 2019-03-04 14:47
Closing because remindersBot opened it

**Closed by ryancramerdesign** 2019-03-04 14:47 UTC
Labels: resolution: won’t fix, status: impacts multiple users, status: reproducible, type: page tree
