### ISSUE TITLE
relativeTimeStr + Server Timezone + $config->timezone issue?

### ISSUE THREAD

**Issue by jlahijani** [processwire/processwire-issues#270] opened 2017-05-23 17:06 UTC
My server time is UTC (untouched Digital Ocean droplet).
My PW $config->timezone is set to 'America/Los_Angeles' (7 hours behind utc).

When the created (or modified) date is displayed on a page lister (which is processed through relativeTimeStr function), the verbiage is in the future if it's a recently created page.  I would expect it to offset the time difference.

Is this a bug?

![timezone-issue](https://cloud.githubusercontent.com/assets/4558/26366319/83a51360-3f9f-11e7-89b4-d30e2b7a5663.jpg)

**Comment by LostKobrakai** [comment] 2017-05-23 18:10
Is the mysql timezone also set to that timezone? I had issues with that one being off and processwire doesn't really test for that.

**Comment by jlahijani** [comment] 2017-05-23 18:17
I don't see any timezone settings in my mysqld.conf file.

Furthermore, it seems MySQL is set to run off of the system timezone:

```
mysql> select @@global.time_zone;
+--------------------+
| @@global.time_zone |
+--------------------+
| SYSTEM             |
+--------------------+
1 row in set (0.01 sec)

mysql> select @@session.time_zone;
+---------------------+
| @@session.time_zone |
+---------------------+
| SYSTEM              |
+---------------------+
1 row in set (0.00 sec)
```

**Comment by ryancramerdesign** [comment] 2017-05-26 12:43
The `$config->timezone` should be set to whatever the server timezone is. Likely we'll add a separate user-specific timezone setting in the future (connected with user template), which will be useful for cases like this where you want to see dates/times in a timezone different from that of the server.

**Comment by teppokoivula** [comment] 2017-05-29 10:50
+1 for user-specific timezone. Seems like the only sensible solution for cases like these :)

**Comment by ryancramerdesign** [comment] 2017-06-23 11:36
Closing this since not a bug, but adding user-specific timezones to my todo list.

**Closed** 2017-06-23 11:38 UTC
