### ISSUE TITLE
AdminThemeUikit: AsmSelect causing fields above to resize

### ISSUE THREAD

**Issue by fijha** [processwire/processwire-issues#589] opened 2018-05-08 18:52 UTC
### Short description of the issue

AsmSelect causing fields above to resize.

### Expected behavior

Should adjust the size only for fields next to it.

**Comment by ryancramerdesign** [comment] 2018-05-10 09:34
I'm not able to duplicate any visible resizing of fields above an asmSelect. Can you provide instructions on how to duplicate?

**Comment by fijha** [comment] 2018-05-10 10:41
This is what my fields looks like:

![screenshot](https://user-images.githubusercontent.com/17672049/39865763-3f952682-544e-11e8-8851-d5469682b47d.png)

Maybe with different arrangement it doesn't happen.

**Comment by ryancramerdesign** [comment] 2018-05-10 13:06
Interesting, it looks like AdminThemeUikit/scripts/main.js thinks that the
row above it is actually part of the same row as the one the asmSelect is
on. I would guess it's not related to asmSelect, but instead asmSelect is
just what's revealing it in this case. It means that the first column in
the row likely lacks the InputfieldColumnWidthFirst class. Does your
screenshot show the entire layout, or is there anything else on either
side, like a sidebar? Also can you confirm the column width settings for
what is shown in the screenshot are 50, 25, 25, 50, 50 in that order?

**Comment by fijha** [comment] 2018-05-10 13:56
Yes, this is standard layout (no sidebar or anything). Widths are 50, 25, 25, 50, 50. **Featured** and **Author** do have `InputfieldColumnWidthFirst` class, other 3 do not, so that looks correct… probably something with `main.js`…

**Comment by fijha** [comment] 2018-05-10 23:06
It looks like UIkit issue or wrong config. It affects every column next to each other or right above that is not 100% width and stops just before a column that is 100% width. So if I make field **Finish Publishing** 100% width, or put another 100% width field in between, it works as expected.

I'm not very familiar with UIkit, but it has something to do with `uk-height-match`:

```
AdminThemeUikit/init.php (line 150)

$markup['list'] = "<ul {attrs} uk-grid uk-height-match='target: >
.Inputfield:not(.InputfieldStateCollapsed) > .InputfieldContent'>{out}</ul>";

```

I tried to remove `uk-height-match='target: > .Inputfield:not(.InputfieldStateCollapsed) > .InputfieldContent'` and it fixed the problem. But not sure if it's important. When there is a target specified it doesn't respect rows, as if there was `uk-height-match='row: false'`. Strange, maybe UIkit bug…

**Comment by matjazpotocnik** [comment] 2018-05-12 17:12
@ryancramerdesign, I didn't try the proposed solution from @fijha to fix this issue, but I remeber I had problems with height if border type is set to Card - here is link to the issue https://github.com/ryancramerdesign/AdminThemeUikit/issues/44 I can confirm that removing uk-height-match fixed it!

**Comment by fijha** [comment] 2018-05-12 17:43
Everything seems to be fine without `uk-height-match`. The field elements are using CSS Flexbox, so no need to adjust their height with JavaScript.

**Comment by fijha** [comment] 2018-06-06 19:51
So the problem lies in VersionControl module (VersionControl.css). I forgot to mention that I'm using it. When disabled, the problem is gone. And what's causing the issue is this CSS rule:

```
.overlay-parent,
.InputfieldColumnWidth {
    position: relative;
}
```

Try to add `position: relative;` to `.InputfieldColumnWidth` or `.Inputfield` and see what happens. Not sure why they can't have `position: relative;` or why it's messing up with Uikit `uk-height-match`.

**Comment by teppokoivula** [comment] 2018-06-07 09:31
Can't remember the exact reason for that style rule, but I'd assume it's added so that an overlay can be placed directly over an Inputfield. Without "position: relative" the element would stick to the nearest relatively positioned parent instead. Or perhaps it works as expected without this rule – can't say for sure without a bit of testing.

This might also be one of those things that require a theme-specific custom rule in the module CSS. Not ideal, but that's how it works when we're dealing with styles and markup that can change from theme to theme – yet we still need to inject stuff directly into the UI.

I'm currently busy with other stuff, but will try to find some time to check if (and how) VersionControl styles could be modified to avoid this issue :)

**Comment by fijha** [comment] 2018-06-07 18:21
Actually, you could try to wrap `.field-revisions` in another `div` and add `position: relative` to it. This will fix it and may not cause any other (theme) issues. But yeah, would also require you to update JavaScript files, as it could break traversing etc…

**Comment by netcarver** [comment] 2019-10-31 21:07
@fijha @teppokoivula Hey folks, am I right in thinking this is actually an issue with the version control module and not with PW? If so, perhaps Ján could open an issue on Teppo's repo and close this issue?

**Comment by netcarver** [comment] 2019-11-03 15:58
/remind me to review this issue in 1 week

**Comment by netcarver** [comment] 2019-11-10 10:10
@teppokoivula @fijha I'm closing this now as it appears to be related to the style rules in the version control module. Please post here again if you need the issue reopened.

**Closed by netcarver** 2019-11-10 10:10 UTC
Labels: status: can't reproduce, status: multiple, type: uikit
