### ISSUE TITLE
redirect to 404 after changing admin page url

### ISSUE THREAD

**Issue by VincentVanWijk** [processwire/processwire-issues#278] opened 2017-05-30 07:33 UTC
### Short description of the issue
After changing the admin url, you get redirected to the old url, that doesnt exist anymore.

### Expected behavior
Get redirected to the new admin url

### Actual behavior
Get redirected to the old admin url, that does not exist anymore.

### Steps to reproduce the issue
1. go to admin page settings
2. Change the url
3. Save
4. 404

### Setup/Environment
 multilanguage installation

* ProcessWire version: 3.061 master
* (Optional) PHP version: 5.6

**Comment by kixe** [comment] 2017-06-04 10:47
I don't agree.
To change the name of the admin page (id=2), superuser rights are required by default. So the user should know what he is doing or know he has to change the url to reach the admin area again.
I use the possibility to change the name in certain applications as an additional security measure to hide the admin area. A redirect would be totally inappropriate. [Read more ...](https://processwire.com/docs/security/admin/)
In the case of an amendment, it should be ensured that the redirect is limited to this one-time action. (Is the expenditure justified?)

This is not a problem or error and belongs (to my view) not here. This can be at most a feature request. I recommend to move this to [issue-requests](https://github.com/processwire/processwire-requests/issues)

**Comment by LostKobrakai** [comment] 2017-06-04 11:29
I do think we're just talking about the one redirect after saving the new admin page's name. I'm not sure there will be any harm to security to detect that a new name was saved and adjust the redirect url to the new location in that case (for the superuser doing the change).

If we're talking about other active users being redirected that would be a whole different story, though.

**Comment by ryancramerdesign** [comment] 2017-06-22 15:33
The URLs used by the request are set at the beginning of the request. If you change the name of the admin page, a 404 is expected. Simple to resolve–just access it at the URL you changed it to, and that's it. I also recommend logging out, and logging back in again, since some things may be cached with previous admin URLs in it.

**Comment by netcarver** [comment] 2019-02-06 17:26
@ryancramerdesign Is this a "not a bug" candidate or is there something that can be done with this issue?

**Comment by ryancramerdesign** [comment] 2019-02-07 17:10
@netcarver This is an expected behavior so I'll close it.

**Closed by ryancramerdesign** 2019-02-07 17:10 UTC
