### ISSUE TITLE
image field grid mode and size slider (ProcessWire 3.0.96)

### ISSUE THREAD

**Issue by foxwashere** [processwire/processwire-issues#545] opened 2018-03-19 22:42 UTC
### Short description of the issue

At the image field the toggle buttons for switching the grid mode and the slider for changing the image size are not working (ProcessWire 3.0.96). (Default and Uikit theme).

### Expected behavior

InputfieldImageListToggle should allow to switch between grid mode
InputfieldImageSizeSlider should allow to change the image size.

### Actual behavior

Clicking on InputfieldImageListToggle "grid" hides the image.
Clicking on InputfieldImageListToggle "left" hides the image.
Clicking on InputfieldImageListToggle "list" shows the image.
The InputfieldImageSizeSlider can not be dragged, the image size can not be changed.

### Optional: Screenshots/Links that demonstrate the issue

![type-error-ui](https://user-images.githubusercontent.com/37559204/37625676-327cdbf6-2bcd-11e8-9bf8-f32ed220a415.png)

### Optional: Suggestion for a possible fix

Will a jQuery UI Version update fix it?

### Setup/Environment

ProcessWire version: 3.0.96

Testet on a few ProcessWire 3.0.96 installations. Testet browsers: Firefox, Safari, Chromium.

* (Optional) PHP version: 
* (Optional) MySQL version: 
* (Optional) Any 3rd party modules that are installed and could be related to the issue:

Thank you!

**Comment by netcarver** [comment] 2019-02-08 19:00
@foxwashere Bumping this issue as it is quite old. Is this still an issue for you?

Has anyone else seen this happen?

**Comment by chrisbennett-Bene** [comment] 2019-02-09 02:28
I have noticed this quite regularly, including just now when I finally decided to look around for possible reasons and ended up here. I haven't been able to track down why or even when it occurs, nor is it something I can reproduce at will. Like the original post, every now and then it just doesn't work.

Generally, if I click on variations,  save the page or something like that it kicks everything back into gear and it all works perfectly again, as if something just isn't running occasionally and needs a nudge to get it going. Once it is going again it seems to keep working fine until it randomly doesn't again. Sorry, I know that is frustratingly unhelpful for troubleshooting and the next time it occurs I will check further.

**Comment by foxwashere** [comment] 2019-02-09 07:35
Hi netcarver
Yes, unfortunately it is still an issue, also in PW 3.0.123.
Thank you Chris for your post. Like you say it happens regularly. I noticed that it mostly works after a shift reload.

**Comment by chrisbennett-Bene** [comment] 2019-02-13 00:47
As promised, took a quick look when problem next occurred.
Error which was present when problem was evident and disappeared when it was working correctly was:
Uncaught TypeError: Cannot read property 'addClass' of undefined
    at e.(/cms/page/edit/anonymous function).(anonymous function)._mouseCapture (https://www.bene.net.au/wire/modules/Jquery/JqueryUI/JqueryUI.js?v=1546401829:7:28960)
    at e.(/cms/page/edit/anonymous function).(anonymous function)._mouseCapture (https://www.bene.net.au/wire/modules/Jquery/JqueryUI/JqueryUI.js?v=1546401829:6:5029)
    at e.(/cms/page/edit/anonymous function).(anonymous function)._mouseDown (https://www.bene.net.au/wire/modules/Jquery/JqueryUI/JqueryUI.js?v=1546401829:6:11521)
    at e.(/cms/page/edit/anonymous function).(anonymous function)._mouseDown (https://www.bene.net.au/wire/modules/Jquery/JqueryUI/JqueryUI.js?v=1546401829:6:5029)
    at HTMLSpanElement.<anonymous> (JqueryUI.js?v=1546401829:6)
    at HTMLSpanElement.dispatch (JqueryCore.js?v=1546401225:2)
    at HTMLSpanElement.u (JqueryCore.js?v=1546401225:2)

When the problem is occurring, this error bangs out every time you try to move the slider. 
Tried with Maximum files allowed = 1 and 0 which made no difference. As with foxwashere, also PW 3.0.123

**Comment by netcarver** [comment] 2019-02-16 19:46
Thanks @chrisbennett-Bene. Hopefully Ryan will pick this up soon.

/remind me to review this issue in 2 weeks

**Comment by ryancramerdesign** [comment] 2019-03-04 15:24
@foxwashere @chrisbennett-Bene I still cannot duplicate this issue. Probably hundreds or thousands of people are using these tools every day, so I think we have to find out what's different in your particular installations. Since it sounds like you've already tried different browsers, I think the best place to look is what other modules are installed, especially those on the "Site" tab. Can you both provide a list of what you've got and then maybe we can see what's similar between your two installations and then hopefully narrow in on something.

**Comment by foxwashere** [comment] 2019-03-06 17:48
Thank you Ryan for taking the time!
I can attach 2 screenshots of the modules installed. Under the "Site" tab there is "Database Backups".
![modules-site](https://user-images.githubusercontent.com/37559204/53901776-048dd780-4040-11e9-9ee6-0754ca00c3b9.png)
![modules-core](https://user-images.githubusercontent.com/37559204/53901784-08b9f500-4040-11e9-8c82-df06538c3c6a.png)

**Comment by ryancramerdesign** [comment] 2019-03-08 15:31
@foxwashere Thanks, I don't think it's related to any installed modules that you listed above. Since I cannot duplicate this one, I think we'll have to wait till someone else sees this one that is able to duplicate it and debug it.

**Comment by netcarver** [comment] 2019-03-08 16:49
@foxwashere Are you or @chrisbennett-Bene able to give @ryancramerdesign  access to a system displaying this issue?

**Comment by chrisbennett-Bene** [comment] 2019-03-15 03:06
Sorry all, I took a couple of weeks off and missed everything. I am more than happy to give @ryancramerdesign access if that helps track down the issue

**Comment by netcarver** [comment] 2019-03-15 09:28
@chrisbennett-Bene @ryancramerdesign Chris, is [this](https://processwire.com/talk/profile/7294-chris-bennett/) your profile on the forum? If so, I suggest you get in contact with Ryan via PM on the forum to try and arrange access.

**Comment by netcarver** [comment] 2019-04-29 19:28
@chrisbennett-Bene Chris, did you manage to get in contact with Ryan and get him access to the install that is displaying this issue?

**Comment by netcarver** [comment] 2019-10-29 19:28
@chrisbennett-Bene Chris, any update? Did you manage to PM Ryan? If not, I'm minded to close this.

**Comment by netcarver** [comment] 2019-11-03 15:50
@foxwashere As Chris seems to have gone silent on this, are you able to contact Ryan via the forum PM mechanism to allow him access to an installation exhibiting this issue?

/remind me to review this issue in 7 days

**Comment by netcarver** [comment] 2019-11-10 13:54
@foxwashere @chrisbennett-Bene I'm closing this issue now. If either of you can contact Ryan via PM on the forum to allow him to troubleshoot that would be great. Just post here again and I'll re-open this issue if needed.

**Closed by netcarver** 2019-11-10 13:54 UTC
Labels: status: can't reproduce, status: multiple
