### ISSUE TITLE
SVG not served with pagefileSecure true

### ISSUE THREAD

**Issue by noelboss** [processwire/processwire-issues#487] opened 2018-02-05 15:56 UTC
### SVG not served when pagefileSecure=true

SVG files are server by PW with content type `application/octet-stream` instead of as `'image/svg+xml'` when `$config->pagefileSecure = true;`

This is true for the backend and frontend.

### Expected behavior

SVG's should be served as content type `'image/svg+xml'`

### Actual behavior

SVG's are server with content type `application/octet-stream`

### Optional: Screenshots/Links that demonstrate the issue

![screen shot 2018-02-05 at 16 53 39](https://user-images.githubusercontent.com/114080/35813952-321e01de-0a95-11e8-9fd9-87e4ee61f461.png)

### Optional: Suggestion for a possible fix

Adding svg to the fileContentTypes array fixes the issue. But only adding an index also does not work.

```
// site/config.php
// works 
$config->fileContentTypes = array_merge($config->fileContentTypes, ['svg' => 'image/svg+xml']);

// does not work:
$config->fileContentTypes['svg'] = 'image/svg+xml';
```

### Setup/Environment
<details><summary><strong>Server Details</strong></summary>ProcessWire: 3.0.89 <br />
PHP: 7.0.17-2+deb.sury.org~trusty+1 <br />
Webserver: Apache/2.4.7 (Ubuntu) <br />
MySQL: 5.5.54-0ubuntu0.14.04.1 <br />
</details>
<details><summary><strong>Server Settings</strong></summary> allow_url_fopen: 1 <br />
max_execution_time: 120 (changeable) <br />
max_input_nesting_level: 64 <br />
max_input_time: 600 <br />
max_input_vars: 1000 <br />
memory_limit: 512M <br />
post_max_size: 500M <br />
upload_max_filesize: 300M <br />
xdebug:  <br />
xdebug.max_nesting_level:  <br />
 <br />
mod_rewrite: 1 <br />
mod_security: *confirmed off <br />
 <br />
GD: 2.2.3 <br />
GIF: 1 <br />
JPG: 1 <br />
PNG: 1 <br />
 <br />
EXIF Support: 1 <br />
FreeType: 1 <br />
Imagick Extension: 1 <br />
 <br />
</details><details><summary><strong>Module Details</strong></summary> AdminOnSteroids: 1.7.6 <br />
AdminPageFieldEditLinks: 3.1.0 <br />
CronjobDatabaseBackup: 1.1.5 <br />
FieldtypeAssistedURL: 1.0.0 <br />
FieldtypeFieldsetGroup: 0.0.2 <br />
FieldtypeFunctional: 0.0.1 <br />
FieldtypeMultiplier: 0.1.1 <br />
FieldtypeRepeaterMatrix: 0.0.4 <br />
FieldtypeRuntimeMarkup: 0.0.2 <br />
FieldtypeTable: 0.1.5 <br />
FieldtypeTextareas: 0.0.7 <br />
FrontEndEditLightbox: 1.3.6 <br />
IcfActionFieldManipulation: 0.0.1 <br />
IcfActionSendMail: 0.0.1 <br />
IcfActionTest: 0.0.1 <br />
IcfUtil: 0.0.1 <br />
IftRunner: 0.1.7 <br />
InputfieldAssistedURL: 1.0.1 <br />
InputfieldChosenSelect: 1.2.3 <br />
InputfieldChosenSelectMultiple: 1.1.9 <br />
InputfieldFunctional: 0.0.1 <br />
InputfieldMultiplier: 0.1.1 <br />
InputfieldRepeaterMatrix: 0.0.4 <br />
InputfieldRuntimeMarkup: 0.0.2 <br />
InputfieldTable: 0.1.5 <br />
InputfieldTextareas: 0.0.7 <br />
LoginRegister: 0.0.2 <br />
LoginWithEmail: 0.0.3 <br />
Oauth2Login: 0.1.0 <br />
ProcessForgotPassword: 1.0.2 <br />
ProcessIft: 0.1.6 <br />
ProcessSwitchUser: 0.0.6 <br />
ProcessTagParserTest: 1.0.0 <br />
ProcessWireUpgrade: 0.0.7 <br />
ProcessWireUpgradeCheck: 0.0.7 <br />
TextformatterMakeLinks: 1.0.0 <br />
TextformatterOEmbed: 2.0.2 <br />
TextformatterTagParser: 2.1.0 <br />
TextformatterVideoEmbedOptions: 0.3.5 <br />
TracyDebugger: 4.9.8 <br />
WireMailMandrill: 0.0.1 <br />
</details>

**Comment by ryancramerdesign** [comment] 2018-02-06 10:43
Thanks, I've pushed an update to add this to our default fileContentTypes. Note that the reason your second example didn't work is because you can't set array elements directly from the Config object like that, and instead should set them like this (as a method call): 
~~~~~
$config->fileContentTypes('svg', 'image/svg+xml'); 
~~~~~
However, the svg is now added to our default fileContentTypes so you don't have to do the above.

**Comment by noelboss** [comment] 2018-02-06 12:22
thank you @ryancramerdesign !
PS. Might there be more content types that are missing?

**Comment by ryancramerdesign** [comment] 2018-02-08 13:11
The intention is only to cover the most common content types here, and it seems like SVG belongs there, but I can't think of any others missing that are as common. This is a $config property so that people can customize it according to their needs.

**Comment by netcarver** [comment] 2018-07-25 09:40
Does Ryan's fix adequately resolve the issue for you @noelboss? (I know there are a few other pagefileSecure fixes that went in recently that might also cover this ground.) If the issue is resolved, could you please close this issue.

**Comment by netcarver** [comment] 2018-08-05 19:25
@noelboss Hello. I intend closing this issue in a week or so if I've not heard anything back from you - or anyone else - about it by then.

You can always re-open this issue later if you need to.

**Comment by noelboss** [comment] 2018-08-15 11:52
Using SVG as logos for Admin does still not work, not sure if it's related, everything else works now. Thanks!

**Comment by netcarver** [comment] 2019-02-06 10:54
@noelboss Ok, I'll update the labels to show this as still a work in progress.

**Comment by netcarver** [comment] 2019-03-22 12:47
@ryancramerdesign Bumping for your consideration. Looks like it's partially resolved.

**Comment by ryancramerdesign** [comment] 2019-03-26 10:21
@noelboss It sounds like you might be using an SVG logo that lacks width/height attributes. Open your .svg file and check the <svg> tag, it might look something like this:

`<svg role="img" viewBox="0 0 24 24" ... >`

Try adding width/height attributes to it. 50px width/height works nicely in the admin:

`<svg role="img" viewBox="0 0 24 24" width="50" height="50" ...>`

**Closed** 2019-04-29 14:40 UTC
Labels: status: work in progress

**Comment by noelboss** [comment] 2019-04-29 14:44
Thanks!
