### ISSUE TITLE
Undefined index 'code' after submitting comment

### ISSUE THREAD

**Issue by teppokoivula** [processwire/processwire-issues#971] opened 2019-09-02 13:41 UTC
### Short description of the issue

When I submit a comment form rendered with `$page->comments->renderForm()`, I'm seeing following notice:

```
Notice: Undefined index: code in /wire/modules/Fieldtype/FieldtypeComments/FieldtypeComments.module on line 661
```

### Setup/Environment

* ProcessWire version: 3.0.123
* PHP version: 7.2.21

**Comment by ryancramerdesign** [comment] 2019-09-26 18:48
@teppokoivula That indicates that the DB schema in the comments field might be old (lacking the code column) and need an update. I think it could be cleared by editing a page with a comments field and saving it? Actually, submitting a comment should have done it too. Do you still see this error if you submit another comment? Thanks.

**Comment by androbey** [comment] 2019-10-08 11:31
I can confirm the described behaviour. 
DB schema has column code, but entries are always NULL. 
Undefined index 'code' happens because `$field->schemaVersion` returns 0. [See line 189](https://github.com/processwire/processwire/blob/master/wire/modules/Fieldtype/FieldtypeComments/FieldtypeComments.module#L189).
Tested on new and existing setups on same environment as initial comment. Editing page with a comments field, editing comment field itself and submitting another comment don't help.

**Comment by ryancramerdesign** [comment] 2019-10-15 10:04
@androbey Thanks for confirming. I have a theory about what's going on. I think in your and @teppokoivula  case, the conditions where getDatabaseSchema() would run must not have occurred. That's the method that updates the schema (and schemaVersion property). I was thinking that editing the field or saving a comment would have called that method, but it looks like it doesn't unless you change a property that affects the schema. So it looks like I'll need to manually call getDatabaseSchema() in the savePageField() method, to ensure it gets called. My test installs show a schemaVersion of 6, so I'm not seeing the error here. I'm wondering if in the admin, you go to Pages > Find, and then select your comments field in filters, that should force getDatabaseSchema() to be called. If you have another chance to test, please let me know if you you continue to see the error (or not) after doing that, and that should point us in the right direction for how best to fix it.

**Comment by androbey** [comment] 2019-10-15 11:07
@ryancramerdesign I was able to briefly test the described solution. I noticed some strange behaviour, but I didn't follow it any further. 
In my test install (a regularly upgraded version of ProcessWire) I have two comments fields (one "historic" which is assigned to a template and used there for some pages and one created for testing this issue, which is not assigned to a template). 
Using finder (as described above) leads to some errors (e.g. `stripos() expects parameter 1 to be string, array given in .../wire/core/FieldSelectorInfo.php:116`) and results in an upgraded schemaVersion property for the testing field (the one which is not assigned to a template and hence not used by any pages). The historic comment field is not updated, so the error is still present.

**Comment by matjazpotocnik** [comment] 2023-07-18 17:36
@teppokoivula @androbey is this still an issue? Years have passed, and there were a lot of changes in the core.

**Comment by androbey** [comment] 2023-07-20 07:31
Sorry, I can't tell right now. Have stopped using the module because of this and never tried again.

**Comment by matjazpotocnik** [comment] 2023-07-23 04:37
Closing this now. Post more if it needs re-opening.

**Closed as completed by matjazpotocnik** 2023-07-23 04:37 UTC
