### ISSUE TITLE
Cropped image throws an exception when inserted into CKE under PHP 7.4

### ISSUE THREAD

**Issue by flipzoom** [processwire/processwire-issues#1149] opened 2020-04-16 16:20 UTC
### Short description of the issue

First of all: this error only occurs under PHP 7.4. With PHP 7.3 everything is fine. When inserting a cropped image into a CKEditor field via the image editor, an exception is thrown if Debug/Tracy is enabled. Without debug, simply no image will be inserted. However, this error only occurs with cropped images. Not with resized.

![screenshot-localhost-2020 04 16-18_13_24](https://user-images.githubusercontent.com/708183/79479936-c4a06e80-800d-11ea-8385-9a2ad54fcd86.png)

### Optional: Screenshots/Links that demonstrate the issue

Here is a screencast: 
https://github.com/FlipZoomMedia/RepoAssets/raw/master/Screencasts/screencast-localhost-2020.04.16-18_11_26.mp4

### Steps to reproduce the issue
1. Open the "Insert image" function in a CKEditor field
2. Select an image and crop it as you wish
3. Now insert the image via the button "Inser image"

### Setup/Environment
* ProcessWire version: 3.0.153 (April 16), but also with version 3.0.152
* Only with PHP version: 7.4.x
* WIN and Linux

**Comment by adrianbj** [comment] 2020-04-16 16:23
I think this is a duplicate of https://github.com/processwire/processwire-issues/issues/1086

I thought it was related to resizing, but I never saw the error myself - just my site editors, so it might be cropping.

**Comment by ryancramerdesign** [comment] 2020-05-15 15:21
I'm going to close this one because it looks like it's definitely the same thing as #1086. I had been able to duplicate and fix it. Though let me know if still observing any issue and we can can reopen.

**Closed as completed by ryancramerdesign** 2020-05-15 15:21 UTC
