### ISSUE TITLE
isset($input->post['key']) returns false even when key is present

### ISSUE THREAD

**Issue by jlj** [processwire/processwire-issues#872] opened 2019-05-08 20:34 UTC
### Short description of the issue

When a POST request can contain optional keys, using `isset($input->post['key'])` return false in processwire 3.0 when the key is present in the post data. In processwire 2.7, this expression returns true when the key is present. 

Example: processing a post that contains a 'fv'  optional key with value "2" (in the context of a module):

````php
$isPostFormatSet = isset($this->input->post['fv']) === false ? 'false' : 'non-false';
$doesPostFormatKeyExistInPost = $this->input->post->offsetExists('fv') ? 'yes' : 'no';

$log = new FileLog($this->config->paths->logs . 'debug.txt'); 
$log->save("Received  post format {$this->input->post->fv}; isset(\$this->input->post['fv']):{$isPostFormatSet}; \$this->input->post->offsetExists('fv'):{$doesPostFormatKeyExistInPost}");	
````

The resulting trace in the log file is:

````
Received  post format 2; isset($this->input->post['fv']):false; $this->input->post->offsetExists('fv'):yes
````

This issue appeared when migrating a module from 2.7 to 3.0. It impacts the following code patterns:

````php
echo $this->input->post->fv; // -> 2

$postFormat = isset($this->input->post['fv']) ? $this->input->post->fv : '1'; 
// expected $postFormat value "2"; actual value "1"

// with php 7, we have the same result if we use the coalescing operator
$postFormat = $this->input->post->fv ?? '1'; // expected value "2"; actual value "1"

if (isset($this->input->post['fv'])) {
    // This is not executed
}
````

### Notes

- Checking the presence of a key in a GET request by `isset($input->get['key'])` may present the same behavior (not tested).
- The api introduced in 3.0.125 `$input->post($key = '', $valid = null, $fallback)` is clearly a better way of dealing with optional keys, but naive code like the one above should probably still be valid.

### Setup/Environment

* ProcessWire version: 3.0.123 and 3.0.131 (but not in 2.7.2 with php 5.6)
* (Optional) PHP version: 7.3

**Comment by ryancramerdesign** [comment] 2019-06-27 11:54
@jlj I can't reproduce the issue here. Tested with both GET and POST, though both use the same class (WireInputVars) so they are identical. But here's how I tested: 
~~~~
echo isset($input->post['v']) ? 'YES' : 'NO';
~~~~
If a `v` POST var is present in input, then it outputs YES. If no `v` POST var is present then it outputs NO. 

What's different in your case is that you are preceding `$this` to your input calls. I tried that too, and all was still working. But since you are doing that, you may need to consider what class your `$this` refers to because `isset()` [I think] is going to ask that all in the chain are set in this order `$this` then `$this->input` then `$this->input->post` then finally your post variable. So if the class you are calling `$this` from does not have an `offsetExists()` that responds to `input` then presumably you could get the result you are getting. 

If the above does not point to the issue, then another thing to look for is if you've got `$config->wireInputLazy = true;` in your /site/config.php file?

Lastly, and this is besides the point, but it's also not necessary to use isset() on PW's get/post vars the way it would be on PHP's `$_POST`. In PW, when a var is not present, it simply returns NULL. So rather than using isset() you can just compare if `$input->post('v') === null` then the POST var was not present. Though if you prefer to use isset, then of course no harm in that either, but you'll just need to consider the chain of classes PHP will check as mentioned above.

**Comment by netcarver** [comment] 2019-10-29 19:13
@jlj Hello Jean-Luc, any further progress with this? Did Ryan's comment above help?

**Comment by netcarver** [comment] 2019-12-21 14:25
@jlj Jean-Luc, I'm closing this issue now. Please post again if the comment above didn't solve it for you.

**Closed as completed by netcarver** 2019-12-21 14:25 UTC
Labels: status: can't reproduce
