### ISSUE TITLE
Field admin_theme appears in template

### ISSUE THREAD

**Issue by beatep** [processwire/processwire-issues#450] opened 2017-12-08 14:38 UTC
### Short description of the issue

I just used 3.0.84 for creating a template and in the basic tab there is the field admin_theme:

### Optional: Screenshots/Links that demonstrate the issue

![admin_theme](https://user-images.githubusercontent.com/1794446/33770412-bedfc31e-dc2d-11e7-95b4-e79cc2dc3432.png)

Is this a bug?

**Comment by ryancramerdesign** [comment] 2017-12-11 11:02
Not a bug. Fields that have the system flag but lack the permanent flag are intentionally included in this list, and identified with the asterisk appended to them. Though I understand, the admin_theme field probably isn't going to be needed unless you plan to create alternate user templates. Maybe in the future we'll add another status to support that type of exclusion, but for now, it is expected that admin_theme and email would appear in this list.

**Comment by netcarver** [comment] 2018-07-29 11:14
@beatep Hi Beate, I know this is an older issue, but if Ryan's comment has resolved this to your satisfaction, please would you consider closing this issue? If not, feel free to post about this again here, or maybe opening a feature-request for a way to exclude fields from the field-selector in the template editor might be one way to approach this (or asking in the forum in case anyone has a hook solution.)

Thanks for considering!

**Closed** 2018-07-30 09:53 UTC
Labels: resolution: not a bug, type: filtering, type: templates
