### ISSUE TITLE
Options field - setting a value via API won't work with option value containing hyphen

### ISSUE THREAD

**Issue by sjardim** [processwire/processwire-issues#193] opened 2017-02-21 18:49 UTC
### Short description of the issue

I tried to add an option to a page using the API on a **MultiSelect Option Field**, but when the option has a hyphen, like in _'game-theory'_, ProcessWire appears to ignore it. 

### Expected behavior

My option field 'Book Shelves' has values like these:
1=advanced|Advanced
2=game-theory|Game Theory

So, running:

`$page->book_shelves = array('advanced', 'game-theory');`

`$page->book_shelves` should have now both options selected.

### Actual behavior

`$page->book_shelves` has ONLY the option`'advanced'` selected.

### Workaround

I replaced the hyphens and capitalized the first character so ProcessWire could match the options title and it worked. 

`$s = array();`
`foreach($shelves as $shelf) { //game-theory`  
`    $shelf = str_replace("-"," ",$shelf); //game theory`
`    $s[] = ucwords($shelf); //Game Theory`
`}`
`$page->book_shelves = $s;`
`$page->save();`

### Setup/Environment

* ProcessWire version: 3.0.52
* (Optional) PHP version: 7.1.0
* (Optional) MySQL version: 10.1.19-MariaDB Homebrew

**Comment by kixe** [comment] 2017-02-23 07:49
I use this field with similar settings.
```
1=de|Germany
2=ch|Switzerland
3=fr-fr|France
4=at|Austria
```
Changing values via API works without problems. I couldn't reproduce the issue.
How do you determine the issue?

**Could you please check the following:**
+ Are the values set in the database?
+ Can you see the changings in the backend?

**Could you give more information:**
+ about field settings (Inputfieldtype, default value etc.)
+ how you determine the issue?

**Comment by netcarver** [comment] 2019-02-06 13:49
@sjardim Hi Sérgio, could you please provide the requested information to allow Ryan to progress this issue. Thank you!

**Comment by sjardim** [comment] 2019-02-28 17:15
> @sjardim Hi Sérgio, could you please provide the requested information to allow Ryan to progress this issue. Thank you!

Hi @netcarver, we can disregard this issue I suppose. I cannot work on it any further at the moment and @kixe couldn't reproduce it, so I think it was a problem in my code. :)

**Comment by netcarver** [comment] 2019-02-28 19:23
@sjardim Thanks Sérgio, closing.

**Closed by netcarver** 2019-02-28 19:23 UTC
Labels: status: needs more information
