### ISSUE TITLE
Adding users is not possible from the page tree, top navigation link still works.

### ISSUE THREAD

**Issue by solonmedia** [processwire/processwire-issues#1279] opened 2020-11-13 14:19 UTC
### Short description of the issue

When adding a user from the top menu, the input template only shows a Name field and the user is added successfully.

When adding a user from the Pages > Home > Admin > Access > Users > New pathway, the input template shows a template selection field, a name field and a url field. When submitting this form, I get a 404 error and the URL follows the pattern:

    {domain.com}/processwire/access/users/edit/bookmarks/bookmarks/bookmarks/bookmarks/

I've tried removing site modules and get the same result. It is possible to add users without going this route, but I had a customer think the site was broken because she couldn't add users from the page tree.

### Expected behavior

Both methods of adding a user (from the top menu and the page tree) should be identical.

### Actual behavior

The two methods are not identical and one works properly while the other does not.

### Setup/Environment

* ProcessWire version: 3.0.168

**Comment by ryancramerdesign** [comment] 2020-11-13 16:57
Closing, appears to be duplicate of #1278

**Closed as completed by ryancramerdesign** 2020-11-13 16:57 UTC
