### ISSUE TITLE
$sanitizer->options($input->post("field"), $array) throws an error

### ISSUE THREAD

**Issue by cb2004** [processwire/processwire-issues#93] opened 2016-11-23 15:15 UTC
### Short description of the issue

Within a form I am building $sanitizer->options($input->post("field"), $array) throws an error before there is any submitting of the form, if the form has been submitted it functions as I would expect.

### Expected behavior

The same as $sanitizer->option($input->post("field"), $array)

### Actual behavior

Error: Uncaught TypeError: Argument 1 passed to ProcessWire\Sanitizer::options() must be of the type array, null given, called in C:\Users\COMPUTER\Desktop\OneDrive\Work\Websites\WEBSITE\site\assets\cache\FileCompiler\site\templates\views\forms\volunteers.php on line 8 and defined in C:\Users\COMPUTER\Desktop\OneDrive\Work\Websites\WEBSITE\wire\core\Sanitizer.php:2259

### Optional: Screenshots/Links that demonstrate the issue

Your screenshots/links go here.

### Optional: Suggestion for a possible fix

Your possible fix goes here.

### Steps to reproduce the issue

```
$form = array(
	"field" => $sanitizer->options($input->post("field"), $array)
);
```

### Setup/Environment

* ProcessWire version: 3.0.41
* (Optional) PHP version: 
* (Optional) MySQL version: 
* (Optional) Any 3rd party modules that are installed and could be related to the issue:

**Comment by adrianbj** [comment] 2016-11-23 15:36
@cb2004 - that's not a bug with the options sanitizer method. Until you "post" field, it will be null. 

You could check to see that it exists before running the sanitizer on it. What is your goal for using the options sanitizer before submitting the form?

**Comment by cb2004** [comment] 2016-11-23 16:24
I dont need to sanitize before, I have just been using code from here for years:

https://processwire.com/talk/topic/407-processing-contact-forms/#comment-3208

I was just trying to sanitize my checkboxes so I will look for another way.

Cheers.

**Comment by ryancramerdesign** [comment] 2016-11-30 19:52
The `options` (plural) method requires 2 arrays. If you don't know if the first value is an array, one thing you could do would be to force the value as an array 
~~~~~
$form = array(
	"field" => $sanitizer->options($input->post->array("field"), $array)
);
~~~~~
I'll close this one since the behavior is correct, but let me know if you have any more questions.

**Closed by ryancramerdesign** 2016-11-30 19:52 UTC
