### ISSUE TITLE
Page parents not correctly updating (which affects has_parent)

### ISSUE THREAD

**Issue by jlahijani** [processwire/processwire-issues#136] opened 2016-12-28 16:47 UTC
Please view video:
https://youtu.be/BY0VXhKi2KM

**Comment by LostKobrakai** [comment] 2016-12-28 17:02
At least here you should be able to use the mysql snippet I posted over here until the issue is found: https://github.com/processwire/processwire-issues/issues/118

**Comment by ryancramerdesign** [comment] 2017-01-02 12:55
I think very likely this is a result of the same issue as the other issue you reported that caused the page not to be restored when dragging out of the trash. That's because the issue was caused by a certain parent change that didn't trigger a change event the way it should, so the pages.save() call didn't see it, and thus no pages_parents update would occur. If you still have that test profile used in your video handy, please let me know if you continue to experience it in 3.0.47, as I think the issue is likely already fixed.

**Comment by ryancramerdesign** [comment] 2017-02-03 11:12
Closing because I think this one is fixed, but please re-open if you find otherwise.

**Closed by ryancramerdesign** 2017-02-03 11:12 UTC
Labels: resolution: fixed (close when ready)
