### ISSUE TITLE
Limited Admin - Page Tree Inconsistencies and Exception

### ISSUE THREAD

**Issue by zoaked** [processwire/processwire-issues#350] opened 2017-08-19 17:37 UTC
### Short description of the issue
We are creating a limited admin user that can only see areas of the site that they have been given access to. 

There are several related issues: (all referenced screenshots are shown in the screenshots section below)

1. In the limited screenshot, the number of children under home is shown as 2 even though only one is shown (to be clear, the second item should be missing and it is the count that is the issue - see next bullet for more info)
1. In the limited navbar screenshot, the 404 error page is being shown even though the hidden property is checked on the page settings (I believe this is the item that was being counted, but not shown, in the previous bullet)
1. Also in the limited navbar screenshot, the 'Data' page is visually leaking information that there are children available under it (and the number of children) even though this user does not have access to any of them (as shown in the screenshot, no sub-menu appears)
1. The 'Data' page is strictly for structural purposes and does not have a template associated with it.  The limited user has permission to see this page, but not to edit it.  As a result of there being no template the page cannot be viewed on the front-end.  In the menu the page can still be clicked on which causes an exception to be thrown. 

### Expected behavior

1. The number shown accurately reflects the number of children available
1. Hidden pages are, well, hidden (doesn't show up in the navbar)
1. Number of children matches the number of items that get shown and sub-menus are only offered when a user has access to at least one child
1. The element representing the parent page would not be a link or link would take no action since the page is neither viewable nor editable

### Actual behavior

Actual behavior has been described in short description and/or shown in screenshots below

### Optional: Screenshots/Links that demonstrate the issue

See screenshots of what the superuser sees on the page list:
![superuser](https://user-images.githubusercontent.com/10800710/29488629-e3af6364-84dc-11e7-9f56-42b463b79b13.PNG)
![superuser-navbar](https://user-images.githubusercontent.com/10800710/29488632-e3b0ec02-84dc-11e7-916a-2c80291a117d.PNG)

and here is the same view when the limited admin is logged in:
![limited](https://user-images.githubusercontent.com/10800710/29488628-e3aa4e06-84dc-11e7-86eb-b335c471f085.PNG)
![limited-navbar](https://user-images.githubusercontent.com/10800710/29488630-e3b09716-84dc-11e7-929e-4c7b67146e14.png)

Exception that is thrown when clicking on the 'Data' page in the nav bar:
![limited-error](https://user-images.githubusercontent.com/10800710/29488631-e3b0e7c0-84dc-11e7-9f3a-22b8a23ccb9c.PNG)

### Steps to reproduce the issue

1. Create a new role and give it page edit and manage users permissions
1. Create a new template called 'data' that have no corresponding template file.  Under the access settings, give guest view access. All other permissions should be removed.  Under family settings, the new pages option should be set to only one.
1. Create a new template that has no corresponding template file.  Allow this template to be a child of the data template.  Under the access settings pick one role to have view and edit access. (not the new role)  All other permissions should be removed. (including guest)  Under the family settings, the child pages option should be set to no.
1. Create a new page for 'Data' that uses the data template
1. Create one or more child pages under it using the other template.
1. Create a new user and assign them to the newly created role, but NOT to the one that has view/edit permissions on the child template.
1. Login as newly created user

### Setup/Environment

* ProcessWire version: 3.0.62
* (Optional) PHP version: 7.1
* (Optional) MySQL version: mysql Ver 14.14 Distrib 5.7.16
* (Optional) Any 3rd party modules that are installed and could be related to the issue:

**Comment by netcarver** [comment] 2018-08-01 22:42
@Toutouwai - Robin, I see you gave this a tumbs-up emoji - does this issue effect you too?
@zoaked - Is this still an issue with the latest dev version?

**Comment by netcarver** [comment] 2018-08-01 22:43
@zoaked Is this still an issue in the latest dev version?
@Toutouwai. Robin, I see you gave this a thumbs-up emoji - does it effect you too?

**Comment by Toutouwai** [comment] 2018-08-01 23:06
@netcarver, there are a few different things described in this issue. I haven't experienced all of them, but the part I was giving the thumbs up to was the incorrect child count in Page List. I have experienced that when using hooks to limit page visibility but originally raised that as a [feature request](https://github.com/processwire/processwire-requests/issues/194) rather than an issue seeing as I was going beyond the core features.

But since I discovered the child count is incorrect for non-superusers even on a clean PW installation with no custom hooks I have opened a separate issue for that: https://github.com/processwire/processwire-issues/issues/649

**Comment by ryancramerdesign** [comment] 2019-04-05 13:02
I think all of these except item 2 have already been resolved in other individual issue reports. Item 2 is an intended behavior (hidden status does not affect visibility in admin page list). I will close this for now, but please feel free to re-open in new issue report if any related issues turn up. Thanks.

**Closed by ryancramerdesign** 2019-04-05 13:02 UTC
Labels: status: impacts multiple users
