### ISSUE TITLE
No unit tests?

### ISSUE THREAD

**Issue by nicdavies** [processwire/processwire-issues#822] opened 2019-02-28 13:10 UTC
### Short description of the issue
As far as I can tell, there's absolutely no unit tests? Why? There really should be some unit tests in the core.

### Expected behavior
n/a

### Actual behavior
n/a

### Optional: Screenshots/Links that demonstrate the issue
n/a

### Optional: Suggestion for a possible fix
Install phpunit using composer (composer req phpunit/phpunit --dev) and set up a phpunit.xml.dist file in the root.

### Steps to reproduce the issue
n/a

### Setup/Environment
n/a

**Comment by teppokoivula** [comment] 2019-03-01 09:05
This would be better suited for the [processwire-requests](https://github.com/processwire/processwire-requests) repository. I would recommend closing this issue and reopening it there.

While I agree that we should have tests for core code (unit test, integration tests, whatever combination makes most sense) and firmly believe it would make ProcessWire more robust and less error prone on updates (Ryan is awesome, but human errors do still happen), having unit tests is not a bug/issue in itself :)

**Closed as completed** 2019-03-01 09:20 UTC
