### ISSUE TITLE
Mismatch of declaration of User::editUrl() & Page::editUrl($options = Array) 

### ISSUE THREAD

**Issue by anilex** [processwire/processwire-issues#131] opened 2016-12-23 22:12 UTC
### Short description of the issue

When updated to the latest dev (v3.0.46) and logged in to the admin area the error occurred.  

### Expected behavior

To use the admin area as usual.  

### Actual behavior

The error occured: on top of any other UI (nav, upgrade messages, etc) 
```
Warning: Declaration of ProcessWire\User::editUrl() should be compatible with ProcessWire\Page::editUrl($options = Array) in /Users/{my_user}/Sites/{project_name}/_site/app/wire/core/User.php on line 479
```

### Optional: Suggestion for a possible fix

Add $options = array() to  #User::editUrl() class. 

### Setup/Environment

* ProcessWire version: dev 3.0.46
* (Optional) PHP version: 7.0.11 (php error reporting to E_ALL)

**Comment by adrianbj** [comment] 2016-12-23 22:14
Duplicate of https://github.com/processwire/processwire-issues/issues/130

**Comment by ryancramerdesign** [comment] 2016-12-25 12:45
Thanks I've pushed a fix.

**Closed by ryancramerdesign** 2016-12-25 12:45 UTC
