### ISSUE TITLE
findJoin() failing to explode non-autojoin multiValue fields

### ISSUE THREAD

**Issue by netcarver** [processwire/processwire-issues#1649] opened 2022-11-25 19:56 UTC
### Short description of the issue

Following on from Adrian Jones' report in the forum [here](https://processwire.com/talk/topic/25088-pw-30172-%E2%80%93-find-faster-and-more-efficiently/?do=findComment&comment=228604), the results of findJoin() fail to explode multivalue fields unless they have the autojoin property set on them - which is probably unlikely as we'd not need to call findJoin() in these cases anyway.

### Expected behavior

Any multivalue fields passed in as join arguments should be correctly exploded in the result of the call to `findJoin()`

### Actual behavior

Any joined multivalue fields are returned as unexploded strings with embedded null-bytes.

### Location of issue

I've tracked this down to the following block of code - which skips the explode of multivalue fields unless it has the autojoin property/field set on it.

```php
            // check for autojoin multi fields, which may have multiple values bundled into one string
            // as a result of an sql group_concat() function
            if($field->type instanceof FieldtypeMulti && ($field->flags & Field::flagAutojoin)) {
                foreach($value as $k => $v) {
                    if(is_string($v) && strpos($v, FieldtypeMulti::multiValueSeparator) !== false) {
```

https://github.com/processwire/processwire/blob/9bb9d717297fc949b2a8ce60de413625ec35ee64/wire/core/PageValues.php#L734-L742

### Suggestion for a possible fix

Not sure of the best way to tackle this. I think one way would be to simply ditch the check for the autojoin property and always explode multivalue fields if the joiner is present in the string. Removing the check for the Field::flagAutojoin restores the output to the expected value but may introduce inefficiencies as all FieldtypeMulti fields will lead to the contained `foreach()` being run.

### Steps to reproduce the issue + Screenshots

1. Create a multivalue page reference field, say 'widgets' ensure that the autojoin property is not set. (You'll need to create a small set of pages to point the widgets page reference field to.
2. Add widgets to a template, say 'factory', and create and populate a page using that template.
3. In tracy's code panel run `d($pages->findJoin('template=factory', 'widgets'));`
4. Expect a page array with one entry for the factory page (more if you created more) with each page having the widgets field being an array of values.
5. Actually get a result where the widgets field is a string with embedded null bytes separating each widget id.

Expected result pattern (array of IDs)
![image thumb png a5ea487fbcde8281a53444c38fd9a94a](https://user-images.githubusercontent.com/16049/204049543-eb991adf-5ef8-4db6-a11f-ee02c41253cb.png)

Actual result pattern (string)
![image thumb png f4e7ff95e7048a056cc076d34c654f9e](https://user-images.githubusercontent.com/16049/204049557-00699d69-3e38-49eb-9e61-b770cef4bad3.png)

### Setup/Environment

|Software|Version|
|------:|:-------|
|ProcessWire|3.0.207|
|PHP|8.0.24|
|Webserver|Apache/2.4.54 (Debian)|
|MySQL Server|8.0.26-0ubuntu0.20.04.3|
|MySQL Client|mysqlnd 8.0.24|

**Comment by adrianbj** [comment] 2022-11-25 23:08
@ryancramerdesign - to expand on @netcarver's report, there is also an issue with replication of page IDs in the string, eg:

<img width="1241" alt="image" src="https://user-images.githubusercontent.com/871211/204061887-6f43dd9f-117d-4544-a2eb-7fb5fe17117c.png">

But note that this only happens when there is more than one PR field in the fields list. This example shows two PR fields, but if I add a third one, it runs until timeout, presumably because there is some additive or multiplicative effect going on.

This should probably be a new issue, because even if I remove the ` && ($field->flags & Field::flagAutojoin`, the array is still populated with all these replicate page IDs.

**Comment by ryancramerdesign** [comment] 2022-12-02 15:50
@netcarver @adrianbj Thanks, I've pushed a fix for this. Can you confirm it also fixes it there?

Also want to mention it's usually not worthwhile to autojoin multi-value fields, unless there's only one being joined and the quantity of values in it is very small (like less than 10). I think for most cases a multi-value field being autojoined may even add overhead. As a result, I rarely use autojoin with multi-value.

**Comment by adrianbj** [comment] 2022-12-03 23:22
Thanks @ryancramerdesign - I can confirm that the fix is working. 

I agree about the speed with these - I found that when testing but still wanted to mention this as a bug that needed fixing.

**Comment by adrianbj** [comment] 2022-12-03 23:23
PS - for some reason I don't have permission to close this issue - @netcarver - do you know if some setting has been changed?

**Comment by matjazpotocnik** [comment] 2022-12-04 17:22
Adrian, Steve opened this issue, and he can close it. Let's wait for him.

**Comment by adrianbj** [comment] 2022-12-04 17:59
@matjazpotocnik - so he did :)

**Comment by netcarver** [comment] 2022-12-08 11:34
Thank you everyone!

**Closed as completed** 2022-12-08 11:34 UTC
Labels: status: fixed-please confirm
