### ISSUE TITLE
File compiler adding \ProcessWire to strings with parentheses that look like PW methods.

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-issues#98] opened 2016-11-28 17:50 UTC
### Short description of the issue

The compiler is targeting what it thinks are methods in strings when it sees parentheses.

### Expected behavior

It should leave content inside strings alone.

### Actual behavior

```
$str = ' page(s)';
```
results in: 

> \ProcessWire\page(s)

I wonder if perhaps the file compiler could benefit from `token_get_all()` to exclude comments, variables, etc. I have found it very useful in the past for parsing PHP files.

**Comment by ryancramerdesign** [comment] 2016-12-01 16:31
I don't currently have a way to differentiate a function call that appears in a string vs. one that's outside of it. Further, there are cases where it does need to convert from within strings, like class references. The FileCompiler is meant to accommodate most situations, but there are always going to be exceptions, so this is one of them. Though I'm tempted to have the FileCompiler ignore functions added by the $config->useFunctionsAPI since they are maybe too common, as is the case with the one you found via page(s). I'm interested in learning more about what you suggest for the token_get_all() method – I've not used that one before. Can you tell me more about how you think it might help for this case? Thanks.

**Comment by adrianbj** [comment] 2016-12-01 19:43
> I'm tempted to have the FileCompiler ignore functions added by the $config->useFunctionsAPI since they are maybe too common

I do think it will come up a lot, although not compiling when valid will also be problematic, so maybe it needs to be clear not to use those unless you are declaring the PW namespace.

I know, it's complicated for you to get right, but I think that `token_get_all` could make it easier :)

It lets you do stuff like this:
```
$tokens = token_get_all($fileContent);
foreach($tokens as $token) {
    if($token[0] == T_COMMENT || $token[0] == T_DOC_COMMENT) {
		// don't compile comments
	}
	else {
		compile($token[1]);
	}
}
```
so you can apply different logic depending on what type of content you are dealing with.  

Here is a list of the types of tokens it will identify: http://php.net/manual/en/tokens.php

In particular, you might find these ones useful:
```
T_COMMENT
T_DOC_COMMENT
T_INCLUDE
T_INCLUDE_ONCE
T_REQUIRE
T_REQUIRE_ONCE
T_STRING
T_CLASS
T_VAR
T_VARIABLE
```

Hope that might prove useful, although it may require a significant overhaul of the compiler.

**Comment by ryancramerdesign** [comment] 2016-12-02 15:54
I've taken a closer look at token_get_all. Ultimately FileCompiler has to do string replacement on the source file, rewriting the parts that need it, and leaving everything else alone. The token_get_all looks handy for analysis, but it's not going to help with most of what FileCompiler must do. Still for the analysis part, I think it actually may help, since FileCompiler doesn't do a lot of that at present. For instance, in collecting what function calls and classes are referenced, we can avoid compiling something like `page(s)` if token_get_all doesn't indicate `page` as one of the function calls that's used in the code. It could be similarly helpful with require/include statements. I'd use token_get_all to build a whitelist of what's used before compiling starts, and then skip over compiling things that aren't in the whitelist. Granted there could still be situations where it could compile something that doesn't need it, but using token_get_all would potentially really help to reduce the situations where that occurs.

**Comment by jlahijani** [comment] 2017-01-04 00:53
I just experienced a similar issue with the word 'include'.  Using PW 3.0.47.

In my template, I have some general text like:
To include the shipping cost in your quote, please complete the 'Estimate Shipping' box above.

It transforms it to:
To include(\ProcessWire\wire('files')->compile(the shipping cost in your quote,array('includes'=>true,'namespace'=>true,'modules'=>true,'skipIfNamespace'=>false)), please complete the 'Estimate Shipping' box above.)

Let me know if you are able to replicate this or need further info.

**Comment by ryancramerdesign** [comment] 2017-01-04 18:13
@jlahijani  I couldn't duplicate it until I used the exact sentence that you used, then I could. A combination of factors in that sentence made FileCompiler misidentify it. Whereas other sentences using the word "include" weren't affected. I've gone ahead and pushed quite a few updates to FileCompiler that should fix both of the cases mentioned in this issue report (yours and @adrianbj). There are still cases where it could get caught though (and likely always will be), but hopefully this should significantly reduce them. Hopefully I didn't add many new bugs with all these changes, but please let me know if you run into any. 

Btw I did experiment with the token_get_all() per the earlier mention, as I thought it might be helpful for some of the identification stuff. What I found is that token_get_all() doesn't recognize things properly if they aren't in the namespace... meaning token_get_all() won't properly identify everything until after FileCompiler has compiled the file to put things in the right namespace. :) So I wasn't able to find a good use for it in FileCompiler, but I did end up using the using some ideas that were planned from that approach, so it was a helpful suggestion either way.

**Comment by adrianbj** [comment] 2017-03-01 17:46
Another situation. 
This:
```
the debug bar is displayed for authorized users (superusers and those with the "tracy-debugger" permission)
```
is turned into:
```
the debug bar is displayed for authorized \ProcessWire\users(superusers and those with the "tracy-debugger" permission)
```

**Comment by netcarver** [comment] 2018-07-27 11:09
@adrianbj Hi Adrian, looks like Ryan pushed a code change following your comment and reopening of this issue. Can this be closed now?

**Comment by adrianbj** [comment] 2018-07-27 12:06
@netcarver - unless I am mistaken, that code commit after I reopened is @foobarlab pulling in @ryancramerdesign 's change which is dated Jan 4 which is well before I reopened this.

The issue noted in my last comment is still valid and I end up having to use a `&nbsp;` before parentheses in these situations as a hacky workaround.

**Comment by gmclelland** [comment] 2018-07-27 15:57
Ya, I'm still seeing a similar issue with this https://github.com/wanze/TemplateEngineTwig/issues/14 even in PW 3.0.108.  It's strange sometimes I can edit a file to trigger the file compiler and the site will display correctly.  On some sites it displays correctly and others it doesn't.

Here is the code that displays incorrectly
```php
// from TemplateEngineTwig.module
        $f = $modules->get('InputfieldCheckbox');
        $f->label = __("Auto reload templates (recompile)");
        $f->description = __('If enabled, templates are recompiled whenever the source code changes');
        $f->name = 'auto_reload';
        if ($data['auto_reload']) $f->checked = 1;
        $wrapper->append($f);
```
Here is what it looks like:
![errors](https://user-images.githubusercontent.com/40570/43331503-aebb98a0-918b-11e8-9e43-92a970a421dc.jpg)

**Comment by netcarver** [comment] 2018-07-27 16:52
@adrianbj Sorry, my mistake - I'll be more careful about looking at the commits!

**Comment by adrianbj** [comment] 2018-07-27 22:03
All good :)

**Comment by netcarver** [comment] 2019-02-06 22:02
This is an old issue now - with 8 months since last post. Still active? @adrianbj @gmclelland

**Comment by adrianbj** [comment] 2019-02-06 22:11
Hi @netcarver - it's definitely still an issue and bites me quite regularly :)

**Comment by ryancramerdesign** [comment] 2019-02-07 15:44
I think it's okay to close this issue. If this was a simple fix I'd have done it by now, but it's not. And even if there was a simple fix, there's a high probability of it causing other issues. The compilation process is far from a perfect science, so it's always been a matter of finding the balance that prevents the most fatal errors, which I think FileCompiler has effectively done. I run into the mentioned issue sometimes too, but it's a minor visual annoyance. 

FileCompiler exists mostly to get people from PW2 to PW3. If it's a big concern, I think it's fine to drop PW2 compatibility from modules so that the FileCompiler isn't even necessary. I've been dropping PW2 compatibility in newer versions of my modules at least. Unless some security related issues comes along, there are not likely to be more updates to FileCompiler at this stage, since most have moved to PW3 and namespaces by now, and FileCompiler hasn't been adopted for much else beyond that.

**Comment by teppokoivula** [comment] 2019-02-07 18:33
I'm with Ryan on this one: in my opinion any work put towards resolving FileCompiler issues is (mostly) wasted effort at this point. I'd also like to go one step further and suggest that we decide an EOL date – or version? – for this sort of native FileCompiler behaviour.

Basically the only thing I've been wondering is whether it would be somehow possible to avoid having to place "namespace ProcessWire" in regular template files. For me that's a real nuisance, particularly since I tend to split "code" from "view files"... and having a namespace declaration in otherwise clean view scripts annoys the heck out of me :)

Anyway, If we want to be nice to end users, getting rid of FileCompiler would require a new major version. When updating anything from one major version to another one should be prepared for some backwards incompatible changes.

**Comment by adrianbj** [comment] 2019-02-07 18:39
Yeah, I don't expect it to be fixed at this stage and I agree with @teppokoivula that the file compiler should be phased out pretty soon. I know there must be a reason why it doesn't work so I am about to feel silly, but why couldn't the file compiler just prepend the PW namespace to the top of the file and that's it?

**Comment by teppokoivula** [comment] 2019-02-07 18:59
There may be other (more valid) reasons, but I'd imagine non-namespaced files with unrelated code being at least one potential issue. Since PHP falls back to the global namespace in most cases that probably shouldn't be a huge issue, but performance-wise it would of course be less than ideal.

I'm probably missing something important here, so hopefully someone can explain this further :)

**Comment by adrianbj** [comment] 2019-02-07 19:04
I guess I was thinking it could just do this for template files and nothing else?

**Comment by teppokoivula** [comment] 2019-02-08 06:56
Right. The problem is that the only way to reliably tell if a file is a "template file" is to see if it's attached to a ProcessWire template directly, and this leaves out all files that are included or used in some other way.

In my use case it would literally do nothing since typically all requests are routed through single backend endpoint (front controller in my workflow). admittedly my use case is rather atypical, but the include issue is still problematic :)

**Comment by netcarver** [comment] 2019-02-16 20:04
@teppokoivula @adrianbj @ryancramerdesign @gmclelland @jlahijani I intend to close this issue in a week unless Adrian closes it first, or someone has a further view they'd like to voice that argues for keeping it open.

I note there are a couple of other file compiler issues that are live.

/remind me to review this issue in 1 week

**Comment by adrianbj** [comment] 2019-02-16 20:14
I've learned to live with it so I don't mind if it's closed at this point.

**Comment by postscript-chris** [comment] 2019-02-27 09:46
@netcarver looks like @adrianbj closed this issue and the bot reopens them

**Comment by ryancramerdesign** [comment] 2019-02-28 15:07
Closing because @reminders reopened it and I don't think it was supposed to

**Closed by ryancramerdesign** 2019-02-28 15:07 UTC
Labels: status: discussion, type: file compiler
