### ISSUE TITLE
frontend editing not working with markup regions

### ISSUE THREAD

**Issue by BernhardBaumrock** [processwire/processwire-issues#294] opened 2017-06-18 13:37 UTC
### Short description of the issue

i just wanted to switch my logic from a simple site to markup regions. i only have one main content region.

### Expected behavior

it should be possible to use frontend editing together with markup regions.

### Actual behavior

when i moved my main content div from _main.php to home.php all the field contents disappeared.

### Steps to reproduce the issue

1. create a pw install (intermediate profile)
1. create a html skeleton in _main.php
1. create a region in this file eg. <region id="content"><?= $page->body ?></region>
you should see the body content
1. enable frontend editing for this field
1. everything should work
1. move this field to home.php, eg. <region id="content"><?= $page->body ?></region>
the content will be empty (i tried both $page->edit(true) and $page->edit('body')   )

### Setup/Environment

* ProcessWire version: 3.0.64
* (Optional) PHP version: 7

**Comment by AndZyk** [comment] 2017-06-18 20:04
Hello Bernhard,

I can confirm this issue and switched therefore to [Option C](https://processwire.com/blog/posts/front-end-editing-now-in-processwire-3.0-alpha-4/#option-c-html-edit-tags) in my templates.

Regards, Andreas

**Comment by BernhardBaumrock** [comment] 2017-06-18 20:16
I switched to delayed output for the time.

**Comment by AndZyk** [comment] 2017-06-18 20:29
Option C has also the advantage to [enable front-end editing for repeater items](https://processwire.com/talk/topic/15357-solved-frontend-edit-on-repeater-fields/?do=findComment&comment=138551). But everybody should be able to use whatever Option they prefer, so I hope this issue will be solved. ;-)

**Comment by ryancramerdesign** [comment] 2017-06-21 10:56
I think the problem is likely markup regions confusing some of the "pw-" classes that are used in the front-end editor markup. I've fixed the issue locally for another case, but think it will likely correct this issue too. This will be in 3.0.65. Thanks.

**Comment by ryancramerdesign** [comment] 2017-06-22 12:48
The commit referenced above is likely to fix this issue, though haven't yet tested to be sure. If you are able to test, please let me know what you find. If it doesn't appear to fix the issue at first, try updating your /site/config.php file to set `$config->useMarkupRegions = 2;` to force it to use the newer markup regions spec (which no longer uses class attributes for region actions).

**Closed** 2018-03-16 14:38 UTC
Labels: status: fixed (please confirm)
