### ISSUE TITLE
Possible to login in without Tfa code

### ISSUE THREAD

**Issue by snobjorn** [processwire/processwire-issues#1376] opened 2021-05-05 07:12 UTC
### Short description of the issue

In ProcessWire, I have set TFA for ProcessLogin as Required. Using TfaEmail. When creating a new user, I set the new user to use TfaEmail and Save. But I do not type in the Tfa code that ProcessWire asks for to confirm the setup. This then makes it possible for the user to login in without using TFA, even though it is set as required for all users.

### Expected behavior

I expect the user not to be able to login until the TFA code is confirmed in the dashboard. Or confirmed for the user through email or in some other way. I expect my users never to be able to login without using a TFA code.

### Actual behavior

The user can log in without the TFA code confirmed in the dashboard. Meaning, the user can login without using a TFA code at all.

### Steps to reproduce the issue

1. Set TFA to be required for all users in ProcessLogin
2. Create new user
3. Set the user to use TfaEmail, then save
4. Do not type in confirmation code.
5. Let the user log in with username and password

* ProcessWire version: 3.0.175 dev
* Any 3rd party modules that are installed and could be related to the issue: TfaEmail, TfaTotp

**Comment by ryancramerdesign** [comment] 2021-05-05 14:42
@snobjorn You cannot enable TFA for someone else in that manner, as there's no way you can confirm it since you don't have access to their email address. 

If you want to force use of TFA through email then you'll want to go to Modules > Configure > ProcessLogin. Check the box to force TFA using the TfaEmail module. Save.

**Comment by snobjorn** [comment] 2021-05-06 06:02
@ryancramerdesign It might be that way it should be used. But the admins of the page has found a way around. They use a temporary email adress to activate TFA. Then afterwards they change it to be the user's email address. In that way they have found that they can confirm TFA for someone else.

But it could as well have been that an admin were making himself a second account. He was able to avoid confirming the TFA code for this new account, just by closing the new user creation process before the confirmation. Even if TFA using TfaEmail was forced (through ProcessLogin, as per step 1).

I get how it has been intended to be used, but I am mostly questioning the way an admin was able to create and login with a new account, without using TFA. When TFA has been set to force in the settings.

**Comment by ryancramerdesign** [comment] 2021-05-07 13:07
@snobjorn A superuser or user with user-admin permission has the ability to do pretty much whatever they please when it comes to users, consistent with their access level. If administrators are creating accounts for themselves to bypass TFA then they probably should not be trusted as an administrator. :) The forced TFA (supported only by TfaEmail) is meant to apply only if a TFA method is not already already selected. If an administrator has manually selected a TFA method for a user then it has to be confirmed before it can be enabled. I would instruct your administrator not to select a TFA method for the user at all so that the forced default/fallback TFA can do it's job. (which would TfaEmail, if selected in the ProcessLogin module)

**Comment by snobjorn** [comment] 2021-05-09 14:39
@ryancramerdesign Thank you for the elaboration. It all makes sense to me now. Also thanks for the advice on the follow up.

**Comment by netcarver** [comment] 2021-06-13 07:04
@snobjorn Closing this now - if you need to have it re-opened, just post here again.

**Closed as completed by netcarver** 2021-06-13 07:04 UTC
Labels: resolution: not a bug, status: discussion
