### ISSUE TITLE
FileCompiler issue

### ISSUE THREAD

**Issue by LostKobrakai** [processwire/processwire-issues#254] opened 2017-04-27 19:36 UTC
### Short description of the issue

My module does not get compiled as it should be, like it's reported here: https://github.com/LostKobrakai/Migrations/issues/16

### Expected behavior

The namespace being added like for the Exception in the begining of the screenshot.

### Actual behavior

The function call stays the same.

### Optional: Screenshots/Links that demonstrate the issue

<img width="777" alt="screenshot 2017-04-27 21 30 26" src="https://cloud.githubusercontent.com/assets/2489835/25500880/fd16784c-2b90-11e7-9bb4-bb0ec946fb3b.png">

### Optional: Suggestion for a possible fix

Your possible fix goes here.

### Steps to reproduce the issue

See the linked issue above.

### Setup/Environment

* ProcessWire version:
* (Optional) PHP version: 
* (Optional) MySQL version: 
* (Optional) Any 3rd party modules that are installed and could be related to the issue:

**Comment by LostKobrakai** [comment] 2017-05-05 10:18
https://github.com/LostKobrakai/Migrations/commit/d22e6b4c5a5726e320dae0f6bd586578ad19a3b7
This commit resolved the issue for my module, maybe it helps for resolving why the compiler couldn't handle it.

**Comment by ryancramerdesign** [comment] 2017-05-05 14:01
Thanks. The issue is that FileCompiler doesn't attempt to convert multi-line function calls. It's a little tricky finding the right balance between avoiding false positives and covering as many cases as possible, but I'll see if there's some way to support this case.

**Comment by netcarver** [comment] 2019-02-06 14:14
@ryancramerdesign Any update on the research for this one?

**Comment by netcarver** [comment] 2019-02-16 19:59
/remind me to review this issue in 2 weeks

**Comment by ryancramerdesign** [comment] 2019-02-21 21:02
@netcarver With FileCompiler in broad usage and working reliably for the majority of cases, I think there's some danger in breaking more than we fix, if we try to make adjustments for something like this. I don't think we'll be making further changes to FileCompiler unless some major issue arises. FileCompiler is here to get folks from PW2 to PW3, but by PW4 I think we will have phased it out.

**Comment by netcarver** [comment] 2019-02-21 21:22
@ryancramerdesign Ok. I have a reminder set for a weeks time on this issue. Will close then if no major issues are reported.

**Comment by netcarver** [comment] 2019-03-05 22:14
Closing.

**Closed by netcarver** 2019-03-05 22:14 UTC
Labels: type: file compiler
