### ISSUE TITLE
Session Problems

### ISSUE THREAD

**Issue by dennisspohr** [processwire/processwire-issues#341] opened 2017-08-10 17:09 UTC
### Short description of the issue

After a user logins on my frontend I get the following exception after every 5th-10th page-request:

> session_start(): Session callback expects true/false return value in /www/.../wire/core/Session.php on line 267

### Setup/Environment
* ProcessWire version: 3.0.62
* (Optional) PHP version: 7.0.20

**Comment by ryancramerdesign** [comment] 2017-08-16 13:43
Do you have any other Session modules installed, like SessionHandlerDB? Look under Modules > Site > Session, and Modules > Core > Session.

**Comment by dennisspohr** [comment] 2017-08-16 14:06
Yes, SessionHandlerDB is installed. And also ProcessLoginHistory if that matters.

**Comment by ryancramerdesign** [comment] 2018-02-23 12:44
Are you still experiencing this error? I was never able to duplicate it, and haven't been able to pinpoint what exactly the error message is actually referring to.

**Comment by dennisspohr** [comment] 2018-02-23 14:10
Yes I'm still getting this error (currently ignoring it)

But I also have other problems with the session: sometimes my users get logged out after just a few minutes. It's happening on a very irregular basis and I couldn't find more about it. In the meantime I also moved to a new server, but having the same problems.

**Comment by ryancramerdesign** [comment] 2018-02-23 14:43
Your users might be getting logged out for an unrelated reason, like
session fingerprinting. Check your Setup > Logs > Session to see. You can
disable session fingerprinting in your config.php if you find it's an
issue. For the session error that you are seeing, I think we need to find
someone else that can reproduce it since I've not been able to here, so
lets keep this issue open. When you moved to a new server, is it within the
same hosting/company (wondering if common configuration related), and do
you observe any difference without the SessionHandlerDB module installed?
Thanks.

**Comment by dennisspohr** [comment] 2018-02-23 14:47
Thanks Ryan, I will check about the fingerprinting.

Regarding the new server - it's a new company, also move from shared hosting to a virtual server.
Unfortunately I can't deactivate the SessionHandlerDB module, because some of my system functionality is depending on it.

**Comment by netcarver** [comment] 2019-02-06 20:45
@dennisspohr Hello Dennis, can you confirm if this issue is still live? Thank you.

**Comment by netcarver** [comment] 2019-03-08 10:02
Closing as this seems to have gone cold. @dennisspohr Dennis, if this issue is still live, just post more. Thanks!

**Closed by netcarver** 2019-03-08 10:02 UTC
Labels: status: cannot duplicate—anyone else?
