### ISSUE TITLE
PW admin working on Android but not on iOS?

### ISSUE THREAD

**Issue by Notanotherdotcom** [processwire/processwire-issues#713] opened 2018-10-02 11:23 UTC
On 3.0.112, client reported to me today that the PW admin on UIKit theme doesn't work on iOS 12 (they sometimes need to go in to copy a link, check some wording etc when out of the office as they have a lot of documentation they share with customers).

I checked it in Android but seems to work fine on there with CKEditor buttons wrapping correctly and the whole page scrollable as you expect. iOS seems to have elements like breadcrumbs and CKEditor toolbars going off-screen and unable to scroll down the page according to client.

Can anyone confirm? Unfortunately I do not have an iPhone to test with.

**Comment by teppokoivula** [comment] 2018-10-04 05:36
I just gave this a test using a virtual iPhone X and Safari (don't have access to physical device, but so far these have been very much in line) but couldn't reproduce this issue.

With inline mode CKEditor worked surprisingly well (toolbar came up, and stayed in place, i.e. while scrolling it went out of screen until I scrolled back up)  and in regular mode it worked "decently": for some reason here I had a zoom issue (had to zoom out to get everything on screen), and the page seemed a lot wider than it was supposed to be (loads of scrollable empty space at the right side.)

Might need a bit more narrowing down, i.e. what exactly went wrong, what the device was, which browser, etc. It could obviously be a physical vs. virtual device thing, but again in my experience those are nowadays pretty rare :)

**Comment by Toutouwai** [comment] 2018-10-04 05:45
I tested the admin on an older iPhone and it works pretty well. The appearance of WireTabs could be better and icon layout at top right of image field can get thrown out if the field label is long, but all in all not bad.

**Comment by Notanotherdotcom** [comment] 2018-10-05 17:56
Thanks for testing guys.

This is what the client reported seeing (video in zip file): 
[ScreenRecording_10-02-2018 12-24-41.zip](https://github.com/processwire/processwire-issues/files/2451596/ScreenRecording_10-02-2018.12-24-41.zip)

We do have the AdminOnSteroids module installed so wonder if that is affecting layout. I'm stuck with no way to test though sadly :(

**Comment by Notanotherdotcom** [comment] 2018-10-05 17:57
Well, aside from the obvious "turn plugins off one by one and ask them to keep checking" which I'd not thought of til just now :D

**Comment by teppokoivula** [comment] 2018-10-06 05:45
Just to make sure that I'm getting this right: is the user trying to scroll the page, but it won't work at all... or is the screen just jumping up and down randomly?

**Comment by Notanotherdotcom** [comment] 2018-10-08 08:28
On the video I attached they seem to be having a hard time scrolling the page.

I suspect this could be down to the AdminOnSteroids module as it's caused layout issues before so will give the client instructions on how to toggle that off and test.

**Comment by teppokoivula** [comment] 2018-10-08 11:07
Actually I'm asking because saw something similar while trying to scroll on the iPhone X. Couldn't reproduce it after that one time, so I thought it was just a network connection issue.

Might have to give this another try just to make sure :)

**Comment by teppokoivula** [comment] 2018-10-08 11:30
Sorry, nope: can't reproduce that issue anymore. On the other hand I think I've finally figured out why the screen has so much extra space on the right side.

#pw-masthead (which apparently shouldn't be displayed on mobile at all) seems to mess things up in Safari on iPhone X. Currently it's hidden with `position: absolute; top: -9999px;`, but that still leaves the extra space on screen. If I add `display: none` to it, the issue goes away.

I'm not sure if this is some sort of Uikit issue or something specific to our use case... @ryancramerdesign, any ideas? Seems odd that the element is apparently hidden using position absolute, vs. display – but I'm not too familiar with Uikit or the admin theme, so perhaps there's a reason for that :)

I still can't reproduce the issue in the video, so perhaps that is related to AOS.

**Comment by rolandtoth** [comment] 2018-10-11 08:36
Most AOS (CSS) tweaks are kicking in only above 959px screen width but of course try to disable it and see if the issue persists.

**Comment by netcarver** [comment] 2019-02-16 19:43
@ryancramerdesign Does your last post mean that there has been a fix pushed for this? Can this issue be labelled as resolved?

**Comment by ryancramerdesign** [comment] 2019-02-21 16:26
@netcarver as far as I know this is resolved, but looks like I must not forgotten to connect the issue report to a commit

**Comment by netcarver** [comment] 2019-02-21 17:34
@Notanotherdotcom @teppokoivula @rolandtoth Could one of you confirm if this is fixed? If so, I'd like to close this issue.

**Comment by matjazpotocnik** [comment] 2019-02-21 17:58
I can't see that `display:none` is added to #pw-masthead in /wire/modules/AdminTheme/AdminThemeUikit/scripts/main.js after line 190

**Comment by Notanotherdotcom** [comment] 2019-02-22 08:44
I can't check as don't have an iPhone sorry. Seemed to display differently in an emulator than on a real iPhone for some reason from what I remember.

**Comment by teppokoivula** [comment] 2019-02-23 11:00
@ryancramerdesign, at least the offending code is still in place, and there's no `display: none` (apart from the one added when you're in the login screen), so I would assume that this hasn't been fixed. 

The issue only seemed to occur on some device and browser combinations, and I don't currently have access to those, so can't confirm the behaviour – only that the suggested fix hasn't been applied.

**Comment by ryancramerdesign** [comment] 2019-02-28 15:32
Testing now on an iPhone 5 (in addition to iPad 3) but not seeing any issues in 3.0.126 here. I don't recall exactly what fix was applied (must have forgotten to link it here or had a typo) but I'm not observing any issues at present so going to close this issue. However, if anyone is still experiencing it please re-open or let me know. Thanks.

**Closed** 2019-03-07 10:10 UTC
Labels: status: cannot duplicate—anyone else?, type: UIKit
