### ISSUE TITLE
Root "home" not showing in options "Page List Select" with field "Page Reference" on page with children

### ISSUE THREAD

**Issue by neeltjechanterie** [processwire/processwire-issues#1239] opened 2020-09-02 11:27 UTC
### Short description of the issue

Root page "home" not showing in options "Page List Select" with field Page Reference. I did not select any options, nor selected a parent page. Current version: ProcessWire 3.0.165, in older versions this worked (ProcessWire 3.0.138).
<img width="311" alt="Screenshot 2020-09-02 at 13 26 32" src="https://user-images.githubusercontent.com/11270519/91975611-f77aa300-ed1f-11ea-92e1-8eb2c64e986d.png">

### Expected behavior

Show "home"/root in list
<img width="485" alt="Screenshot 2020-09-02 at 13 26 02" src="https://user-images.githubusercontent.com/11270519/91975632-fea1b100-ed1f-11ea-9fa4-4f2d35228645.png">

**Comment by teppokoivula** [comment] 2020-09-02 13:25
Not sure if this is related, cross-linking just in case: https://github.com/processwire/processwire-issues/issues/1151.

**Comment by neeltjechanterie** [comment] 2020-09-02 15:09
> Not sure if this is related, cross-linking just in case: #1151.

It seems you have the same problem ... but it's strange, I started form the same template with the same field, the only thing that I've changed is the Processwire version.

**Comment by neeltjechanterie** [comment] 2020-09-02 15:16
I found the problem. If the page with the field "Page Reference > Page List Select" has childpages, the "root"/home doesn't appear. If I remove the child pages from that page, the root is visible. So I guess this is a legit bug.

**Comment by teppokoivula** [comment] 2020-09-02 15:32
> If the page with the field "Page Reference > Page List Select" has childpages, the "root"/home doesn't appear. 

Confirmed — it's the same issue. Not having any children also "fixes" the issue for me.

**Comment by kevinvermeersch** [comment] 2020-09-08 08:33
Adding "showRootPage: true" in wire/modules/Inputfield/InputfieldPageListSelect/InputfieldPageListSelect.js should fix this issue.

https://github.com/kevinvermeersch/processwire/commit/e3e9077b785d0fa4062f1a585d1fdec0d43d435e

_Originally posted by @kevinvermeersch in https://github.com/processwire/processwire-issues/issues/1151#issuecomment-686520266_

**Comment by ryancramerdesign** [comment] 2020-09-15 11:33
Thanks @neeltjechanterie @teppokoivula @kevinvermeersch I've pushed a fix for this issue, per what @kevinvermeersch identified. The issue was that a setting present in the "children" tab PageList was overriding the PageList defaults config, and since PageListSelect didn't specify a showPageRoot setting, it was accepting the default from the "children" tab one.

**Comment by kevinvermeersch** [comment] 2020-09-16 14:01
Thanks @ryancramerdesign, i've pulled the latest dev branch and it works for me.

**Closed as completed** 2020-09-16 14:11 UTC
Labels: status: fixed-please confirm
