### ISSUE TITLE
wire()->modules not containing all modules

### ISSUE THREAD

**Issue by owzim** [processwire/processwire-issues#398] opened 2017-10-04 08:11 UTC
### Short description of the issue

`$this->wire->modules` not containing modules that aren't prefixed with module type prefixes, like: `Fieldtype`, `Inputfield`, `Process` and so on.

### Expected behavior

`$this->wire->modules` should contain all installed modules.

### Actual behavior

see above

### Steps to reproduce the issue

1. Install a Module named without a prefix, like `MyModule`
2. Look into `$this->wire->modules` ... it will not be there.

### Setup/Environment

* ProcessWire version: 3.0.62
* (Optional) PHP version: 5.5.38

**Comment by Toutouwai** [comment] 2017-10-04 08:29
Weird that you would experience that. I can't reproduce - I can see loads of modules in $modules that don't have any prefix. Just a sample...

![2017-10-04_212535](https://user-images.githubusercontent.com/1538852/31166360-f7975f52-a94a-11e7-9d11-ec8b2049a1b5.png)

**Comment by horst-n** [comment] 2017-10-04 09:00
Without testing on my own, what about this scenario:
subdirectory: site/modules/HereAreMyModule/
case A) 
file: MyModule.module
case B)
file: HereAreMyModule.module
As I said, (without testing on my own), I bet case B) will work, and case A) may not.

**Comment by ryancramerdesign** [comment] 2017-10-12 13:51
> Look into $this->wire->modules ... it will not be there.

I'm not sure I follow what you mean by "look into", how do I do that? Are you talking about using it with some debugging tool, or are you talking about using a `$modules->get()`? Lets say you have SomeModule installed, and you do a `$modules->get('SomeModule');` you aren't getting the module? Or do you mean something else like `$modules->getModuleInfo()` or `$modules->findByPrefix()`?

**Comment by netcarver** [comment] 2019-02-06 20:30
@owzim Hi Christian, can you supply any more information to help Ryan track this down?

**Comment by netcarver** [comment] 2019-03-07 13:53
Closing as this has gone cold. @owzim Christian, if you have any more information regarding this, please post here and it can be reviewed. Many thanks!

**Closed by netcarver** 2019-03-07 13:53 UTC
Labels: status: needs more information
