### ISSUE TITLE
WireDebugInfo class never loaded but used in core

### ISSUE THREAD

**Issue by EntitySelf** [processwire/processwire-issues#394] opened 2017-09-29 15:32 UTC
Version: ProcessWire 3.0.76
File: /wire/core/Wire.php
Function: __debugInfo
Line: 1758
Problem: In this function a new instance of class WireDebugInfo is created but fails because the file "WireDebugInfo.php" is never included/required in the project. Should the file be added to the $corePreloads array in /wire/core/boot.php or loaded on demand ???

![image](https://user-images.githubusercontent.com/32257936/31023425-03dad6c6-a53c-11e7-8c0f-c1aeea43306c.png)

Possible fix, loading the file on demand:
![image](https://user-images.githubusercontent.com/32257936/31029805-5e9436b8-a553-11e7-9685-9944ed6f2a82.png)

**Comment by abdusco** [comment] 2017-09-29 20:15
I've always had problems with xDebug + PW after PHP>=5.6 because of this `__debugInfo()` magic method. PHPStorm never managed to stop at the breakpoints I placed in my templates. I found the solution in commenting out all `__debugInfo()` definitions. This leads to countless properties visible in objects, but at least I can stop execution at any point and rewind as much as I need to.

**Comment by EntitySelf** [comment] 2017-09-29 20:56
No, breakpoints in the __debugInfo() method didn't work for me either, I messed around with it a bit and searched but only found old info on the problem. I put it on my to-figure-out list for another rainy day, lol... 

I found this problem while I was trying to solve this https://github.com/processwire/processwire-issues/issues/392 issue, I noticed the errors on the missing WireDebugInfo class after PHPStorm terminated the debug session, I am used to Visual Studio, thought it was weird :)

I don't really want to mess around in the core a lot because it will be a headache to maintain every update, I hope Ryan will patch it for everyone :) But thanks for the hint, next time I might just comment them out temporary...

**Comment by ryancramerdesign** [comment] 2017-10-12 09:55
Not sure I follow with this one, because any class in /wire/core/, or module in /wire/modules/ is handled by the autoloader. Meaning, it's not necessary to include() the file because the autoloader takes care of that. The core preloads array is only there as an optimization, since it saves a little time to bypass the autoloader and just include() the files that we know are always going to be needed. What error message are you seeing and how can I duplicate it? thanks.

**Comment by netcarver** [comment] 2019-02-06 20:33
@EntitySelf I know it's been a while, but can you provide a step-by-step guide to help reproduce this issue?

**Comment by netcarver** [comment] 2019-03-08 10:03
Closing as this seems to have gone cold. @EntitySelf if you come up with a step-by-step to reproduce, please post it and I'll re-open the issue. Thank you.

**Closed by netcarver** 2019-03-08 10:03 UTC
Labels: status: impacts multiple users
