### ISSUE TITLE
Adding new page with multilang OFF shows multilang fields

### ISSUE THREAD

**Issue by BernhardBaumrock** [processwire/processwire-issues#916] opened 2019-06-26 09:08 UTC
### Short description of the issue

When you disable multilang support for a template and then add a new page of that type the GUI shows multilang fields for title + page name. Once the page is saved it shows only single-language fields.

### Expected behavior

It should show single-language fields instead (only default language)

### Optional: Screenshots/Links that demonstrate the issue

![image](https://user-images.githubusercontent.com/8488586/60167068-a1000380-9802-11e9-9efb-3b8ccb0933c5.png)

![image](https://user-images.githubusercontent.com/8488586/60167086-b07f4c80-9802-11e9-9faa-9415aff11181.png)

### Setup/Environment

* ProcessWire version: 3.0.133

**Comment by ryancramerdesign** [comment] 2019-06-28 11:58
@BernhardBaumrock I can't reproduce that one here. I've tried a few different combinations of family settings, but no luck. What are you clicking on to initiate this, and what does the URL in your address bar look like when it's on the "add new" screen where you are seeing language tabs? 

Also, just to confirm, you have disabled language support by editing the template (basic-page), clicking the Advanced tab, and then checking the box at the bottom to "disable multi-language support for this template?"

**Comment by BernhardBaumrock** [comment] 2019-07-22 13:45
Hi Ryan,

just tried it with a fresh installation of the languages site profile:

Go to edit template -> basic-page `/admin/setup/template/edit?id=29` -> advanced -> disable multi-lang for this template

Add a new page under "about": `/admin/page/add/?parent_id=1001`
![img](https://i.imgur.com/BrDll8P.png)

Note: It still shows the language tabs on this page.

Click save, then the language tabs are disabled:
![img](https://i.imgur.com/GZEWA2e.png)

**Comment by matjazpotocnik** [comment] 2022-04-18 06:40
@BernhardBaumrock, is this still an issue? As I can't reproduce either.

**Comment by BernhardBaumrock** [comment] 2022-04-18 08:52
Thx for checking. I tried it with the latest DEV and it is still the same (wrong) behaviour.

- install PW dev
- install language support + company modules (field language, field tabs etc)
- disable multi-lang for "basic-page"
- create a new page

The language input will show up:

![image](https://user-images.githubusercontent.com/8488586/163783428-f43352da-f1b8-46f6-b353-56625acfed27.png)

After creation it will be a single language page:

![image](https://user-images.githubusercontent.com/8488586/163783474-bb7b1d2e-8417-4455-be27-075e69fcea1a.png)

It should already be a single language page on page-add. IMHO this is a bug.

**Comment by ryancramerdesign** [comment] 2022-04-22 14:23
@BernhardBaumrock I just tried to duplicate again but still can't. Here's what I'm doing. I've got a template blog-category in my multi-language site, and if I go to Blog > Categories > Add New, I get this:

<img width="848" alt="Screen Shot 2022-04-22 at 10 18 49 AM" src="https://user-images.githubusercontent.com/328272/164733377-a10b9a61-2e9b-4d57-85e7-c92278622928.png">

So I go and edit my blog-category template and check the box to disable multi-language:

<img width="764" alt="Screen Shot 2022-04-22 at 10 17 48 AM" src="https://user-images.githubusercontent.com/328272/164733448-465ae575-85eb-408a-b8fc-6713f5402c51.png">

Then I go to attempt to add a blog category again, and I get this:

<img width="760" alt="Screen Shot 2022-04-22 at 10 17 15 AM" src="https://user-images.githubusercontent.com/328272/164733495-1561076b-142a-4059-80fd-f241c3ce64f9.png">

**Comment by BernhardBaumrock** [comment] 2022-05-07 09:06
Hey Ryan thx. That's very strange... I've tried it again and it's the same result. Could you try installing my version and see if that works different on your end?
Here is the zip with all the files + a db dump in /site/assets/backups/database/db.sql (will be online for 14 days I think): https://transfer.sh/fg4HYY/tmp-lang.zip
Admin login is ddevadmin / ddevadmin. See config.php to adjust db connection info (dont forget to change the db host as it is "db" in my case).
You can delete the .git and .ddev folders after extract.

Here is how this installation looks like on my end (will be deleted on 21/05): https://calip.io/O1wKadGz#cQZ1CRZf

**Comment by BernhardBaumrock** [comment] 2022-05-07 12:23
Update: Forum member Klenkes can confirm this issue: https://processwire.com/talk/topic/27094-does-disabling-multi-lang-work-for-you/?do=findComment&comment=223706

**Comment by BernhardBaumrock** [comment] 2022-05-07 13:09
Hey @ryancramerdesign the issue occurs only if there is just one single template allowed to be added! Thx @matjazpotocnik 

https://calip.io/1TJBAzco#RHR92CVm

**Comment by aagd** [comment] 2022-05-07 13:23
> Hey @ryancramerdesign the issue occurs only if there is just one single template allowed to be added! Thx @matjazpotocnik
> 
> https://calip.io/1TJBAzco#RHR92CVm

I can reproduce this in **3.0.198 dev**

**Comment by matjazpotocnik** [comment] 2022-05-07 14:27
I fixed it like this:

In ProcessPageAdd.module, after line 925, I added:
```
if($template->noLang) $field->attr('data-nolang', '1');`
```
In ProcessPageAdd.js, after line 84, I added:

```
if(parseInt($("#Inputfield_template").attr('data-nolang')) > 0) {
    hideLanguageTabs();
}
```

**Comment by BernhardBaumrock** [comment] 2022-05-07 14:32
Nice!! I can confirm that this fixes the issue for me :)

**Comment by ryancramerdesign** [comment] 2022-05-09 14:20
Thanks @matjazpotocnik I've added your suggested fix for this.

**Closed as completed** 2022-05-09 14:21 UTC
Labels: status: has suggested fix, status: fixed-please confirm
