### ISSUE TITLE
New circular reference issue with page reference field

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-issues#572] opened 2018-04-24 17:03 UTC
### Short description of the issue

Firstly, just to clarify, this is different to the old: https://github.com/ryancramerdesign/ProcessWire/issues/663

I two two page reference fields on the user template: `subscriber` and `tester`

User 1 selects User 2 as tester
User 2 selects User 1 as subscriber
User 3 selects User 1 as subscriber

This results in a circular reference and out of memory errors because of the `resetTrackChanges()` method. 

### Expected behavior

I should be able to reference a page from another page with one page reference field and reference the original one via a different page reference field.

### Actual behavior

Out of memory error due to circular reference.

### Optional: Suggestion for a possible fix

I think the approach is to store a PageArray of already process pages from `$value` and check the next `$value` against this to ensure it's only processed once.

### Steps to reproduce the issue

1. Create two page reference fields on the same template
2. Select Page 1 from Page 2 for one of the fields
3. Select Page 2 from Page 1 for the other field
4. Try to edit the page in the admin or call it via the API

**Comment by adrianbj** [comment] 2018-04-24 17:08
Here's an idea for an approach to fix this from @BitPoet

https://processwire.com/talk/topic/8567-endless-recursion-in-pageresettrackchanges/?do=findComment&comment=166089

**Comment by Toutouwai** [comment] 2018-04-25 00:07
Would something like this work?...

```php
public function resetTrackChanges($trackChanges = true) {
    parent::resetTrackChanges($trackChanges);
    foreach($this->data as $key => $value) {
        if($value instanceof Page && $value->resetDone) continue;
        if(is_object($value) && $value instanceof Wire && $value !== $this) {
            if($value instanceof Page) $value->resetDone = true;
            $value->resetTrackChanges($trackChanges);
        }
    }
    return $this; 
}
```

**Comment by adrianbj** [comment] 2018-04-25 03:54
Hey @Toutouwai - not well tested yet, but so far, so good!

I'll post here if I notice any side-effects over the next couple of days as I'll be working heavily with this.

Thanks!

**Comment by ryancramerdesign** [comment] 2018-04-26 09:50
Thanks for looking at this and for the proposed solutions. Looks good to me, though I'm wondering about one thing. If it sets a `resetDone` property on the Page, doesn't it then break any future `resetTrackChanges()` calls? If so, I was thinking that maybe it should get a timestamp before the foreach, and then compare the resetDone against that timestamp instead? Or am I misunderstanding the issue? These circular reference things are sometimes hard to conceptualize. 
~~~~~~
public function resetTrackChanges($trackChanges = true) {
    $ts = time();
    parent::resetTrackChanges($trackChanges);
    foreach($this->data as $key => $value) {
        if($value instanceof Page && $value->resetDone >= $ts) continue;
        if(is_object($value) && $value instanceof Wire && $value !== $this) {
            if($value instanceof Page) $value->resetDone = $ts;
            $value->resetTrackChanges($trackChanges);
        }
    }
    return $this; 
}
~~~~~~

**Comment by adrianbj** [comment] 2018-04-26 15:49
Thanks for thinking about this Ryan - it's time to get this sorted once and for all :)

> If it sets a resetDone property on the Page, doesn't it then break any future resetTrackChanges() calls?

I don't honestly know - do you have any ideas on the best way to test this properly?

**Comment by ryancramerdesign** [comment] 2018-04-27 15:07
I can't say I've ever used this type of circular reference with pages, and not sure I totally understand why the issue turns up, but it sounds like @Toutouwai does. I'm glad the proposed solution from Toutouwai seems to solve the problem, but I can also see it creates a new problem, which is that it leaves all those objects with a resetDone property in a state where any further resetTrackChanges() calls won't do anything. So there has to be something that either removes that resetDone property when it's no longer needed, OR uses a timestamp to group them together (like my example above), so that later resetTrackChanges() calls don't get blocked. If anyone observing the issue tests out the function I posted above (which is a variation on Toutouwai's suggestion), and everything still works (no circular reference problems) then I think that's the way to go.

**Comment by adrianbj** [comment] 2018-04-27 15:14
@ryancramerdesign - I can confirm that your version with the timestamp also works, so if you think it's better, then I am happy with it at the moment - it seems to make logical sense. I'll monitor things and let you know if I find any issues.

**Comment by adrianbj** [comment] 2018-04-28 12:58
Just did a little testing and it turns out the microtime makes things worse :)

If I simply load the edit interface for a user page in the admin, this is how many times `resetTrackChanges()` is called:

Current core: 208550
Toutouwai: 254
Ryan: 254
BitPoet with microtime(true): 169090
BitPoet with microtime(): 6441
Adrian: 253

I repeated these tests a few times and the counts varied quite a bit, but always within the same order of magnitude.

The "Adrian" option is:

```
	public function resetTrackChanges($trackChanges = true) {
	    parent::resetTrackChanges($trackChanges);
	    foreach($this->data as $key => $value) {
	        if($value instanceof Page && in_array($value->id, $this->pagesChecked)) continue;
	        if(is_object($value) && $value instanceof Wire && $value !== $this) {
	            if($value instanceof Page) $this->pagesChecked[] = $value->id;
	            $value->resetTrackChanges($trackChanges);
	        }
	    }
		$this->wire('log')->save('testing','adrian');
	    return $this;
	}
```

I define `	protected $pagesChecked = array();` at the top of the class. I guess my solution has the same potential issue that Ryan brought up about @Toutouwai 's idea without the time check.

Any thoughts anyone?

**Comment by adrianbj** [comment] 2018-05-21 21:12
@ryancramerdesign - any more thoughts on this. I have a project about to go live that is relying on this.  I am happy enough with @Toutouwai's solution, but I wonder if there is still perhaps a more reliable/efficient approach?

**Comment by ryancramerdesign** [comment] 2018-05-24 10:26
@adrianbj I think the one that uses time() sounds like it will work, and maybe that's the one we should go with. The only thing I don't like is that it sets a property (resetDone) on all the pages, and that property stays, so it's using a few more bytes than I'd like, though not a big deal. But here's another version to try which might be slightly more efficient than the previous ones (if it works). It uses that pagesChecked concept, but in a way that is shared among everything being reset, and then wiped out once the original reset as finished. It also uses isset() rather than in_array(), as isset() is quite a bit faster. Are you able to test this version to compare like you did with the others?
~~~~~~~
public function resetTrackChanges($trackChanges = true) {
	static $pages = array();
	static $level = 0;
	$level++;
	parent::resetTrackChanges($trackChanges);
	foreach($this->data as $key => $value) {
		if(!$value instanceof Wire) continue;
		if($value instanceof Page) {
			if($value === $this || isset($pages[$value->id])) continue;
			$pages[$value->id] = $value;
		}
		$value->resetTrackChanges($trackChanges);
	}
	$level--;
	if(!$level) $pages = array();
	return $this;
}
~~~~~~~

**Comment by adrianbj** [comment] 2018-05-24 14:35
@ryancramerdesign  - Thanks for taking the time to look into this. I am hesitant to use your time() approach because of the issue with microtime not working - suggests to me that it may not be reliable.

Looking at your new approach - I repeatedly see 306 calls to `resetTrackChanges()` compared to 255 for my pagesChecked approach,  although I am not sure why :) 

Any thoughts?

**Comment by ryancramerdesign** [comment] 2018-05-25 14:13
@adrianbj The reason you are seeing more calls to the above version is because Page objects come in different varieties, like User being a type of Page. Those static variables only persist in the same class even if one extends the other. So a static in a method from Page, doesn't retain it's value in User, even if User doesn't override the method. I often forget this, and did here. I think this version should work as intended:
~~~~~
protected static $resetTrackChangesItems = array();
public function resetTrackChanges($trackChanges = true) {
	parent::resetTrackChanges($trackChanges);
	$isRoot = empty(self::$resetTrackChangesItems); 
	foreach($this->data as $key => $value) {
		if(!$value instanceof Wire) continue;
		if($value instanceof Page) {
			if($value === $this || isset(self::$resetTrackChangesItems[$value->id])) continue;
			$pages[$value->id] = true;
		}
		$value->resetTrackChanges($trackChanges);
	}
	if($isRoot) self::$resetTrackChangesItems = array();
	return $this;
}
~~~~~

The reason the microtime() version didn't work is because it returns strings and it would be doing string comparisons rather than time comparisons. And the reason the microtime(true) version didn't work is I think because the values microtime(true) returns have some additional precision in them beyond what's visible. For instance, see this:
~~~~~
$t1 = microtime(true);
$t2 = microtime(true);
echo "$t1\n$t2\n";  
echo "Values are the same? ";
echo ($t1 == $t2 ? "Yes" : "No");
~~~~~
This results in the following output:
~~~~~
1527256469.89
1527256469.89
Values are the same? No
~~~~~
The values sure look the same, but in a comparison, PHP says they aren't. However, if you round the microtime values to what's actually visible, that seems to correct the issue:
~~~~~
$ts = round(microtime(true), 2); 
~~~~~
That might be worth trying in the resetTrackChanges(). 

Btw, I'm not sure how your pagesChecked version works unless the $pagesChecked variable was a static class variable, like in the version I posted above in this message. If it wasn't, you'd get a new $pagesChecked array for every Page instance, and it seems like that could potentially allow a circular reference to proceed?

**Comment by adrianbj** [comment] 2018-05-25 14:47
@ryancramerdesign - thanks for the all the detailed explanation around `microtime()`.

Unfortunately your new version doesn't work - it was called ~190000 times.

I am short on time this morning so can't investigate, but if you want me to try anything else, just let me know.

**Comment by ryancramerdesign** [comment] 2018-05-25 15:22
Strange, that's a lot of calls! Wow. I must be missing something major.
It's working fine here, but I don't have a proper circular reference to
test it with. Let's not bother with investigating it further... We know the
time() one works nicely, I think that's the way to go.

**Comment by adrianbj** [comment] 2018-07-17 04:35
Hey @ryancramerdesign - sorry to bug you, but any chance you could bump this one up on your list please?

Thanks!

**Comment by adrianbj** [comment] 2018-12-13 01:35
@ryancramerdesign - any chance of implementing a fix for the upcoming stable release please?

**Comment by ryancramerdesign** [comment] 2018-12-14 11:18
I've been reluctant to add this to the upcoming master because I'm concerned about potential side effects here, and I don't understand the issue well enough to feel comfortable with any particular solution just yet. But will return to this after the new master and get something added to the dev branch so we can start testing among a larger group to make sure there aren't any unintended side effects.

**Comment by adrianbj** [comment] 2018-12-14 16:33
Understandable :)

Just to give you an update - I have been using this version on the site in question:

```
	public function resetTrackChanges($trackChanges = true) {
	    parent::resetTrackChanges($trackChanges);
	    foreach($this->data as $key => $value) {
	        if($value instanceof Page && in_array($value->id, $this->pagesChecked)) continue;
	        if(is_object($value) && $value instanceof Wire && $value !== $this) {
	            if($value instanceof Page) $this->pagesChecked[] = $value->id;
	            $value->resetTrackChanges($trackChanges);
	        }
	    }
	    return $this;
	}
```

and so far I don't seem to have had any issues, although it might be worth thinking about @BitPoet's comment here: https://processwire.com/talk/topic/8567-endless-recursion-in-pageresettrackchanges/?do=findComment&comment=166089

**Comment by BitPoet** [comment] 2018-12-15 01:33
@adrianbj, @ryancramerdesign: I'm planning to run some extensive testing (and probably twiddling) on the possible solutions over the "slow days" between Christmas and new year, and I'll hopefully have a production tested PR ready early in January (I have a few parts in our intranet page that are heavily reliant on resetTrackChanges working properly and efficiently, so it's the perfect environment for that). I'll report back here.

**Comment by BitPoet** [comment] 2019-01-08 14:16
Sorry that this took a bit longer than planned. I gave this some more thought, and the timestamp approach should be unnecessary. @ryancramerdesign's [solution with the (class-)static array](https://github.com/processwire/processwire-issues/issues/572#issuecomment-392070961) seems to be the best solution, though there is a variable naming mismatch in the posted code, which is likely why the number of recursive calls was so high.

@adrianbj, can you give this fixed version a try? This also assigns the current page earlier to the list of processed pages.
```php
	protected static $resetTrackChangesItems = array();

	public function resetTrackChanges($trackChanges = true) {
		$isRoot = count(self::$resetTrackChangesItems) == 0;
		
		self::$resetTrackChangesItems[$this->id] = true;
		
		parent::resetTrackChanges($trackChanges);
		foreach($this->data as $key => $value) {
			if(is_object($value) && $value instanceof Wire && $value !== $this) {
				if($value instanceof Page && isset(self::$resetTrackChangesItems[$value->id])) continue;
				$value->resetTrackChanges($trackChanges);
			}
		}
		
		if($isRoot) self::$resetTrackChangesItems = array();
		
		return $this; 
	}
```

**Comment by adrianbj** [comment] 2019-01-08 15:14
Thanks @BitPoet - I tested your version and it results in 282 calls to resetTrackChanges compared with 253 for my version. Obviously still function and way better than the default version, but I am curious why there is a difference.

**Comment by BitPoet** [comment] 2019-01-08 15:51
Thanks @adrianbj for the quick feedback. I guess you might have less calls because of multiple "toplevel" calls to resetTrackChanges. Ryan's+my version resets the seen pages list before exiting the method when it wasn't called recusively, while yours doesn't. So if different parts of PW invoke resetTrackChanges on the same page, your code still has the id's for pages referenced by that page in the list. That likely happens with PW's caching reusing existing page objects.

**Comment by BitPoet** [comment] 2019-02-09 10:37
@adrianbj - can you give more details about your setup? I just tried to reproduce the issue, but I could save a user with a field referencing another user just fine.

**Comment by adrianbj** [comment] 2019-02-12 23:01
Hi @BitPoet - did you try adding the reference via the API like in my example using the user object vs the user id, or did you just add the reference via the admin?

**Comment by Toutouwai** [comment] 2019-04-05 08:15
@ryancramerdesign, what do you think about the idea of adding a config option to Page Reference fields so that when the option is enabled the field returns page IDs instead of Page/PageArray objects? So enabling this option would have a similar effect to @teppokoivula's FieldtypePageIDs module, but with the benefits of having all the Page Reference inputfield types available and the familiar config options for defining selectable pages.

**Comment by startmedia001** [comment] 2019-04-17 14:50
Hi everybody - I'm new to PW and wanted to creat a REST-API. It seems i have the same issue with the referencefield: https://processwire.com/talk/topic/21291-fatal-error-when-outputting-multiple-page_reference-fields/?tab=comments#comment-184185

After doing the Hello-World tutorial (That thing with the planets) and playing around with the reference field, I have tried to assign to each planet another planet and got the following error:

Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 262144 bytes) in /Applications/MAMP/htdocs/extranet/wire/core/Page.php on line 1651
Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 262144 bytes) in Unknown on line 0

**Comment by adrianbj** [comment] 2020-03-05 23:28
@ryancramerdesign - another weird one today. I added a page reference field `billing_user` to a regular template with this selector:
```
template=user, client=page.id
```
where `client` is another page reference field that links back to the current page.

This resulted in out of memory errors, so I tried using the PHP option and used this:
```
$this->wire()->addHookAfter('InputfieldPage::getSelectablePages', function($event) {
	if($this->wire('process') != 'ProcessPageEdit') return;
	if($event->object->hasField == 'billing_user') {
	  $event->return = $event->pages->find('template=user, client='.$event->arguments('page'));
	}
});
```
and that works just fine. Not sure why the latter works, but thought I should report the difference in case it helps you when planning a fix for all this.

Note that both `billing_user` and `client` are "single" page fields.

**Comment by apeisa** [comment] 2020-08-25 13:04
@ryancramerdesign any news on getting this issue fixed on dev branch now that new master is published? This is causing multiple issues for us and seems to bite users quite a often.

**Comment by sforsman** [comment] 2020-08-25 14:10
Also note that after the infinite loop problem with `Page::resetTrackChanges()` has been fixed, an almost identical fix to `Page::uncache()` is required (the culprit being https://github.com/processwire/processwire/blob/380583a92cdc07aec149a08092019e63c803c349/wire/core/Page.php#L4181).

It is possible that the postfix issue @adrianbj encountered (https://github.com/processwire/processwire-issues/issues/572#issuecomment-459977890) is caused by the latter, since by default PW executes `Pages::uncacheAll()` after `Page::save()`.

**Comment by ryancramerdesign** [comment] 2020-08-25 15:44
@apeisa I really want to be able to reproduce the issue before I apply fixes for it. I've never been able to reproduce it though.  I see enough people run into it that it's there, but just not sure what I'm missing to see it in the wild. I thought I sort of understood what was going on when we were talking about changes to resetTrackChanges(), but was operating only out of concepts rather than a tangible issue to test against. Then I saw startmedia001's post above, which sounded like it might be a clear way to reproduce it, so I tried, but still couldn't. Then I updated my dev copy of the processwire.com site, adding a "related_posts" Page field to all the blog posts, and set it up so that they all store references to one another, creating lots of circular references, and displaying them on the front-end. Still can't reproduce it. Is there some other factor at play here like autojoin on a Page field or something?

**Comment by sforsman** [comment] 2020-08-25 17:45
It's pretty easy to reproduce - just create a Page Reference -field (with `derefAsPage` set to 1 or 2), a practical example would be `spouse`, then create two pages A and B, select A as spouse for B and vice versa. Then `$pages->find("spouse!=''")->each(function($page) { echo $page->spouse->title . PHP_EOL; });`. There are different ways to produce the same problem but this should be the simplest way.

**Comment by ryancramerdesign** [comment] 2020-08-25 18:48
Thanks @sforsman I can duplicate that using your instructions. The only change I had to make to my existing test was changing the page field settings to return a single Page rather than PageArray. Then suddenly it gets the out of memory error, where it was working fine before. Strange that it would matter, but also good, in that it narrows in on where to look.

**Comment by adrianbj** [comment] 2020-08-25 18:51
@ryancramerdesign - please also take a look at: https://github.com/processwire/processwire-issues/issues/1092 and in particular the linked issues in the first post. One of them at least talks about single page vs array.

**Comment by sforsman** [comment] 2020-08-26 07:53
@ryancramerdesign the difference comes down to the fact that `PageArray` does not have it's own implementation of `resetTrackChanges()` that would actually call `Page::resetTrackChanges()`. In the case of `PageArray`, when `Page::getFieldValue()` calls `resetTrackChanges()` on the `$value`, basically a few arrays are just reset to empty.

To put it in a different way, if `PageArray` would use an implementation that called `resetTrackChanges()` on each `Page`-object it contains, then the problem would surely exist with `derefAsPage=0` as well.

It's probably already been discussed earlier, but as a quick recap, the infinite loop happens because in these scenarios when the value of the `FieldtypePage` is populated, `resetTrackChanges()` is called on the `$value`, which in the case of `Page`-objects goes through all it's loaded `data` and executes `resetTrackChanges()` on the values.

So using the previous simple loop as an example, let's say we are at the second iteration and we start to populate `spouse` for page B. 

1. The field contains a reference to page A, on which `resetTrackChanges()` is called. 
2. `resetTrackChanges()` goes through the `data` of page A and since the `spouse` of page A is loaded and points to B, `resetTrackChanges()` will call `resetTrackChanges()` on page B.
3. Because page B has partially loaded `spouse` (i.e. the value is already stored in the `data`-property), another `resetTrackChanges()` is called on page A.
4. Jump to step 2.

Obviously the infinite loop can be avoided by calling `$page->uncache()` after each iteration (which would cause too much overhead in our use cases), or by calling `$page->remove("spouse")` (which isn't very practical either).

**Comment by ryancramerdesign** [comment] 2020-08-27 12:54
@sforsman Thank you, that really clarifies it for me! If I understand correctly, The issue is simpler than I was thinking. It sounds like the direction we were going in before with resetTrackChanges keeping track of stuff is not necessary, though not 100% certain. But the problematic line seems to be [this one](https://github.com/processwire/processwire/blob/master/wire/core/Page.php#L1542):
~~~~~
if(is_object($value) && $value instanceof Wire) $value->resetTrackChanges(true);
~~~~~
Unless I'm forgetting something, that line is hardly necessary. It's there to make sure the Page is starting with a clean value without any pending tracked changes, just in case the Fieldtype got messy. It's basically a little bit of insurance, but probably not necessary insurance. Plus, it really shouldn't be called on a Page object at all. ProcessWire tries hard not to create multiple instances of the same Page, and there may be legit changes in that Page object instance that shouldn't be reset. 

I think it's possible the line could just be removed. But maybe a safer bet would be to just prevent it from resetting changes on Page objects, like this: 
~~~~~
if(is_object($value) && $value instanceof Wire && !$value instanceof Page) $value->resetTrackChanges(true);
~~~~~
That fixes the issue in testing here. Do you find the same?

I also think that just in general, Page objects should never resetTrackChanges() on other Page objects, unless they are owned exclusive by the Page (like a RepeaterPage). That's because Page objects are shared in memory, so the same instance gets passed around to anything that asks for it. One Page really has no authority over another (repeaters excepted) and shouldn't be resetting anything about another Page. I can see that the reason for infinite loop is that PW is breaking its own rules about one Page being a good citizen among other pages. So while the change above might seem to resolve the issue, I think it also needs to check and skip over Page objects in the [Page::resetTrackChanges](https://github.com/processwire/processwire/blob/master/wire/core/Page.php#L3079) method:
~~~~~
public function resetTrackChanges($trackChanges = true) {
	parent::resetTrackChanges($trackChanges);
	foreach($this->data as $key => $value) {
		if(is_object($value) && $value instanceof Wire && !$value instanceof Page) {
			$value->resetTrackChanges($trackChanges);
		}
	}
	return $this; 
}
~~~~~
You've mentioned uncache as a solution, and I'm not sure I totally understand that route. So I'm trying to be a bit verbose here and paste in code and such, rather than just committing it, as I could be forgetting or missing something too. Thanks for looking at all of this.

**Comment by sforsman** [comment] 2020-08-27 15:20
@ryancramerdesign nice! Your suggestion most certainly fixes the issue. I also like your reasoning about the relation- and ownership between Pages. It's hard to think of a scenario where a ProcessWire developer actually relies on the current behavior. Either way I think the change you proposed makes sense.

> You've mentioned uncache as a solution, and I'm not sure I totally understand that route.

Actually I didn't mean it as a solution, it was just a sidenote on how to work around the issue _without_ touching the core.

Now that we're on the path to fixing the loop in resetTrackChanges, there is a very similar issue with uncache caused by [this](https://github.com/processwire/processwire/blob/master/wire/core/Page.php#L4181). The problem can be reproduced using my original example and adding `wire('pages')->uncacheAll();` after the loop. Just note that the resetTrackChanges fix needs to be in place for the execution to reach that point.

**Comment by ryancramerdesign** [comment] 2020-08-27 19:00
Another great find, thanks @sforsman — as far as I can tell, [this line](https://github.com/processwire/processwire/blob/master/wire/core/Page.php#L4181) in the Page::uncache() method is doing nothing useful and just causing an issue here. Even if it had some purpose, it should have been validating for an interface before calling a method like that, which makes me think it must have been some temporary code that got overlooked. I am removing that line and testing locally, but I don't expect any issue with removing it as I think it hasn't been relevant for a long time, if ever. The way PW works at present, the behavior we were looking for with that line already happens on its own. From testing here, it looks like it fixes the out of memory error when uncacheAll() gets called on the page with the circular reference.

**Comment by apeisa** [comment] 2020-08-28 06:19
Thank you everyone participated in fixing this issue! Great to have this kind of "difficult but nasty" bugs killed 💪 

We will test dev branch soon to see if it works as expected.

**Comment by adrianbj** [comment] 2020-08-31 20:32
@apeisa - looks like it's working for me here, but I'll wait until you confirm at your end as well before I close this. Thanks to you and @sforsman for getting this back on Ryan's radar.

**Comment by apeisa** [comment] 2020-09-11 10:42
This looks good for us also!

**Closed** 2020-09-14 02:07 UTC
Labels: status: discussion, status: multiple

**Comment by Radon8472** [comment] 2020-11-12 09:07
@ryancramerdesign
Could you take a look at #1272 please?

It seems that the problem is very similar to this issue, but it has to be fixed in the ProDrafts module too.
