### ISSUE TITLE
Text Tags Inputfield Type Repeater z-index issue

### ISSUE THREAD

**Issue by Notanotherdotcom** [processwire/processwire-issues#1512] opened 2022-01-23 18:35 UTC
### Text Tags Inputfield Type Repeater z-index issue

In repeaters, if the inputfield with the text tab type is at the bottom edge of the repeater and the list of possibly entries is >1 it gets cut off (z-index issue I think)

### Expected behavior

Like ASM Select, it should overlap outside the repeater so you can see the full list

### Actual behavior

It gets cut off

### Optional: Screenshots/Links that demonstrate the issue

The "Leader" field at the  bottom right should have about 18 names on it but only one is visible

<img width="769" alt="image" src="https://user-images.githubusercontent.com/190857/150692779-6376f62a-e777-4dea-a592-06d351868634.png">

**Comment by apeisa** [comment] 2022-03-16 08:30
I can confirm this issue is there with PW 3.0.184. It works in FF, but not in Chrome (99.0.4844.51).

**Comment by matjazpotocnik** [comment] 2022-05-08 16:31
I can replicate, PW 3.0.199, Edge. It happens because `overflow:hidden` is added to "surrounding div" `<div class="InputfieldContent uk-form-controls">`. 

![image](https://user-images.githubusercontent.com/7663992/167305089-f220c34b-2c93-46f5-bb79-3d462065d930.png)

My attempt to fix this is by adding this line

`if($content.css('overflow') == 'hidden') $content.css('overflow', '');`

in InputfieldRepeater.js, after line 394.

@apeisa, @Notanotherdotcom can you test?

**Comment by matjazpotocnik** [comment] 2023-05-06 07:18
@apeisa @Notanotherdotcom ping

**Comment by apeisa** [comment] 2023-05-07 18:46
Sorry, not using pw day to day anymore, so not in a good position to test.

**Comment by matjazpotocnik** [comment] 2023-05-08 18:23
I can't replicate anymore on PW 3.0.217. Closing, let me know if it needs re-opening.

**Closed as completed by matjazpotocnik** 2023-05-08 18:23 UTC
Labels: status: help wanted, status: has suggested fix, status: multiple
