### ISSUE TITLE
Breakpoint on line 47 of Index.php returns ___DebugInfo Error

### ISSUE THREAD

**Issue by FrancisChung** [processwire/processwire-issues#114] opened 2016-12-12 15:17 UTC
I'm using latest MAMP Pro, PHPStorm and PW3.

I was trying to set a break point on line 47 when I noticed the following.

If you use PHP > 5.6,  you get a _**__DebugInfo must return an Array**_ error.
If you set a breakpoint on code that is not part of a class module, this seems to occur.

I was trying to replicate this problem on a plain vanilla PHP 5.6 project thinking it was an XDebug issue, but everything was working so I've eliminated XDebug and PHP as root cause for now.

**Comment by ryancramerdesign** [comment] 2016-12-14 11:17
I'm not sure how to duplicate this one. Though my setup is the same as yours (MAMP, PHPStorm, PW3). Is there any indication of what file it's talking about for line 47? If so, it might be easy for me to find it even if I can't reproduce it. What is the exact version of ProcessWire that you are running?

**Comment by FrancisChung** [comment] 2017-01-02 11:05
Hi Ryan, I haven't forgotten about you. I'll look into it this week and get back to you with some example files or projects

**Comment by chrBrd** [comment] 2017-03-27 12:10
I'm using PHP7, Xdebug 2.5.1 and PW 3.0.42. I've had the same problem and looked into ProcessWire's debug code.

The issue with setting any breakpoint on or before line 47 of the root index.php is due to `__debugInfo()` in `ProcessWire\Wire` requiring a current instance of the `ProcessWire` class, which isn't instaniated until line 52.

I've honestly found the `__debugInfo()` methods to be a bit of a mess - on my clean install the `WireDebugInfo` class can't be found as it isn't included. Including it then leads to a litany of problems.

I'm about to dive in and have a more thorough look at it all, but in the meantime I've found the easiest way to get XDebug working as normal is to comment out all PW's `__debugInfo()` overrides (there are 7 of them inside various classes).

**Comment by FrancisChung** [comment] 2017-03-28 06:17
Thanks Chris for the post, especially your workaround suggestions. Will try them out!

**Comment by chrBrd** [comment] 2017-03-29 08:56
Quick update on this - I've started to add a few checks to the `__debugInfo()` methods so they don't rely on uninstantiated classes, but in doing so I've come across a bug in XDebug (the debugging process will not terminate as usual if any breakpoins are set in `__debugInfo()` magic methods or any methods called by them, it needs to be closed manually). A bug report has been [submitted](https://bugs.xdebug.org/view.php?id=1410), but until the issue has been fixed I won't be able to test my changes to ProcessWire properly.

**Comment by abdusco** [comment] 2017-08-19 07:19
Thanks, @chrBrd I finally got xDebug running

**Comment by netcarver** [comment] 2018-07-31 22:52
@chrBrd @FrancisChung Thanks for this issue report. It's been a while - any updates on this issue from either of you?  Chris, did you get any further in your testing there?

**Comment by chrBrd** [comment] 2018-07-31 23:35
I'm afraid not, priorities intervened and I pretty much haven't looked at this or ProcessWire since I came across the problem. Looks like the problem in Xdebug that nixed my workarounds is still there too.

**Comment by netcarver** [comment] 2019-02-14 23:23
@FrancisChung @chrBrd Any further update to this? If not, I'd like to close this issue at the end of next week.

**Comment by netcarver** [comment] 2019-02-21 17:49
Closing as no additional information provided. Please post further if needed.

**Comment by ethanbeyer** [comment] 2019-08-16 04:20
I'd like to reopen this issue, as it's something I've been struggling with, too.

I have installed `symfony/var-dumper` via composer, but the same issue arises with `var_dump()`. I haven't tried this with Tracy yet, but since the error seems to be related to WireDebugInfo needing an instance of ProcessWire, I don't think Tracy would help.

With the background out the way, here's better information:

1. in `/index.php`, I added a `dd($config);` (dump&die) to line 34. With context, that looks like this:

```php
$config = ProcessWire::buildConfig($rootPath);
dd($config); // this does not work
if(!$config->dbName) {
    ...
}
```
As I said, the result is the same for `var_dump($config);`.

This is the error I receive:
![Screen Shot 2019-08-16 at 12 17 14 AM](https://user-images.githubusercontent.com/6864684/63143219-332eb780-bfbb-11e9-8b17-1f1e646dc2cd.png)

As @chrBrd said above:
> The issue with setting any breakpoint on or before line 47 of the root index.php is due to __debugInfo() in ProcessWire\Wire requiring a current instance of the ProcessWire class, which isn't instaniated until line 52.

There's no way to debug `$config` before the app finishes booting.

I recognize this is a fairly stable part of the app, but I am experimenting with a different file structure for ProcessWire, and so it has necessitated rewriting some of the default configs. Doesn't matter. Just thought some deeper info might help close this issue more substantially.

Thanks!

**Comment by ethanbeyer** [comment] 2019-08-16 13:11
Thanks, @netcarver!

**Comment by ethanbeyer** [comment] 2019-08-16 14:21
I needed a quick-and-dirty solution so I wasn't sitting on my hands. I don't believe this is a *good* solution, but it might be a good starting-point for the fix:

[`wire/core/Wire.php:1748`](https://github.com/processwire/processwire/blob/master/wire/core/Wire.php#L1748)
```php
/**
 * debugInfo PHP 5.6+ magic method
 *
 * This is used when you print_r() an object instance.
 *
 * @return array
 *
 */
public function __debugInfo() {
    return [];

    static $debugInfo = null;
    if(is_null($debugInfo)) {
        $debugInfo = $this->wire(new WireDebugInfo());
    }
    return $debugInfo->getDebugInfo($this);
}
```
This _does_ work, but the reason for the first `return []` being skipped to eventually output the object is unclear to me.

**Comment by ryancramerdesign** [comment] 2021-08-03 15:03
@FrancisChung @ethanbeyer I've pushed an update that should prevent that error. Though I'd still recommend avoiding breakpoints before a ProcessWire instance exists, as most ProcessWire classes require a ProcessWire instance, so there won't be anything to debug yet. But this update will let you `dd($config)` or `print_r($config);` at least.

**Closed by ryancramerdesign** 2021-08-03 15:03 UTC
Labels: status: needs more info

**Comment by ethanbeyer** [comment] 2021-08-05 15:21
Thanks for making this change, @ryancramerdesign !

**Comment by FrancisChung** [comment] 2021-08-18 00:03
Even though I haven't been working on Processwire for a few years now, I just thought I'd drop by and say thanks for fixing this issue @ryancramerdesign. Pretty much most of the issues I've raised on Github never gets a response, so great to see an issue being closed out.
