### ISSUE TITLE
InputfieldFieldset and InputfieldMarkup $field->collapsed = Inputfield::collapsedNever not working

### ISSUE THREAD

**Issue by trk** [processwire/processwire-issues#277] opened 2017-05-29 17:10 UTC
For `InputfieldFieldset` and `InputfieldMarkup` `$field->collapsed = Inputfield::collapsedNever` option not working and breaking this field visual (always closed, can't oped). 

**screenshot** without collapsed options :
![ekran resmi 2017-05-29 20 04 44](https://cloud.githubusercontent.com/assets/455983/26557441/2595b9cc-44aa-11e7-939e-bd66562d40c0.png)

**screenshot** with collapsed options:
![ekran resmi 2017-05-29 20 06 32](https://cloud.githubusercontent.com/assets/455983/26557472/59a74686-44aa-11e7-9abb-eaac61918b6c.png)

Example usage :
```php
$modules = $this->wire('modules');

$fields = new InputfieldWrapper();

$field = $modules->get('InputfieldMarkup');
$field->name = 'fields_info';
$field->label = 'InputfieldMarkup $field->collapsed = Inputfield::collapsedNever';
$field->markupText = 'Inputfield markup, without collapsed option !';
$field->collapsed = Inputfield::collapsedNever;
$fields->add($field);

$fieldset         = $modules->get('InputfieldFieldset');
$fieldset->label  = 'InputfieldFieldset $fieldset->collapsed = Inputfield::collapsedNever';
$fieldset->collapsed = Inputfield::collapsedNever;

$field = $modules->get('InputfieldMarkup');
$field->name = 'fields_info';
$field->label = 'InputfieldMarkup inside Fieldset';
$field->markupText = 'InputfieldMarkup inside Fieldset, InputfieldFieldset not have collapsed option !';
$fieldset->add($field);

$fields->add($fieldset);
```

* ProcessWire version: 3.0.63
* Any 3rd party modules that are installed and could be related to the issue:
* AdminThemeUikit

**Comment by matjazpotocnik** [comment] 2017-11-04 09:25
Isn't that by design? Inputfield::collapsedNever means Never collapsed, and not collapsable. But I agree that markupText should be displayed. As a workaround, you can add some inputfield to InputfieldMarkup:

```
$modules = $this->wire('modules');

$fields = new InputfieldWrapper();

$field = $modules->get('InputfieldMarkup');
$field->name = 'fields_info';
$field->label = 'InputfieldMarkup $field->collapsed = Inputfield::collapsedNever';
$field->markupText = 'Inputfield markup, without collapsed option !';
$field->collapsed = Inputfield::collapsedNever;
    $field_button  = $modules->get('InputfieldButton');
    $field_button->collapsed = Inputfield::collapsedHidden;
    $field->add($field_button); 
$fields->add($field);

```

**Comment by karltaidev** [comment] 2018-03-28 07:07
I can confirm the same issue. Inputfield::collapsedNever collapsed for some situation.
Version: 3.0.96
AdminTheme: UiKit

To reproduce, change the ProcessModule.module in wire/modules/Process/ProcessModule, line 434
`

		$tab = $this->wire(new InputfieldWrapper());
		$tab->attr('id', 'tab_core_modules'); 
		$tab->attr('title', $this->labels['core']);
		$tab->attr('class', 'WireTab');
		
		$markup = $this->modules->get('InputfieldMarkup');
		$markup->value = $this->renderListTable($coreModulesArray);
		$markup->label = $this->_('/wire/modules/ - Modules included with the ProcessWire core');
		$markup->icon = 'folder-open-o';
		$markup->collapsed = Inputfield::collapsedNever; //Add the line here
		$tab->add($markup); 
		$form->add($tab);`

Go to modules page and browse Core tab. It is collapsed. 

The main reason is due to the InputfieldWrapper. Without InputfieldWrapper, it works just fine.

**Comment by ryancramerdesign** [comment] 2018-03-30 13:42
Thanks! I've pushed a fix for this issue.

**Closed** 2018-06-04 02:11 UTC
Labels: resolution: fixed (close when ready)
