### ISSUE TITLE
[3.0.141] Fatal Error: Uncaught Error: Call to a member function prepend() on null in wire\core\Fields.php:1066

### ISSUE THREAD

**Issue by MrSnoozles** [processwire/processwire-issues#985] opened 2019-09-25 15:31 UTC
### Short description of the issue

When opening the "pass" field for editing in the backend I get this fatal error. 

### Expected behavior

Open the page to edit the pass field.

### Actual behavior
![grafik](https://user-images.githubusercontent.com/17496592/65616035-a49a5680-dfba-11e9-9004-385f37b9ba96.png)

### Steps to reproduce the issue

1. Log in to backend
2. Go to fields
3. Show system fields
4. Go to "pass" field

### Setup/Environment
* ProcessWire version: 3.0.141
* Blank site profile
* No site modules installed

**Comment by adrianbj** [comment] 2019-09-25 15:36
Duplicate of https://github.com/processwire/processwire-issues/issues/979

**Comment by adrianbj** [comment] 2019-09-25 15:36
It also affects several modules - these are reported in several threads on the forum.

**Comment by MrSnoozles** [comment] 2019-09-25 15:53
Thank you. No idea how I overlooked this.

**Closed as completed** 2019-09-25 15:52 UTC
