### ISSUE TITLE
Profile theme not saving on user creation

### ISSUE THREAD

**Issue by richgcook** [processwire/processwire-issues#949] opened 2019-08-02 18:56 UTC
### Short description of the issue

When I add a new user, even if the 'UIkit' theme is selected (by default), upon creating the user then logging in as said user the theme is unset. If I go to the profile, no options are selected. If I select 'UIkit' here and save it's all fine.

### Expected behavior

I'd expect when creating a user, and selecting (or not selecting if it's the default) a user theme to withhold this selection. 

### Actual behavior

The selection (or the default selection) of the user theme isn't retained and instead doesn't set any theme selection.

### Screenshots/Links that demonstrate the issue

![Screenshot 2019-07-27 at 21 45 50](https://user-images.githubusercontent.com/901289/62392506-83d7f680-b55f-11e9-81c9-104beda1de33.jpg)

### Setup/Environment

* ProcessWire version: 3.0.123 (but had this issue since v3, I believe)
* PHP version: 5.6 through to 7

**Comment by ryancramerdesign** [comment] 2019-09-25 12:34
@richgcook I can't duplicate this one, so I think it's possibly one of those things that's already fixed on the dev branch. Though I noticed in your screenshot that there's no space between the radio button and admin theme name, so it looks like something might be screwy there (another module interfering?). If you have a chance to test on the dev branch, please let me know, otherwise I'm pretty sure this one is already fixed. Thanks.

**Comment by richgcook** [comment] 2019-09-30 08:58
@ryancramerdesign I've updated to 3.0.141 but the issue still exists (and the radio buttons remain spaceless)

Looking at the CSS for the buttons it looks like it's being overridden by **/wire/templates-admin/styles/inputfields.css?v=4**

![Screenshot 2019-09-30 at 09 41 29](https://user-images.githubusercontent.com/901289/65863859-d750a000-e368-11e9-87a9-d59c2592c82e.jpg)

**Comment by ryancramerdesign** [comment] 2019-09-30 10:07
@richgcook That inputfields.css file is only used as a fallback if there are no admin themes installed. Between your screenshot and the presence of inputfields.css, it looks to me like something might be not quite right with your installation, so we'll want to troubleshoot it. The fallback admin theme (from PW 2.0) doesn't come into play unless the actual admin theme fails to load. That generally shouldn't be able to happen, unless something unexpected is happening somewhere. Some things I'd suggest as next steps:

- Modules > Refresh
- Make sure you yourself have an admin theme selected in your profile
- Modules > Site > Clear file compiler cache (button at bottom)
- If there's a /site/templates/admin-theme/ dir, remove it 
- If there's any /site/modules/AdminTheme* dirs. remove them
- If still not working, replace your entire /wire/ directory with a fresh copy

**Comment by richgcook** [comment] 2019-09-30 10:48
@ryancramerdesign Thank you so much for the detailed response.

I've done all that and deleted the 'test' user and re-added (Uikit is the only 'Admin Theme' available and it is selected by default). Screenshot from being logged in as admin below.

![Screenshot 2019-09-30 at 11 45 17](https://user-images.githubusercontent.com/901289/65872163-e559ed00-e377-11e9-95ba-98b89e40f34f.jpg)

However, when I then log in as test it's the same issue and going to Profile shows that Uikit isn't selected.

![Screenshot 2019-09-30 at 11 46 54](https://user-images.githubusercontent.com/901289/65872239-0d495080-e378-11e9-9734-01d7effae950.jpg)

Modules list:
![Screenshot 2019-09-30 at 11 47 36](https://user-images.githubusercontent.com/901289/65872283-2520d480-e378-11e9-921b-1d34190936e2.jpg)

**Comment by richgcook** [comment] 2019-09-30 10:49
This is in the DB table too in case it is of any interest?

![Screenshot 2019-09-30 at 11 48 44](https://user-images.githubusercontent.com/901289/65872391-59949080-e378-11e9-9221-e47f93c9182b.jpg)

**Comment by ryancramerdesign** [comment] 2019-09-30 14:06
@richgcook I see that only the "Pages" link appears in your admin. What roles does your user have? Does one of their roles at least have page-edit permission? (this gives permission to access the admin). I'm wondering if maybe the issue here is permissions related rather than admin theme related... maybe the user just doesn't have enough permission. Your DB table looks fine, and it's showing the row for the default superuser. If that's the only row in there, then it's not yet saved new user's selection. I would also install AdminThemeDefault (and AdminThemeReno if you'd like) so that there's more than one option for your admin theme selection, just in case. 

Another potential issue is that since AdminThemeDefault isn't installed, and is the default value for config.defaultAdminTheme, that might also be causing an issue. In your /site/config.php try adding:
~~~~~
$config->defaultAdminTheme = 'AdminThemeUikit'; // or AdminThemeDefault after installed
~~~~~

**Comment by richgcook** [comment] 2019-09-30 22:25
@ryancramerdesign Thanks for all this. I've attached a screenshot of the permissions for the role 'editor'. I've also always had the `$config->defaultAdminTheme ` addition in there. So puzzling.

I've installed the AdminThemeDefault and deleted the user and re-added. Same issue.

![Screenshot 2019-09-30 at 23 24 42](https://user-images.githubusercontent.com/901289/65921232-95ac0d80-e3d9-11e9-8611-1873a067f789.jpg)
![Screenshot 2019-09-30 at 23 24 24](https://user-images.githubusercontent.com/901289/65921233-95ac0d80-e3d9-11e9-9e65-72f9cb16ffce.jpg)
![Screenshot 2019-09-30 at 23 19 46](https://user-images.githubusercontent.com/901289/65921234-95ac0d80-e3d9-11e9-8f0c-cc4c9936b371.jpg)

**Comment by Toutouwai** [comment] 2019-09-30 22:55
@richgcook, have you determined that this issue is reproducible on a clean PW installation?

**Comment by richgcook** [comment] 2019-09-30 22:55
@Toutouwai Not yet. I will!

**Comment by netcarver** [comment] 2019-10-28 18:55
@richgcook Hi Richard, any progress?

**Comment by netcarver** [comment] 2019-12-21 14:27
@richgcook Hi Richard, it's been a while so I'm going to close this for now. Just post here again when you have the data and I'll re-open this issue.

**Closed as completed by netcarver** 2019-12-21 14:27 UTC
Labels: status: fixed-please confirm, status: can't reproduce
