### ISSUE TITLE
ProcessWire > 3.0.8: click on last item in breadcrumb of page edit does not open page tree at the right position anymore

### ISSUE THREAD

**Issue by processwired** [processwire/processwire-issues#32] opened 2016-10-08 10:26 UTC
### Short description of the issue
A page's breadcrumb does not open the page tree at the parents parent position in some cases. This happens if the page to edit has not been called from the tree (this is the case if the edit link has been called from a custom admin page, for instance).

### Expected behavior
In ProcessWire 2.7.2, a click on a parent item in a page's breadcrumb (see attached screenshot - "Level 3" for instance) opened the page tree at the position of this parent (link generated contains "?open=123" at the end).

<img width="365" alt="nav" src="https://cloud.githubusercontent.com/assets/8448399/19212344/5b261fc2-8d4f-11e6-9a52-7f2112d2006e.png">

### Actual behavior
In ProcessWire 3.0.8 and newer this function was changed: now a click on the last parent does not open the tree anymore as it was before. I believe the change came in with commit d57c9ef6186ec24144ce488842bb32c25aeb0cd2 (line 1262)
`$url = "../?open=$p->id";
if($cnt == $numParents-1) $url = "../";`

### Steps to reproduce the issue

1. Open page tree in admin: http://domain.com/admin/page/
2. Open a page for editing, preferable some page deeper in a nested structure (third level or so). Copy the edit link to clipboard from address bar like this: http://domain.com/admin/page/edit/?id=12345
3. Go back to admin, CLOSE the page tree.
http://domain.com/admin/page/
4. Paste back the page edit url from clipboard to address bar and reload page: http://domain.com/admin/page/edit/?id=12345
5. Click on the last parent in the page's breadcrumb (see screenshot above: "Level 3" in this case)
6. Result: page tree does not open at the position of the page in the tree.

### Setup/Environment

* ProcessWire version: 3.0.36

**Comment by Toutouwai** [comment] 2016-10-08 10:52
Possible dup of #22

**Comment by LostKobrakai** [comment] 2016-10-08 11:03
This behaviour was actually a requested feature, to remove the need of getting to the pagetree again, when needing to edit the parent of the page. I'm not sure if this speed improvement still matters with the new cached pagetree and the page-tree panel. So I'd also vote for removing this inconsistency, even though it was intentionally put there.

**Comment by ryancramerdesign** [comment] 2016-10-13 13:45
I'm going to close this one since it's a duplicate of #22 and the discussion is already there

**Closed by ryancramerdesign** 2016-10-13 13:45 UTC
Labels: resolution: duplicate
