### ISSUE TITLE
Superuser cannot set a users Admin Theme

### ISSUE THREAD

**Issue by cb2004** [processwire/processwire-issues#514] opened 2018-03-06 13:49 UTC
### Short description of the issue

If I am logged in as a superuser and I go into a users profile, I can set the theme to Uikit. When that user logs in they are seeing a different theme, they have to go into their profile and change the setting.

### Expected behavior

A superuser should be able to set the admin theme for another user.

* ProcessWire version: 3.0.94
* (Optional) PHP version: 
* (Optional) MySQL version: 
* (Optional) Any 3rd party modules that are installed and could be related to the issue:

**Comment by rolandtoth** [comment] 2018-03-06 15:50
I'm experiencing this for months, setting back and forth the admin theme for a user usually solves it.

**Comment by cb2004** [comment] 2018-03-06 15:51
I ended up deleting all themes apart from Uikit as I want users to use the new theme.

**Comment by cb2004** [comment] 2018-03-06 16:35
Actually just noticed thats probably not the best way of doing things. I deleted all themes without having Uikit selected just to test and the admin kind of fell down loading a very basic admin where not much worked. I would suggest if only 1 theme is installed it defaults to that. Also it lets you uninstall all themes, maybe when down to only 1 theme installed you cannot uninstall it.

**Comment by Toutouwai** [comment] 2018-03-06 21:33
You can change the admin theme that users get by default by setting `$config->defaultAdminTheme` in /site/config.php.

If you don't want users to be able to change to any other theme then you can remove the `admin_theme` field from "What fields can a user edit in their own profile?" in the ProcessProfile module config.

**Comment by szabeszg** [comment] 2018-03-07 07:14
I always do what @Toutouwai suggested as I do not get the budget to implement support of users being able to switch themes. If I do not want to spend time on issues like this, the best thing to do is to get things right by using one admin theme only.

**Comment by ryancramerdesign** [comment] 2018-03-07 12:42
I can't seem to duplicate the issue here. Logged in as superuser, I go and change another user's admin theme from Default to Uikit, then I open another browser to login with that user. But it's showing me Uikit admin when I login with that user. Then I tried switching all of them once more (Default, Reno, Uikit) but it was changing correctly for the user. Is there some step I'm missing? You are changing their admin theme from Access > Users > username, correct?

**Comment by horst-n** [comment] 2018-03-10 14:20
I have had this issue too before. But can't remember exactly how I get solved it. It may be that I disabled some or one AdminTheme, flushed caches for modules, logged out and in again, and finally installed the AdminTheme again. (<-But not sure of all steps.)
The only thing I definetly know is, that this all wasn't new installed sites, but updated by copying new wire folders to them.

**Comment by horst-n** [comment] 2018-03-10 14:22
seems to be the same issue:
https://github.com/processwire/processwire-issues/issues/514

**Comment by BernhardBaumrock** [comment] 2018-03-17 11:01
same here (also since months):

- fresh install, uikit as default theme
- create new user, keep theme setting as default on "uikit"
- log in to that user, it will have the old default theme

resolution:
set the user's theme to the old default, then back to uikit, then it works.

would be great to fix this @ryancramerdesign  , thanks.

**Comment by netcarver** [comment] 2018-07-25 18:03
@cb2004 As this could have been a duplicate of #523 - which has now been fixed - can you please verify if this is also resolved to your satisfaction, and close the issue if it is. Otherwise, please let us know if the issue persists. Thank you.

**Comment by netcarver** [comment] 2018-07-26 13:39
@ryancramerdesign @cb2004 @BernhardBaumrock @horst-n @Toutouwai @szabeszg @rolandtoth 

Just noticed this is happening on one of my 3.0.108 installs. I don't know why, but I have found that the admin_theme field is setup incorrectly in this installation. In a good install, the field is setup as follows...

![screeny-0004-good](https://user-images.githubusercontent.com/16049/43265682-6b1908d0-90e1-11e8-8218-b79c193392b4.png)

... whereas in a bad install the "AdminTheme" modules are not checked...

![screeny-0004](https://user-images.githubusercontent.com/16049/43265704-75cb9216-90e1-11e8-8abb-c587a770e807.png)

Checking the box restores the correct functionality to the user edit page. So, we have a work-around if this happens again, but not the reason for the incorrect installation of the admin_theme field.

**Comment by cb2004** [comment] 2018-07-26 19:31
@netcarver opened this up for you. Cheers for the pm on the forum.

**Comment by netcarver** [comment] 2019-02-16 19:48
/remind me to review this issue in 2 weeks

**Comment by ryancramerdesign** [comment] 2019-03-04 15:39
I can't duplicate this one. If I create a new user and select Uikit as their admin theme, they get Uikit as their admin theme. Per what @netcarver mentioned I'm guessing that there was a bug at some point and if your admin_theme field happened to be created during that time, perhaps the field was missing something. However, as far as I can tell it is not an issue that is currently present, at least I cannot duplicate it on a new installation here.

**Comment by netcarver** [comment] 2019-03-07 13:49
Closing as this has gone cold. If anyone has more data, feel free to post and it can be reviewed.

**Closed by netcarver** 2019-03-07 13:49 UTC
Labels: status: cannot duplicate—anyone else?, status: impacts multiple users, status: needs more information
