### ISSUE TITLE
MarkupRegions issue when replacing a div with attributes on multiple lines

### ISSUE THREAD

**Issue by jlahijani** [processwire/processwire-issues#834] opened 2019-03-22 19:26 UTC
Video (detailed narrated explanation):
https://youtu.be/PK_G2rucmt4

Explanation:

Assume markup regions is enabled.

Let's say you have the following in _main.php:
```
<main id="content">
</main>
```

Now let's say you have the following in home.php **(the key issue here is how the class attribute is on its own line)**:
```
<main id="content">
  <div
    class="test"
  >
    hello
  </div>
</main>
```

That works fine.

Now let's say instead of using the "main" element, you change it to a "div" in both files, like this:

_main.php:
```
<div id="content">
</div>
```

home.php (remember, class="test" is on its own line):
```
<div id="content">
  <div
    class="test"
  >
    hello
  </div>
</div>
```

That will cause MarkupRegions to incorrectly parse the html leading to stray divs at the very beginning of output.

If I were to put a single space after "<div", then it will work correctly.

**Comment by ryancramerdesign** [comment] 2019-03-26 14:17
@jlahijani Are you sure this is related to FileCompiler? That's something completely separate from MarkupRegions. MarkupRegions don't support tags split up on multiple lines like that, though it appears that the tag causing the issue is not one you are using to define or populate a markup region, so we should be able to fix it. But before I investigate further, I just want to make sure I understand what you meant about FileCompiler, as I'm not sure why that would be connected to this particular issue? Thanks.

**Comment by ryancramerdesign** [comment] 2019-03-26 14:18
You can test if it's got something to do with FileCompiler by placing a `<?php namespace ProcessWire; ?>` at the top of your file. When present, FileCompiler will ignore the file.

**Comment by jlahijani** [comment] 2019-03-26 16:02
Yes, I meant to say markupregions.

**Comment by ryancramerdesign** [comment] 2019-03-28 09:53
Thanks @jlahijani I've pushed a fix for this issue

**Closed as completed** 2019-04-07 16:20 UTC
Labels: resolution: fixed-please close
