### ISSUE TITLE
&#8232; encoding

### ISSUE THREAD

**Issue by TomS-** [processwire/processwire-issues#766] opened 2018-12-10 14:40 UTC
### Short description of the issue
Often on ProcessWire when working from a document, the encoded line return is remaining when saved to the database. This will show "L Sep" (Line Separator) boxes showing. This isn't noticeable on mac but shows on Windows Machines. I believe the HTML Entity Encoder should either:
1. Remove the L Sep
2. Replace L Sep to <br/>

I feel like the first option is better as L Sep's could appear on things that aren't meant to be across multiple lines such as a Title field. 

### Expected behavior

L Sep's should be removed.

### Actual behavior

They remain.

**Comment by postscript-chris** [comment] 2018-12-14 00:03
Yes I have come across this before. Particularly when copying and pasting from Sketch. Annoyingly doesn't show on Mac but does on Windows. Not sure this is a Processwire issue to fix though, maybe a CKEditor issue.

**Comment by TomS-** [comment] 2018-12-14 01:51
@postscript-chris it will happen on any field. It's not being sanatized before storing into the database.

**Comment by ryancramerdesign** [comment] 2018-12-14 10:43
I don't understand where the line separator is coming from, any idea? It sounds like you are even seeing it in single-line text fields (like title)? ProcessWire doesn't add this character, so I'm wondering what the source of it is. Does it only appear in text pasted from another application? Does it only appear at the end of the text, or does it appear elsewhere? We could certainly trim/remove it, though ideally I'd like to know how to reproduce it first.

**Comment by postscript-chris** [comment] 2018-12-14 11:21
Try  this  on  Windows

The above was copy and pasted from a Sketch file supplied to us.

**Comment by TomS-** [comment] 2018-12-14 14:16
@postscript-chris I can see the characters on my mobile phone, including the email that came through with it.

**Comment by ryancramerdesign** [comment] 2018-12-14 15:39
I can see from my mobile phone as well (Android), but not on my computer. I'm not sure that PW should be stripping out valid UTF-8, though maybe in this case there's no legitimate purpose for it to exist in single-line text fields at least. So I'm happy to strip it out. But can you confirm that this is coming from copy-paste, and not being introduced in some other way? For instance, it's not coming from an accidental FTP transfer of PW /wire/ directory files using ASCII mode or something?

**Comment by postscript-chris** [comment] 2018-12-14 15:48
For me this is 100% copy and paste, I think CKEditor must be stripping it?

**Comment by TomS-** [comment] 2018-12-14 16:41
> Seems like the above is stripping the rogue character from copy and pasting it from here. Could be a difficult one to track down.

It seems that Github doesn't have an issue hiding the character on Windows? My website is encoded in utf-8 like Github, so it's hard to see exactly how Github are hiding it as it still appears in DOM. I still think since this character doesn't seem to be supported on web or if it is, it will be a very rare case. The easiest solution is to strip it. Especially as it could throw confusion while coding. Let's say you wanted to do something based on character count.

It could be an interesting debate on whether we sanitise it or not. Personally I think I may be in favour of it being a text formatter.

**Comment by postscript-chris** [comment] 2018-12-14 16:55
Very true, I completely forgot about character count, even though in my most recent project this was a problem. I was counting characters so text fits in perfect circles, and this was adding to the count.

**Comment by ryancramerdesign** [comment] 2018-12-14 17:00
I'm thinking this should be added to the $sanitizer->text() formatter, which all PW input text (and non-HTML textarea) runs through. But before I do that, just wondering if there is any legitimate use of the &#8232; ... like what do those programs that you mentioned use it for? Also what should it be replaced with? A newline, space, or just removed completely?

**Comment by TomS-** [comment] 2018-12-14 17:51
@ryancramerdesign

Software uses it for a line return. So technically its a line return. So the rule would be, if its multiline replace with line return otherwise remove it. 

However since browsers do not support it, I should imagine unless multiline fields have some JavaScript to replace it on paste it would mess with the formatting from the backend to the front end or will reformat on save. Which maybe undesired.

I guess the safest solution would be to just remove it. As that will have the most consistency.

**Comment by ryancramerdesign** [comment] 2018-12-14 18:10
@TomS- I've pushed an update to Sanitizer that removes the UTF-8 version of that character via the text() function. In order for it to remove it, you would have to save a page containing the value somewhere. Please let me know how it works for you. Thanks.

**Comment by TomS-** [comment] 2018-12-17 10:01
@ryancramerdesign 

I have a Textarea which is "Unknown/Text" with "HTML Entity Encoder" applied (I think because it's a TextArea even though the content type is set to Text is not running through the Text Sanitizer. This does not remove the "L SEP" however, if I use "$sanitizer->text()" on the output, the "L SEP" is removed.

I tried it on a single line and it is removed. So it's working, just that small bug.

**Comment by ryancramerdesign** [comment] 2018-12-19 20:19
Just took a closer look and the text() and textarea() sanitizers are only used in certain input scenarios by InputfieldText and InputfieldTextarea, so most likely the case you are seeing is one where it is not used. For textarea with Unknown content type, it may be problematic for us to make assumptions about what it's being used for. And when we do find the right scenario to remove that lsep, then we should probably also remove the 30+ other types of UTF-8 whitespaces that would better be represented by a regular space in text/markup context. So I will work on this further, but this is an update I'd like to test on the dev branch for awhile since there may be side effects for others, so going to get the next master version out, and then revisit this.

**Comment by netcarver** [comment] 2019-03-05 22:21
@ryancramerdesign Any update on this? How did the testing go?

**Comment by ryancramerdesign** [comment] 2019-03-08 15:08
@netcarver I don't remember specifically, but do remember adding code to remove UTF-8 whitespace and added new methods in sanitizer, etc. I was never able to actually duplicate the issue on my own, so not positive if it is already resolved or not. @TomS- are you still experiencing the issue on the current dev branch?

**Comment by TomS-** [comment] 2019-03-08 15:13
@ryancramerdesign L SEP are removed from text but not textarea. I've also noticed L SEP's appear on the ProcessWire website - https://processwire.com/docs/start/templates/ under the code examples. 

You can user BrowserStack under Chrome windows 10 to see these "L SEP" happy to share logins if you need them.

**Comment by ryancramerdesign** [comment] 2019-03-19 10:01
Thanks @TomS- having that link really helped. While I still couldn't see it, I could replace it with the text "LSEP" and then could see it. I have updated FieldtypeTextarea to remove that character when in HTML content-type mode. I've also updated InputfieldCKEditor to remove it as well at input time. Presumably there's no value in this whitespace character when it comes to HTML.

**Comment by netcarver** [comment] 2019-03-29 17:31
@TomS- Tom, I'm closing this one now. Please post more if needed.

**Comment by TomS-** [comment] 2019-04-03 16:43
@netcarver this is still an issue and needs to remain open. If you copy and paste into a textarea that isn't set to HTML (let's say you don't want your clients to have control over things like style/weight and just want to output plain text in which you style in HTML) LSEPS are still there.

**Comment by ryancramerdesign** [comment] 2019-04-16 14:52
@TomS- @netcarver If the content-type is set to "unknown" it's not supposed to perform any conversion on the text. After all, someone might be intending for an LSEP to be stored here. Whereas we can pretty safely assume that they don't want it to be stored with a content type of HTML since LSEP has no purpose there. What I would suggest is using the HTML content type for this purpose, but you can always continue to have the HTML entity encoder enabled so that one can't actually output HTML.

**Closed** 2019-04-17 09:00 UTC
Labels: resolution: fixed (close when ready)
