### ISSUE TITLE
Custom image fields not saving in repeater item

### ISSUE THREAD

**Issue by kiwigringo** [processwire/processwire-issues#1391] opened 2021-05-29 03:27 UTC
### Short description of the issue

Image Field in a repeater does not save custom fields to database (filedata SQL field of image field table in database).

### Expected behavior

Saving page with repeater will save custom image fields to database.

### Actual behavior

With ProcessWire version 3.0.169, when a new repeater item with an image field with custom fields is added, on the first save, custom image fields are not saved, but subsequent saves result in the custom fields being saved.

With version 3.0.178 and 3.0.179, custom image fields are never saved, even on subsequent saves of a page containing the repeater.

An image field on the same page that is not in a repeater item saves custom fields as expected.

### Steps to reproduce the issue

1. Add custom fields to an image field as described here: https://processwire.com/blog/posts/pw-3.0.142/#custom-fields-for-files-images
2. Add the image field to a repeater field
3. Add both the image field and the repeater field containing the image field to a template.
4. Create a page using the template, and add an image to the image field directly on the page, and to a repeater item on the page.
5. Save the page and verify that the custom image fields for the field added directly to the page have saved.
6. Try to add content to the custom image fields of the repeater and save again, and note that no data is saved to database.

### Setup/Environment

* ProcessWire version: >= 3.0.178
* PHP version: 7.4.x
* MySQL version: MariaDB 10.2.38
*  Any 3rd party modules that are installed and could be related to the issue: Multilanguage is NOT installed.

**Comment by Toutouwai** [comment] 2021-05-29 04:08
Duplicate of #1070 ?

**Comment by kiwigringo** [comment] 2021-05-29 04:28
> Duplicate of #1070 ?
Quote from #1070 
"If I perform a page save first, then fill in the image custom data, do page save again, then all gets saved."
That was my experience with 3.0.169, but I didn't report it because it was still possible to save the data in a repeater item on second and subsequent saves of the repeater item.
It wasn't ideal, but there was a way to save the data.
With > 3.0.178 the data doesn't save at all.
(I'm not sure about other versions > 3.0.169 and < 3.0.178 as I haven't tested them)

**Comment by chriswthomson** [comment] 2021-06-01 09:18
I'm also experiencing this on 3.0.179. Pageimages field on a RepeaterMatrix item (named _images). Doesn't save at all. 

Additionally I'm getting an odd issue where I'm prevented from typing in the custom fields after the initial upload, prior to saving the page. I presume it is javascript doing this, the input itself is not disabled.

This isn't a duplicate of #1070, it is related but much worse!

To remedy on a current development (using the dev branch) I've reverted to the latest master, partially solving the saving issue, although reintroducing the bug highlighted in #1070.

**Comment by kiwigringo** [comment] 2021-06-03 04:26
I've narrowed this down to an issue in InputfieldFile.module Reverting to the version in 3.0.169 while leaving all the rest of 3.0.179 unchanged restores the ability to save data on second or subsequent saves, although the issue in #1070 remains.
I can see there was a recent PR commit to enable file metadata in repeater context, and I suspect this may have broken something.
Both files have the same module version number 126, but they have different file sizes, and number of lines.

**Comment by ryancramerdesign** [comment] 2021-06-18 15:01
@kiwigringo @chriswthomson Can you try the latest commit on the dev branch? I just pushed some updates to add support for more Fieldtypes in file/image custom fields when used in repeaters (like JS-based ones such as PageAutocomplete, etc.), and I think it may also fix the issues you've seen here. At least in testing, I had it all working within repeater items. Though it's possible my setup is different from yours, so please let me know what you find, thanks.

**Comment by chriswthomson** [comment] 2021-06-24 08:14
Thanks @ryancramerdesign, I can confirm this has resolved the issues for me.

**Comment by kiwigringo** [comment] 2021-06-24 08:33
@ryancramerdesign  I haven't had time to test a new page yet, but I can confirm that updating existing repeater items saves fields as expected, so presumably new repeaters should work.

**Comment by netcarver** [comment] 2021-06-24 12:43
@kiwigringo @chriswthomson I'm going to close this now. If you need it re-opened, just post in here again.

**Closed as completed by netcarver** 2021-06-24 12:43 UTC
