### ISSUE TITLE
ProcessWire 3.x Installer Error on latest dev version 3.0.185

### ISSUE THREAD

**Issue by trk** [processwire/processwire-issues#1444] opened 2021-10-02 14:04 UTC
When i try to install latest dev version (v3.0.185) for testing, getting error.

Site profile : `site-languages`

`Hey now… Error: Exception: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'page_path_history.language_id' in 'field list' (in wire/core/WireDatabasePDOStatement.php line 166)`

![Ekran Resmi 2021-10-02 17 00 03](https://user-images.githubusercontent.com/455983/135719613-3cd2ec25-5187-4677-af50-9b84fcc69410.png)

**Comment by adrianbj** [comment] 2021-10-02 16:08
I got this similar error

![image](https://user-images.githubusercontent.com/871211/135724180-f8ceacf0-da4a-413a-81d2-48a370bfdf0d.png)

**Comment by adrianbj** [comment] 2021-10-03 00:45
Me too!

**Comment by ryancramerdesign** [comment] 2021-10-04 12:30
Thanks @trk @adrianbj I've pushed a fix for this issue.

**Comment by adrianbj** [comment] 2021-10-04 15:14
Sorry @ryancramerdesign - the only catch with that fix isn't that it doesn't work for existing installs on the buggy version. Obviously it's an easy manual fix, but something to be aware of if others report this.

**Comment by ryancramerdesign** [comment] 2021-10-04 15:19
@adrianbj Why wouldn't it work with existing installs? If I understand correctly, the issue is a missing language_id column, and existing installs would already have that present.

**Comment by adrianbj** [comment] 2021-10-04 15:45
@ryancramerdesign - I am talking about those of us who have installed the latest dev prior to this fix. I don't believe there is any mechanism to update the DB to add that language_id column. It certainly didn't add it in my test. It did however work when upgrading a site directly from 3.0.184 to the very latest version with the change to the DB schema.

Does that make sense, or am I missing something?

**Comment by ryancramerdesign** [comment] 2021-10-04 16:14
@adrianbj The module that generated the error here (PagePathHistory) hasn't had a change in schema, as the language_id column was added almost 7 years ago (in 3.0.7). But for site profiles that had the module installed that long ago, they didn't have the updated schema in the install.sql file. I updated the core profiles .sql files to add it. Usually it wouldn't be necessary (since it updates itself), but PagePathHistory just gets used much earlier in the boot process now, before a modules refresh could fix it. Though there's also now a try/catch that should prevent that issue too. But if you are still seeing the issue, please let me know how to duplicate it and I can keep debugging here.

**Comment by adrianbj** [comment] 2021-10-04 16:54
@ryancramerdesign - a Modules > Refresh doesn't fix things here. The DB table still doesn't have that field:

![image](https://user-images.githubusercontent.com/871211/135891688-1be86ac4-9573-4def-957f-a124a7139b56.png)

Not sure what to tell you in terms of duplicating things. I just upgraded a site from 3.0.184 to 3.0.185 and now visiting the frontend results in that error. 

I just had a look at several of my sites (on 3.0.184) and none of them have that language_id field.

**Comment by ryancramerdesign** [comment] 2021-10-04 17:29
@adrianbj Are you sure the PagePathHistory module is installed? Since I can't duplicate the issue on any of my installs, I think maybe best bet is to wait till someone else runs into it and then we can try to find out what's common among those installs. There have been a lot of code changes, so it may be this error is a side effect rather than the source.

**Comment by adrianbj** [comment] 2021-10-04 17:46
Yep, definitely installed (as it is on all my sites). Surely the screenshot of the page_path_history table above shows that it is?

I see that the install method in PagePathHistory.module creates the `page_path_history` table with the `language_id` field, but the upgrade method only adds the language_id field if `$fromVersion == 1`. For me, the module is already at v0.0.6 so the upgrade isn't triggered and the `language_id` field isn't added.

Maybe this is a historical issue that won't affect newer users, but I think for me it means manually adding that field to all my installs.

**Closed as completed** 2021-10-07 10:33 UTC
Labels: resolution: fixed-please close
