### ISSUE TITLE
SQL Error when finding pages with full-text search on InnoDB

### ISSUE THREAD

**Issue by valieand** [processwire/processwire-issues#190] opened 2017-02-17 16:21 UTC
### Short description of the issue

SQL Error when finding pages with full-text search on InnoDB:
wire('pages')->find('title|body*="колодки"|"масло"');

I can't check it now, but the same seem to work Ok in MyISAM.

### Expected behavior

Pages should be returned

### Actual behavior

> SQLSTATE[42000]: Syntax error or access violation: 1064 syntax error, unexpected '+', expecting FTS_TERM or FTS_NUMB or '*'

### Optional: Suggestion for a possible fix
I think that this issue is InnoDB-specific. Look here: https://dev.mysql.com/doc/refman/5.6/en/fulltext-boolean.html

### Steps to reproduce the issue
1. Switch your PW to InnoDB (all tables).
2. Run wire('pages')->find('title|body*="колодки"|"масло"');
3. Get SQL error

### Setup/Environment
PW 2.8.35
PHP 7.0.14
MySQL 5.7.14

**Comment by ryancramerdesign** [comment] 2017-03-07 15:57
I can't duplicate this one, and have tested with the exact terms. I'm running on InnoDB and charset utf8mb4. You might want to check your table charset and make sure it's either utf8 or utf8mb4. Do you see the error regardless of terms, or is it just those words "колодки"|"масло" ? See if you can narrow in on what works, like removing the OR conditions one at a time.

**Comment by adamspruijt** [comment] 2017-03-09 18:47
I get this error Ryan, though I only get it when using an array selector with a term that has an apostrophe.

**Example**:
`$query = $sanitizer->selectorValue( "Lundy's Lane");`

`//get matches (this doesn't work)`
`$results = $pages->find([`
`	"limit" => 10,`
`	"indexer*=" => $query`
`]);`

`// this does`
`$results = $pages->find("limit=10,title*=$query");`

**Comment by valieand** [comment] 2017-03-10 09:42
@ryancramerdesign thanks for ideas on possible causes.

> You might want to check your table charset and make sure it's either utf8 or utf8mb4.

Server charset UTF-8 Unicode (utf8), tables collation utf8_general_ci

> Do you see the error regardless of terms, or is it just those words "колодки"|"масло" ? 

I've seen error regardless of terms, but may be its because I've used russian words only.

> See if you can narrow in on what works, like removing the OR conditions one at a time.

W/o OR condition it worked. Currently I use workaround - joining find results.

I need to mention that words "колодки"|"масло" come from user input -> trim -> remove whitespaces -> $sanitizer->text() each, then implode to one string and $sanitizer->selectorValue(). E.g. may be smth happens with chars during these operations, even if final string "колодки"|"масло" looks ok.

**Comment by ryancramerdesign** [comment] 2017-03-14 19:34
It shouldn't matter if the word is Russian or not. At first I was thinking maybe it's possible one of those chars was a 4-byte UTF8, which MySQL's regular UTF8 charset doesn't support. But I went ahead and tested on a regular UTF8 install here and also could not reproduce the issue. Now I'm thinking perhaps it's something with the 2.8 version that you are using. I'll try to update that 2.8 version soon. 

@adamspruijt using an array means the selectorValue() call is already implied, so you'd want to leave that out in your array version. It's not working because the value is getting double escaped.

**Comment by adamspruijt** [comment] 2017-03-29 13:36
@ryancramerdesign thanks Ryan, I will keep that in mind.

**Comment by adamspruijt** [comment] 2017-09-19 19:29
@ryancramerdesign Sorry, but I still get this error when using 

`$sanitizer->text()`

I am on:

- MariaDB 10.3
- InnoDB 
- utf8_general_ci

Easiest way to trigger is using a string with two double quotes in a search, ie:
test search "" 

This only happens when using the exact phrase selector  ( *= ) and not the equivalent LIKE versions ( %= ).

Also from a quick test as @valieand indicated the error goes away when using MyISAM

**Comment by ryancramerdesign** [comment] 2019-03-28 16:17
Closing this one because I still can't reproduce after many tries and more than 2 years after initial report. If still experiencing after testing on PW 3.0.123 or newer, please re-open with additional details on how to reproduce. Thanks.

**Closed by ryancramerdesign** 2019-03-28 16:17 UTC
Labels: status: impacts multiple users, status: not reproducible

**Comment by adrianbj** [comment] 2019-03-28 16:30
@ryancramerdesign - I just did some tests on an install with MyISAM vs one with INNODB, both with and without an apostrophe in the sanitized selector:

![image](https://user-images.githubusercontent.com/871211/55174967-ab472e80-513b-11e9-80f2-1ab2e6029820.png)

![image](https://user-images.githubusercontent.com/871211/55175010-bef29500-513b-11e9-93d2-686d42c88486.png)

![image](https://user-images.githubusercontent.com/871211/55175075-dd589080-513b-11e9-86c4-2eaad24c6069.png)

Can you reproduce these?

**Comment by ryancramerdesign** [comment] 2019-03-28 16:47
@adrianbj I'm sure I would be able to reproduce that because I can see that it would fail because it's stuffing the result of a selectorValue() call into a selector array. The primary purpose of using a selector array is that it handles that business for you. The selectorValue() is for string selectors, so using it with an array selector will definitely fail.

**Comment by adrianbj** [comment] 2019-03-28 16:52
Fair enough - sorry I was just playing with the example that @spruijtdesign design provided. 
Is it strange though that it works with MyISAM even though it's not meant to work? 

I must admit though that I think it's weird that the array approach handles sanitizing and the string approach doesn't - that's going to be hard for users to remember. I knew this, but forgot about it in this moment.

**Comment by ryancramerdesign** [comment] 2019-03-28 17:56
> Is it strange though that it works with MyISAM even though it's not meant to work?

It makes sense actually because MyISAM and InnoDB have differences in their FULLTEXT indexes, and MyISAM's is more mature as far as I know. I think that MyISAM indexes quotes in fulltext indexes, but it looks like InnoDB does not. 

I actually think this reveals a potentially useful thing here though. The `*=` operator matches partial words and phrases. Having explicit quotes around the value to match could be a way of telling it to perform an exact phrase match (like in Google when quoting a value) rather than partial phrase match. That's not something we currently have the ability to specify, and supporting it in this manner would be more useful than the current error or non-match.

> I must admit though that I think it's weird that the array approach handles sanitizing and the string approach doesn't - that's going to be hard for users to remember.

If it's in a string, it's not possible for it to happen automatically. Think of a selector string like an SQL statement string, and think of a selector array like bound SQL parameters. If you aren't using bound parameters, then you need to escape/sanitize whatever you put into the SQL statement. If you don't, then there's no way for the engine to know if a quote is terminating a value or part of a value.  The same applies to selector strings. The selectorValue() does for selector strings what PDO::quote() does for SQL statements. And selector arrays effectively do the same thing as bound parameters, and that's why they exist. (I mostly use selector strings still though.)

**Comment by adrianbj** [comment] 2019-03-28 18:06
Glad that brought up a possibility for improved quoted matching!

> If it's in a string, it's not possible for it to happen automatically. 

Yeah, I understand why it's not possible in a string. I tried using selector arrays in a few projects, but I always came up against some scenario where they don't work, so I I have decided not to bother anymore. I think it's better practice to create your own normal array and then `implode()` into a string. That way you get clarity in building the selector, without the limitations of the selector array approach. Sorry, getting OT now :)
