### ISSUE TITLE
Select dropdown with input field dependencies unfocuses itself a second after a dependent field is changed.

### ISSUE THREAD

**Issue by CaelanStewart** [processwire/processwire-issues#124] opened 2016-12-20 17:08 UTC
### Short description of the issue

On a template with input field dependencies on, a select dropdown (for instance) will unfocus itself a second after I've opened it if I've just changed another field. I encounter the issue all the time, since I tend to make heavy use of input field dependencies, and it's quite annoying as I'm quite fast when traversing ProcessWire's user interface, and I keep getting my flow interrupted when this happens.

### Expected behavior

The select box should stay open if I've opened it.

### Actual behavior

If I change a field on the page, and then quickly open a select dropdown afterwards, it unfocuses a second later.

### Steps to reproduce the issue

1. Create a template
2. Create an Options field and populate it
3. Make the visibility of that Options field be determined by the value of another field
4. Change the other field
5. Quickly open the Options field select dropdown
6. Watch it unfocus itself a second later

### Setup/Environment

* ProcessWire version: 3.0.42 (affects all prior versions I've used with input field dependency support)

**Comment by ryancramerdesign** [comment] 2016-12-26 16:20
I can't duplicate this one, or maybe I'm just not fast enough to catch it. But I think what you may be seeing is the size adjustments that are made to Inputfields to accommodate a new item appearing in the form. That shouldn't cause a field to be unfocused, at least not that I've been able to catch (Chrome), but maybe it does in some browsers (?). If the field that's revealed has a width that's less than 100%, you might try changing it to be 100%, as that should limit any DOM changes and might prevent the issue you are observing. However, if your revealed field width is already 100%, I'm not sure there would be a way around it.

**Comment by netcarver** [comment] 2018-07-27 11:17
@CaelanStewart Hi Caelan, I know this is an old issue, but can you still reproduce this in the current codebase or perhaps you can provide a little more detail about which browser you were using? Also, if this is no longer relevant, can it be closed?

**Comment by Toutouwai** [comment] 2018-07-27 22:17
This issue still occurs in AdminThemeDefault. You can see it in action in the screencast below.

![select-issue](https://user-images.githubusercontent.com/1538852/43348499-6bc4a1c2-924e-11e8-8361-3d35a2f83ae9.gif)

The issue is caused by the `setHeight()` function in /wire/templates-admin/scripts/inputfields.js. So to see the issue occur you need to have your inputfield dependencies set up in such a way that a taller inputfield is made visible in the same row, causing the height of the select field to adjust.

The culprit is the hide() and show() [here](https://github.com/processwire/processwire/blob/c01289edb7ad650bb635e412b490e8db8fe91989/wire/templates-admin/scripts/inputfields.js#L724) and [here](https://github.com/processwire/processwire/blob/c01289edb7ad650bb635e412b490e8db8fe91989/wire/templates-admin/scripts/inputfields.js#L726), which is also responsible for an [old issue](https://github.com/ryancramerdesign/ProcessWire/issues/1426) that I believe is still unfixed.

As far as I can see the hiding and subsequent showing of the inputfield is unnecessary. Commenting out those lines fixes this issue.

**Comment by netcarver** [comment] 2018-07-27 22:41
@Toutouwai Thanks for the confirmation, and the pointers!

**Comment by netcarver** [comment] 2019-02-16 20:16
/remind me to review this issue in 2 weeks

**Comment by ryancramerdesign** [comment] 2019-03-04 16:02
Thanks @Toutouwai for tracking that one down. I have added your suggested fix, removing the hide/show, which I agree doesn't seem necessary.

**Comment by netcarver** [comment] 2019-03-07 12:36
@Toutouwai @CaelanStewart Can this issue be closed now?

**Comment by netcarver** [comment] 2019-03-14 20:40
Ok, closing this. Please post more if needed.

**Closed by netcarver** 2019-03-14 20:41 UTC
Labels: resolution: fixed (close when ready), status: discussion, status: impacts multiple users
