### ISSUE TITLE
Adding attributes/classes to non-text fields via API doesn't work

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-issues#1095] opened 2020-02-22 16:23 UTC
### Short description of the issue

If you try `addClass()` or `attr()` to inputfield types other than regular text inputs, they don't work.

### Expected behavior

Not sure why they shouldn't work.

### Actual behavior

See how the `uk-hidden` class is successfully applied to the "body" field (a textarea inputfield), but it doesn't get applied to the "pagetest" field (a select inputfield).

Same goes for trying to add attributes, etc.

![image](https://user-images.githubusercontent.com/871211/75095679-52029d80-554c-11ea-82b9-777e9b895cba.png)

**Comment by ryancramerdesign** [comment] 2021-08-13 15:13
@adrianbj Not all Inputfields support custom attributes and classes, though single-input ones do. So what you are trying to do should work most of the time. I just tested with InputfieldSelect on its own, and it did work. I also tested with a Page field using InputfieldSelect and it also got the "uk-hidden" class in the output. So if it wasn't working before, it seems to be working now.

**Comment by matjazpotocnik** [comment] 2022-05-08 06:11
@adrianbj I can confirm that "uk-hidden" class is applied to InputfieldSelect, but tracy adds their own styles overriding the "display: hidden!important" with "display: inline-block!important"

![image](https://user-images.githubusercontent.com/7663992/167284176-38e81675-3620-4439-9882-45e8a9dff7a1.png)

**Comment by matjazpotocnik** [comment] 2022-05-30 16:57
@adrianbj Adrian, closing this. Please comment again if you need it re-opening.

**Closed as completed by matjazpotocnik** 2022-05-30 16:57 UTC
Labels: status: can't reproduce
