### ISSUE TITLE
Page Front-end Editor Has Bugs In Master Clean Install

### ISSUE THREAD

**Issue by denisurn** [processwire/processwire-issues#609] opened 2018-05-31 09:27 UTC
### Short description of the issue

In latest master clean install Page Frontend Editor module throws quite a few bugs and errors.

### Expected behavior

- logged in user opens modal to edit some fields on the front end
- user saves his changes and pressing save button closes the modal
- changes are seen on the page

### Actual behavior

- user opens the modal;
- javascript console throws few errors (which could be the culprit);
- ajax preloader does not disappear;
- pressing save button does not close the modal (data-autoclose does not work);
- field changes are saved, but are not visible until manual page refresh;

Actual behavior goes here.

### Screenshots/Links that demonstrate the issue

[Firefox console](http://prntscr.com/joxvho)
[Persistent ajax preloader] (https://screenshots.firefox.com/xXPjZgsD7DX0Z4rC/clean.local)

### Steps to reproduce the issue

1. Do a clean install of the latest PW master;
2. Enable/install Page Front End Editor module;
3. Add <edit> tag to the home template `<edit page="<?=$page->id?>" fields="title,body">test modal</edit>`
4. Try to open the modal and save fields. Check the browser console for Jquery errors.

### Setup/Environment

XAMPP, MAMP, tested in latest Firefox and Safari.

* ProcessWire version: 3.0.98
* Jquery Core module version: 1.8.3

**Comment by ryancramerdesign** [comment] 2018-06-01 10:05
I'm not able to duplicate the issue in either Chrome or Firefox. However, the error seems to indicate jQuery isn't available, so I'm thinking it might have more to do with the front-end environment. Which site profile are you seeing it in? Perhaps PageFrontEdit is detecting that jQuery is present, when it isn't.

**Comment by denisurn** [comment] 2018-06-01 12:00
I am using minimal site profile to reproduce.

Is it possible to see you "Network" output? Mine is here (after opening the modal)

[browser network output](http://prntscr.com/jphi07)

All responses are fine (contain actual javascript response). Is there a file missing then?

**Comment by markosiilak** [comment] 2018-06-01 12:11
Same issue here with "Steps to reproduce the issue"
I also Installed latest master with multi language profile installer.
I got a same error: at HTMLIFrameElement.u (JqueryCore.js:2)

**Comment by matjazpotocnik** [comment] 2018-06-01 12:11
I'm testing on existing installation. This is my html:

```
<!doctype html>
<html>
	<head></head>
	<body>	
		<edit fields="title,integer_field">test modal</edit>	
	</body>
</html>

```
js files loaded:

http://localhost/wire/modules/Page/PageFrontEdit/PageFrontEditLoad.js?NoMinify=1
http://localhost/wire/modules/Jquery/JqueryCore/JqueryCore.js
http://localhost/wire/modules/Jquery/JqueryUI/JqueryUI.js
http://localhost/wire/modules/Page/PageFrontEdit/PageFrontEdit.js?nc=1527818150

On dblclick other files are loaded, then it fail on this line in modal.js:

`var k = $("<textarea />").text(h.contents().find("title").text()).html();`

**Comment by denisurn** [comment] 2018-06-01 12:28
@ryancramerdesign I think that @matjazpotocnik solution could be the bugfix. Tested, fixed the issue.

**Comment by denisurn** [comment] 2018-06-04 13:21
Also, this line `var abort = typeof event.toElement != "undefined" && jQuery(event.toElement).hasClass('fa-times');` is always false in Firefox (FF does not have toElement).
Solution would be to replace it with event.relatedTarget.

**Comment by denisurn** [comment] 2018-06-04 13:39
`jQuery(event.toElement).hasClass('fa-times')` also does not always work as sometimes a user clicks on the outer <button>
There should definitely be an improvement on how the modal is closed with "x"

**Comment by denisurn** [comment] 2018-06-04 14:23
Also, when a modal window is closed, it is hidden, rather than destroyed. And when the modal is re-opened, it creates new element, rather than makes the old one visible.

Therefore, opening a new modal results in two elements with the same ID, which could potentially have other issues.

**Comment by denisurn** [comment] 2018-06-06 08:21
`var abort = typeof event.originalEvent != "undefined" && (jQuery(event.originalEvent.target).hasClass('fa-times') || jQuery(event.originalEvent.target).hasClass('ui-dialog-titlebar-close'));`

Here is my solution for 'abort' result 'false' in FF. Tested in FF, Chrome and Edge.

**Comment by matjazpotocnik** [comment] 2018-06-06 11:16
Hmm, JqueryCore.js is not loaded at all, but it should be loaded before any other scripts...

**Comment by matjazpotocnik** [comment] 2018-06-08 16:29
I found out why I had so many troubles with PFE. I was using $config->styles and $config->scripts on frontend in my templates. PFE injects assets (js scripts) using $inputfield->renderReady() method and I echoed those scripts, but jQuery wasn't there yet. So I modified my template rendering and PFE is working. Of course, those bugs that denisurn mentioned are still there...

**Comment by ryancramerdesign** [comment] 2018-06-12 11:46
Thanks @denisurn and @matjazpotocnik, nice work. I've pushed several updates to PageFrontEdit per the fixes mentioned above (and a couple others).

**Comment by schwaaab** [comment] 2018-06-29 17:16
It's working, but not with jQuery 3.3.1, which I used. With the jQuery version from the module, it works as expected.

I guess it's time to upgrade from jQuery 1.11.1 to a more recent version. This problem will only appear more and more.

**Comment by schwaaab** [comment] 2018-06-29 17:21
Hitting enter instead of clicking save while editing in the modal does not close the modal. The whole admin page gets loaded in the modal in that case.

I don't know if this was always the case, but it feels wrong.

**Comment by matjazpotocnik** [comment] 2018-07-02 17:06
@schwaaab, In my testing it's working with option A, eg. inline edit, but it doesn't work with modal. You must use  jQuery migrate (jquery-migrate-3.0.1.min.js) or use older jquery. Ryan doesn't want to upgrade jquery (yet).

@ryancramerdesign it would be good to replace deprecated functions in modal.js (.onload() and .resize()) with .on() function.

I tried upgrading jqueryui to jquery-ui-1.12.1.min.js but there are several problems.

**Comment by matjazpotocnik** [comment] 2018-07-02 18:33
@schwaaab I tried with option C (`<edit fields="title,body">test modal</edit>`) and D (`<div edit="title,body">test modal</div>`) using jquery-3.3.1.min.js and jquery-migrate-3.0.1.js in my frontend `<head>`tag and it's working without problems as far as opening the modal. I only use AdminThemeDefault so maybe you should specify what's wrong so Ryan can fix it? Enter key is not trigered so autoclose is false and the modal stays open. It can be fixed (I did it by using on submit event). Errors are displayed here, but not ideal, I agree. You can fix that by setting the html required field on fileld settings. You could also try FEEL and combine it with inline PFE.

**Comment by matjazpotocnik** [comment] 2018-07-04 07:49
I found out that modal.js is interfering with click events on `<a>` element within the pwModalDoubleClick() function. I have an image gallery using fancybox (I guess it could be any other image gallery that opens modal) and after the image is shown, `jQuery(document).on('click', '.pw-modal-dblclick a', function() {` kicks in and trigger another unwanted click on image...

**Comment by x02a** [comment] 2018-10-19 06:51
Same Problem(s) here, when using Bootstrap 4 with jQuery 3.2.1 :(

**Comment by thetuningspoon** [comment] 2019-01-10 17:18
I also have the modal issues in PW 3.0.110 when using jQuery 3+

**Comment by designconcepts** [comment] 2020-09-22 11:52
I also have issues with using Front-End editing for images and jQuery 3+. For example I get [this](https://github.com/vanderlee/colorpicker/issues/132) error.

Also after editing an image using Front-End editing without jQuery the replacement of the original image doesn't work on images inside a Repeater Matrix.

**Comment by eSlider** [comment] 2022-05-04 12:47
Dirty fix:

```javascript
jQuery.fn.extend({
  offset: function(options) {
    if(arguments.length) {
      return options === undefined ?
        this :
        this.each(function(i) {
          jQuery.offset.setOffset(this, options, i);
        });
    }
    return {top: 100, left: 100};
  }
});
```

**Comment by matjazpotocnik** [comment] 2023-06-20 05:38
@denisurn @markosiilak @zoeck-dev @thetuningspoon @designconcepts @eSlider there have been many updates to the core javascript libraries in the last months. Please check if this issue can be closed. Also, try with the `$config->debug = 'dev'` in your config.php. Thanks!

**Comment by designconcepts** [comment] 2023-06-20 08:50
I have briefly tested front-end editing with PW 3.0.220 and jQuery 3.7.0:

### Textareas

No JavaScript errors for editing textareas with jQuery 3.7.0 but still errors if you use the slim version of jQuery.

![Bildschirmfoto 2023-06-20 um 09 28 41](https://github.com/processwire/processwire-issues/assets/2794879/a792cacb-aae7-4146-af18-267b0bb4b587)

### Modals 

Still JavaScript errors for front-end editing with modals (for example images) with jQuery 3.7.0.

![Bildschirmfoto 2023-06-20 um 09 32 18](https://github.com/processwire/processwire-issues/assets/2794879/21ac5821-1890-4bec-813d-93793ccae1f4)


I guess the issue is that PW doesn't use the latest jQuery UI 1.13.2?

Regards, Andreas

**Comment by matjazpotocnik** [comment] 2023-06-20 08:59
PW uses jQuery UI 1.10.4 unless you specify $config->debug = 'true', then jQuery UI 1.13.2 is used (and jQuery v3.6.4). Would you mind testing this?

**Comment by designconcepts** [comment] 2023-06-20 09:20
Thank you @matjazpotocnik for the hint.

I already had debug mode activated, but changed it to $config->debug = 'dev', as mentioned [here](https://processwire.com/talk/topic/28406-pw-30215-%E2%80%93-core-updates-jquery-upgrades/).

Now when the page loads it still loads the older jQueryUI 1.10.4 and after I click on something with the attribut _edit="id.image"_ it loads the new jQueryUI 1.13.2 and still throws the same error.

![Bildschirmfoto 2023-06-20 um 11 14 34](https://github.com/processwire/processwire-issues/assets/2794879/d4c54031-090e-42da-bcab-d6ddb92cb801)

Maybe the PageFrontEditLoad.js script is loading the wrong version and the browser uses the first available version?

**Comment by matjazpotocnik** [comment] 2023-06-20 12:36
Ah, I see that PageFrontEdit module is not aware of dev versions. Can you modify /wire/modules/Page/PageFrontEdit/PageFrontEdit.module, line 815 and change it to:

`'file' => $config->urls('JqueryUI') . 'dev/JqueryUI.js',`

Or you can try to load jQueryUI manually, just like you load jQuery.js?

**Comment by designconcepts** [comment] 2023-06-20 13:31
Thank you @matjazpotocnik for pointing me to the right direction.

After modifying this line in the module file, I don't get an JavaScript error anymore when opening a modal with front-end editing.

After saving the modal I get an error and the saved element is not replaced, but it seems that the element also doesn't get replaced if I don't use jQuery in my front-end.

![Bildschirmfoto 2023-06-20 um 15 03 30](https://github.com/processwire/processwire-issues/assets/2794879/98345568-6155-4e1b-8674-6413c1ff864f)

**Comment by matjazpotocnik** [comment] 2023-06-20 13:49
If you don't use jQuery on frontend, then the module will load it, but again, the "old" version. Change line 801 to be `'file' => $config->urls('JqueryCore') . 'dev/JqueryCore.js',`

Can you show a minimal example of your template (html code) and how you have setup your template (just an ordinary image field?). Would like to test here localy. I tested with this in my basic-page template:

```html
<!doctype html>
<html>
	<head></head>
	<body>	
		<edit fields="datoteka">test modal</edit>	
	</body>
</html>
```

datoteka is FieldtypeFile.

**Comment by designconcepts** [comment] 2023-06-21 08:03
Hello @matjazpotocnik, I prefer [Option D: HTML edit attributes](https://processwire.com/docs/front-end/front-end-editing/#option-d-html-edit-attributes).

This would be my code for a template with a single image field called "image":

```html
<!doctype html>
<html>
    <head></head>
    <body>
        <!-- Option D-->
        <div edit="image">
            <img src="image.jpg" alt="Image">
        </div>
        <!-- Option C -->
        <edit field="image">
            <img src="image.jpg" alt="Image">
        </edit>
    </body>
</html>
```

But it seems that with or without jQuery, there seems to be an issue updating the front-end after saving the modal.

I always get the JavaScript error "Uncaught Error: Syntax error, unrecognized expression: /?pw_edit_fields=image #pw-edit-modal-....". There seems to be a space between "image" and the id "#pw-edit-...", but I couldn't figure out where in the module this space could be added. I guess it is in the modalRenderEditor-function.

Could you please test this?

**Comment by matjazpotocnik** [comment] 2023-06-21 09:49
Please edit PageFrontEdit.js, line 369, replace

`target.on('load', viewURL + ' #' + targetID, {}, function() {`

with 

`target.load(viewURL + ' #' + targetID, {}, function() {`

The slim version of jQuery probably won't do it, as it lacks support for ajax. The slim build is about 6k gzipped bytes smaller than the regular version; that shouldn't be a concern these days.

**Comment by designconcepts** [comment] 2023-06-21 11:35
Thank you @matjazpotocnik, you are awesome. 😄 

This line caused the JavaScript error. Now I am able to use front-end editing with modals again. If I save the modal the content gets replaced correct.

By looking at the new [target.on()](https://api.jquery.com/on/) event handler it seems correct, but there seems to be a difference to the the old [target.load()](https://api.jquery.com/load/) event handler.

**Comment by matjazpotocnik** [comment] 2023-06-21 11:41
Would you please test with "non-dev" version of jQuery and jQuery UI?

**Comment by designconcepts** [comment] 2023-06-21 12:00
Front-end editing modals works with the "non-dev" versions of JQueryCore.js and JQueryUI.js after the change in the PageFrontEdit.js. 👍

**Comment by matjazpotocnik** [comment] 2023-06-22 16:25
Thank you for testing. This [commit](https://github.com/processwire/processwire/commit/ead96474c6ec51abebf73fea5c19107f01801365) (along with many others regarding jQuery) fixes this issue, so I'm closing it. Please open a new issue if needed.

**Closed by matjazpotocnik** 2023-06-22 16:25 UTC
Labels: status: has suggested fix, status: multiple
