### ISSUE TITLE
Repeater doesn't take on item label when inside another repeater

### ISSUE THREAD

**Issue by TomS-** [processwire/processwire-issues#393] opened 2017-09-29 13:42 UTC
### Short description of the issue
Repeater doesn't take on the item label set in the field settings when it's inside another repeater. 

### Expected behavior
Should use the title that's provided in settings

### Actual behavior
Displays the name of the field. 

* ProcessWire version: 3.0.76

**Comment by Toutouwai** [comment] 2017-09-29 14:07
Duplicate of https://github.com/processwire/processwire-issues/issues/173

**Comment by netcarver** [comment] 2018-07-25 00:35
@TomS- Hi Tom, I see Ryan pushed a fix for this issue. The tag seems to be asking you to close the issue when ready. So, if you are happy with the fix, please could you close the issue. Thank you.

**Closed** 2018-07-25 15:02 UTC
Labels: resolution: fixed (close when ready)
