### ISSUE TITLE
Add Page: "Ok" icon forces Save button down

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#69] opened 2016-11-01 04:27 UTC
### Short description of the issue

This is a minor issue but one that irks me regularly. When adding a new page, the "Ok" icon that appears once the page name is checked forces the Save button downwards. 

Frequently this happens just as I am about to click "Save" and the button is shifted down out from under the mouse cursor - especially when the page title is pasted in rather than typed.

Also, the position of the "required" asterisk breaks to a new line which is a bit odd.

### Expected behavior

"Ok" icon does not affect button position.

### Actual behavior

"Ok" icon changes button position.

### Optional: Screenshots/Links that demonstrate the issue

![add1](https://cloud.githubusercontent.com/assets/1538852/19879444/7c8bdb14-a057-11e6-9298-19ebe21ac44a.png)
![add2](https://cloud.githubusercontent.com/assets/1538852/19879443/7c88c744-a057-11e6-921c-a748ed379dc7.png)

### Optional: Suggestion for a possible fix

Position "Ok" icon absolutely or use other positioning that does not cause elements below to change position.

### Steps to reproduce the issue

1. Paste in page title in "Add Page" screen
2. Watch "Save" button shift down

### Setup/Environment

* ProcessWire version: 3.0.39

**Comment by mikerockett** [comment] 2016-11-01 06:03
This is actually happening in all versions I've been working with: 2.7/8 and 3.0.

Perhaps this can be moved as a green badge next to the text above the input?

**Comment by gmclelland** [comment] 2016-11-01 16:08
Hmm... I'm not seeing this problem in ProcessWire 3.0.37.  What browser are you using?  I'm using Google Chrome 54 on a mac.

**Comment by mikerockett** [comment] 2016-11-01 18:59
Actually, I recall this happening on Firefox. I have since switched to chromium. Given the text antialiasing in that screenshot, it looks like that is FF. Well, at the least, it isn't blink-based.

**Comment by gmclelland** [comment] 2016-11-01 19:04
Confirmed, I can reproduce the issue using Firefox.

**Comment by gmclelland** [comment] 2016-11-01 19:10
I'm not quite sure yet where it is being added, but in Firefox the span with an id=ProcessPageAddStatus is receiving an inline style of display:block.  In Chrome this doesn't happen.

**Comment by gmclelland** [comment] 2016-11-01 19:20
Looks like it happening in wire/modules/Process/ProcessPageAdd/ProcessPageAdd.js or the min.js

Search for ProcessPageAddStatus

I'm still checking....

**Comment by gmclelland** [comment] 2016-11-01 19:40
Adding the following to wire/modules/Process/ProcessPageAdd/ProcessPageAdd.css fixes the problem:
`#ProcessPageAddStatus {
  display: inline !important;
}`

**Comment by gmclelland** [comment] 2016-11-01 19:47
Jquery is hiding a showing and showing the span#ProcessPageAddStatus which uses inline styles like display:none and display:block so you have to force it to use display:inline with the !important.

**Comment by Toutouwai** [comment] 2016-11-01 19:55
@gmclelland - thanks for investigating.
My screenshots above are indeed from Firefox, and the issue seems to be specific to this browser.

I think it's probably a jQuery bug. The [docs](http://api.jquery.com/show/) for show() say:

>  If an element has a display value of inline, then is hidden and shown, it will once again be displayed inline.

A span has a default display value of inline, so show() is not working as it should in Firefox. The version of jQuery used in the core is fairly old (1.8.3) - not sure if this issue has been corrected in more recent versions of jQuery.

**Comment by gmclelland** [comment] 2016-11-01 20:05
@Toutouwai - thanks, I noticed that as well.  I submitted a pull request here with the fix  https://github.com/processwire/processwire/pull/27

I tested it in Chrome and Firefox.

Hope that helps

**Comment by Toutouwai** [comment] 2016-11-01 22:46
Cool. That works because #ProcessPageAddStatus has no contents when it is appended, but note that it overrides the effect of the `hide()` and `show()` so those commands might as well be removed in that case.

Alternatively the CSS file could be left as-is and the `hide()` replaced with `css('display', 'none')` and `show()` replaced with `css('display', 'inline')`.

**Comment by mikerockett** [comment] 2016-11-02 04:16
@Toutouwai - I do remember jQuery changing this behaviour in more recent versions. So the older 1.x (and maybe even 2.x) versions would use `block`.

**Comment by gmclelland** [comment] 2016-11-02 15:58
@Toutouwai I agree we should use css('display', 'none') instead of show().  I'll update the pull request.

**Comment by ryancramerdesign** [comment] 2016-11-04 09:55
Thanks for finding the solution here guys. I'll close this one out since the PR has been added.

**Closed by ryancramerdesign** 2016-11-04 09:55 UTC
