### ISSUE TITLE
Cache + lot of urlSegments => file_put_contents error

### ISSUE THREAD

**Issue by Lazerproof** [processwire/processwire-issues#3] opened 2016-09-25 22:48 UTC
I have page "Products" with a lot of urlSegments:
`site.dev/products/pigs/antibiotics-injectable/antibiotics-external/antibiotics-oral-solutions/antiseptics-external/vaccines-live/feed-additives/disinfectants-and-hygiene/`

In config
`$config->maxUrlSegments = 12;`

Everything works great until I switch on cache for this page. 
After that I get: 
`file_put_contents(D:/Server/domains/localhost/site.dev/app/site/assets/cache/Page/3725/pigs+antibiotics-injectable+antibiotics-external+antibiotics-oral-solutions+antiseptics-external+vaccines-live+feed-additives+disinfectants-and-hygiene+4c81f131016c84203e1525aef538e4ed.cache): failed to open stream: Invalid argument`

![screenshot_4](https://cloud.githubusercontent.com/assets/5707348/18818749/81d37a3a-838a-11e6-831e-28be5af410ab.jpg)

ProcessWire version: 3.0.33
PHP version:  5.6
MySQL version:  5.5

**Comment by isellsoap** [comment] 2016-09-26 07:37
Can you confirm that this also happens with an URL which has only one URL segment in it? I don’t think this issue has something to do with the amount of URL segments.

I couldn’t reproduce the issue on MacOS, but I found some threads on the web that talk about Windows having sometimes issues with `file_put_contents` and specific URL syntaxes. So this issue could potentially be OS-specific.

**Comment by matjazpotocnik** [comment] 2016-09-26 09:13
It looks like Windows specific: the maximum length for a path is MAX_PATH, which is defined as 260 characters. While it is possible to create a file with longer filename from command prompt (I didn't manage to create it using PHP's file_put_contents), there are problems later on in windows explorer so I guess it would be good to check the length of $filename and issue some warning or at least silent the file_put_contents (not good).

Starting in Windows 10, version 1607, MAX_PATH limitations have been removed from common Win32 file and directory functions. However, you must opt-in to the new behavior.

**Comment by Lazerproof** [comment] 2016-09-26 09:17
No, I can`t. It works as expected when there are 4 or 5 segments, but if more I got this worning. So, maybe you are right and it`s related to OS or length of filename. I will try to reproduce it on web hosting.

**Comment by isellsoap** [comment] 2016-09-26 09:23
Ok, I’ll wait for a comment of yours.

If this issue is indeed OS-specific than I think the only feasible solution would be to restructure the data model of your specific ProcessWire installation to not work so extensively/extremely with URL segments but rather with real page URLs. But than again, I don’t no if that’s to much of an effort to change for you.

**Comment by ryancramerdesign** [comment] 2016-09-26 10:29
Unless those URL segments are required to be in a specific order, this could be a potential issue even if  it was working. The problem is it could result in a near infinite number of cache files. It would probably be better not to cache something like this and instead use GET variables/query string. This is really the ideal use of a query string. If caching is necessary, I'd instead use the $cache API variable to cache the expensive parts, but make sure you sort the order of the items in the query ahead of time so that it doesn't have to maintain different caches for the same queries in different orders. Otherwise you'll be stuck with the infinite cache problem again. 

For example, URL:
`site.dev/products/pigs/?query=antibiotics-injectable,antibiotics-external,antibiotics-oral-solutions,antiseptics-external,vaccines-live,feed-additives,disinfectants-and-hygiene`
~~~~~
$segments = $input->get->names('query');
sort($segments);
~~~~~
After the above, $segments will be a sanitized and sorted array ready to use in whatever query you are using it in.

- antibiotics-external
- antibiotics-injectable
- antibiotics-oral-solutions
- antiseptics-external
- disinfectants-and-hygiene
- feed-additives
- vaccines-live

**Comment by isellsoap** [comment] 2016-09-26 11:07
@Lazerproof It seems that this isn’t _per se_ a ProcessWire issue and @ryancramerdesign’s suggestions sound pretty reasonable. Ok if I close the issue?

**Comment by Lazerproof** [comment] 2016-09-26 19:39
@isellsoap Yes, of course. Thanks.

@ryancramerdesign Thank you for suggestions. 
At the begining of the project I was thinking to go with GET parameters, but they are not SEF, so it's not an option for the project. 

I'm using POST method in search form and after submitting I sort segments by template and id, limit number of pages which will be processed to 5 and then make redirection to target page.

I have 16 types of products which can be combined to groups from 1 to 5 with specified sorting, so it will be combination ( not arrangement and permutation ), based on this, if I'm not mistaken, I will have 6884 cache files.

Is it manageable amount of pages for PW ?

**Comment by isellsoap** [comment] 2016-09-26 19:43
PW can handle this easily. See also the following forum threads to get a feeling as to what PW is capable of:

* [Question about "extreme" scale, hundred of thousand (maybe millions) of pages!](https://processwire.com/talk/topic/2503-question-about-extreme-scale-hundred-of-thousand-maybe-millions-of-pages/)
* [Site with millions of „pages”](https://processwire.com/talk/topic/9491-site-with-millions-of-„pages”/)
* [Feasability of using PW to create a SaaS platform such as Airbnb?](https://processwire.com/talk/topic/10455-feasability-of-using-pw-to-create-a-saas-platform-such-as-airbnb/)

**Closed by isellsoap** 2016-09-26 19:43 UTC
Labels: os-specific
