### ISSUE TITLE
Using Selector to query page field within repeater field returns incorrect results if no matches found

### ISSUE THREAD

**Issue by jlahijani** [processwire/processwire-issues#746] opened 2018-11-08 15:50 UTC
Let's say I have a template called "mytemplate" and a repeater field on it called "variations".

Now let's say there's a Page field assigned to the repeater field called "animal". (sorry can't think of a better name right now)

Let's say there's a text field called "description" on the "animal" Page template.

If I do a selector like this...

```
template=mytemplate,variations.animal.description=dog
```

It will return the correct results if there actually is a match.  However, if there is not a match, it will return a handful of other results that shouldn't be there.

Also, not sure if this is related:
https://github.com/processwire/processwire-issues/issues/205

**Comment by netcarver** [comment] 2019-02-15 14:02
@ryancramerdesign Ryan, sounds like a potential bug in selector handling.

**Comment by Toutouwai** [comment] 2019-02-15 21:37
I think the #205 issue mentioned is probably the same issue (a Repeater field is much like a Page Reference field when it comes to matching in a selector).

**Comment by netcarver** [comment] 2019-02-15 21:50
/remind me to review this issue in 1 week

**Comment by ryancramerdesign** [comment] 2019-02-28 14:49
@netcarver I've looked at this before and not been able to figure this one out. But since this seems to be a duplicate of #205, I'm  thinking one should be closed? Usually I'd say keep the first one, but since this one seems simpler to reproduce than #205 so maybe this one should be left open instead? Thanks.

**Comment by jlahijani** [comment] 2019-03-01 18:07
@ryancramerdesign Here's a video demonstrating the issue:
https://www.youtube.com/watch?v=CAWDGCRfAl4

**Comment by netcarver** [comment] 2019-03-05 22:22
@Toutouwai @jlahijani @ryancramerdesign Can this issue be closed now that #205 has been closed?

**Comment by ryancramerdesign** [comment] 2019-03-08 15:09
@netcarver I'm pretty sure this is the same issue and this one can likely be closed, but want to confirm with @jlahijani just to be sure.

**Closed** 2019-03-08 21:48 UTC
Labels: status: fixed (please confirm)
